$schema: http://json-schema.org/draft-07/schema#
title: EvalLogsDataSourceConfig
description: 'A LogsDataSourceConfig which specifies the metadata property of your
  logs query.

  This is usually metadata like `usecase=chatbot` or `prompt-version=v2`, etc.

  The schema returned by this data source config is used to defined what variables
  are available in your evals.

  `item` and `sample` are both defined when using this data source config.

  '
type: object
properties:
  metadata:
    $ref: metadata.yaml
  schema:
    additionalProperties: true
    description: 'The json schema for the run data source items.

      Learn how to build JSON schemas [here](https://json-schema.org/).

      '
    type: object
  type:
    default: logs
    description: The type of data source. Always `logs`.
    enum:
    - logs
    type: string
required:
- type
- schema
