// Code generated by schema2code at 2026-02-23 14:46:19. DO NOT EDIT.


/**
 * Instruction describing how to update a file via the apply_patch tool.
 */
export interface ApplyPatchUpdateFileOperation {
  /**
   * Diff to apply.
   */
  diff: string;
  /**
   * Path of the file to update.
   */
  path: string;
  /**
   * Update an existing file with the provided diff.
   */
  type: 'update_file';
}