// Code generated by schema2code at 2026-02-23 14:46:22. DO NOT EDIT.


/**
 * The format of the output, in one of these options: `json`, `text`, `srt`, `verbose_json`, `vtt`, or `diarized_json`. For `gpt-4o-transcribe` and `gpt-4o-mini-transcribe`, the only supported format is `json`. For `gpt-4o-transcribe-diarize`, the supported formats are `json`, `text`, and `diarized_json`, with `diarized_json` required to receive speaker annotations.

 */
export type AudioResponseFormat = 'json' | 'text' | 'srt' | 'verbose_json' | 'vtt' | 'diarized_json';

/**
 * Constant values for AudioResponseFormat
 */
export const AudioResponseFormatValues = {
  /** json */
  JSON: 'json',
  /** text */
  TEXT: 'text',
  /** srt */
  SRT: 'srt',
  /** verbose_json */
  VERBOSE_JSON: 'verbose_json',
  /** vtt */
  VTT: 'vtt',
  /** diarized_json */
  DIARIZED_JSON: 'diarized_json'
} as const;