// Code generated by schema2code at 2026-02-23 14:46:20. DO NOT EDIT.


import { CreateChatCompletionResponse } from './CreateChatCompletionResponse';



/**
 * An object representing a list of Chat Completions.

 */
export interface ChatCompletionList {
  /**
   * An array of chat completion objects.

   */
  data: (CreateChatCompletionResponse)[];
  /**
   * The identifier of the first chat completion in the data array.
   */
  first_id: string;
  /**
   * Indicates whether there are more Chat Completions available.
   */
  has_more: boolean;
  /**
   * The identifier of the last chat completion in the data array.
   */
  last_id: string;
  /**
   * The type of this object. It is always set to "list".

   */
  object: 'list';
}