// Code generated by schema2code at 2026-02-23 14:46:22. DO NOT EDIT.


import { ChatCompletionMessageToolCallChunk } from './ChatCompletionMessageToolCallChunk';



/**
 * Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
 */
export interface FunctionCall {
  /**
   * The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
   */
  arguments?: string;
  /**
   * The name of the function to call.
   */
  name?: string;
}

/**
 * A chat completion delta generated by streamed model responses.
 */
export interface ChatCompletionStreamResponseDelta {
  content?: string | unknown;
  /**
   * Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
   */
  function_call?: FunctionCall;
  refusal?: string | unknown;
  /**
   * The role of the author of this message.
   */
  role?: 'developer' | 'system' | 'user' | 'assistant' | 'tool';
  tool_calls?: (ChatCompletionMessageToolCallChunk)[];
}