// Code generated by schema2code at 2026-02-23 14:46:24. DO NOT EDIT.


import { FunctionObject } from './FunctionObject';



/**
 * A function tool that can be used to generate a response.

 */
export interface ChatCompletionTool {
  function: FunctionObject;
  /**
   * The type of the tool. Currently, only `function` is supported.
   */
  type: 'function';
}