// Code generated by schema2code at 2026-02-23 14:46:21. DO NOT EDIT.


import { ComputerEnvironment } from './ComputerEnvironment';



/**
 * A tool that controls a virtual computer. Learn more about the [computer tool](https://platform.openai.com/docs/guides/tools-computer-use).
 */
export interface ComputerUsePreviewTool {
  /**
   * The height of the computer display.
   */
  display_height: number;
  /**
   * The width of the computer display.
   */
  display_width: number;
  /**
   * The type of computer environment to control.
   */
  environment: ComputerEnvironment;
  /**
   * The type of the computer use tool. Always `computer_use_preview`.
   */
  type: 'computer_use_preview';
}