// Code generated by schema2code at 2026-02-23 14:46:21. DO NOT EDIT.


/**
 * A citation for a container file used to generate a model response.
 */
export interface ContainerFileCitationBody {
  /**
   * The ID of the container file.
   */
  container_id: string;
  /**
   * The index of the last character of the container file citation in the message.
   */
  end_index: number;
  /**
   * The ID of the file.
   */
  file_id: string;
  /**
   * The filename of the container file cited.
   */
  filename: string;
  /**
   * The index of the first character of the container file citation in the message.
   */
  start_index: number;
  /**
   * The type of the container file citation. Always `container_file_citation`.
   */
  type: 'container_file_citation';
}