// Code generated by schema2code at 2026-02-23 14:46:23. DO NOT EDIT.


export interface EvalGraderScoreModel {
  /**
   * The input messages evaluated by the grader. Supports text, output text, input image, and input audio content blocks, and may include template strings.

   */
  input: (EvalItem)[];
  /**
   * The model to use for the evaluation.
   */
  model: string;
  /**
   * The name of the grader.
   */
  name: string;
  /**
   * The range of the score. Defaults to `[0, 1]`.
   */
  range?: (number)[];
  /**
   * The sampling parameters for the model.
   */
  sampling_params?: SamplingParams;
  /**
   * The object type, which is always `score_model`.
   */
  type: 'score_model';
  /**
   * The threshold for the score.
   */
  pass_threshold?: number;
}