// Code generated by schema2code at 2026-02-23 14:46:27. DO NOT EDIT.


export interface HybridSearchOptions {
  /**
   * The weight of the embedding in the reciprocal ranking fusion.
   */
  embedding_weight: number;
  /**
   * The weight of the text in the reciprocal ranking fusion.
   */
  text_weight: number;
}