// Code generated by schema2code at 2026-02-23 14:46:25. DO NOT EDIT.


/**
 * The input tokens detailed information for the image generation.
 */
export interface ImageGenInputUsageDetails {
  /**
   * The number of image tokens in the input prompt.
   */
  image_tokens: number;
  /**
   * The number of text tokens in the input prompt.
   */
  text_tokens: number;
}