// Code generated by schema2code at 2026-02-23 14:46:25. DO NOT EDIT.


/**
 * A list of one or many input items to the model, containing different content 
types.

 */
export interface InputMessageContentList {
}