// Code generated by schema2code at 2026-02-23 14:46:25. DO NOT EDIT.


import { VectorStoreFileObject } from './VectorStoreFileObject';



export interface ListVectorStoreFilesResponse {
  data: (VectorStoreFileObject)[];
  first_id: string;
  has_more: boolean;
  last_id: string;
  object: string;
}