// Code generated by schema2code at 2026-02-23 14:46:25. DO NOT EDIT.


export type LocalShellCallStatus = 'in_progress' | 'completed' | 'incomplete';

/**
 * Constant values for LocalShellCallStatus
 */
export const LocalShellCallStatusValues = {
  /** in_progress */
  IN_PROGRESS: 'in_progress',
  /** completed */
  COMPLETED: 'completed',
  /** incomplete */
  INCOMPLETE: 'incomplete'
} as const;