// Code generated by schema2code at 2026-02-23 14:46:33. DO NOT EDIT.


/**
 * Indicates that a thread is locked and cannot accept new input.
 */
export interface LockedStatus {
  reason: string | unknown;
  /**
   * Status discriminator that is always `locked`.
   */
  type: 'locked';
}