// Code generated by schema2code at 2026-02-23 14:46:29. DO NOT EDIT.


/**
 * A tool available on an MCP server.

 */
export interface MCPListToolsTool {
  annotations?: Record<string, unknown> | unknown;
  description?: string | unknown;
  /**
   * The JSON schema describing the tool's input.

   */
  input_schema: Record<string, unknown>;
  /**
   * The name of the tool.

   */
  name: string;
}