// Code generated by schema2code at 2026-02-23 14:46:30. DO NOT EDIT.


import { MCPToolFilter } from './McpToolFilter';



/**
 * Give the model access to additional tools via remote Model Context Protocol
(MCP) servers. [Learn more about MCP](https://platform.openai.com/docs/guides/tools-remote-mcp).

 */
export interface MCPTool {
  allowed_tools?: (string)[] | MCPToolFilter | unknown;
  /**
   * An OAuth access token that can be used with a remote MCP server, either
with a custom MCP server URL or a service connector. Your application
must handle the OAuth authorization flow and provide the token here.

   */
  authorization?: string;
  /**
   * Identifier for service connectors, like those available in ChatGPT. One of
`server_url` or `connector_id` must be provided. Learn more about service
connectors [here](https://platform.openai.com/docs/guides/tools-remote-mcp#connectors).

Currently supported `connector_id` values are:

- Dropbox: `connector_dropbox`
- Gmail: `connector_gmail`
- Google Calendar: `connector_googlecalendar`
- Google Drive: `connector_googledrive`
- Microsoft Teams: `connector_microsoftteams`
- Outlook Calendar: `connector_outlookcalendar`
- Outlook Email: `connector_outlookemail`
- SharePoint: `connector_sharepoint`

   */
  connector_id?: 'connector_dropbox' | 'connector_gmail' | 'connector_googlecalendar' | 'connector_googledrive' | 'connector_microsoftteams' | 'connector_outlookcalendar' | 'connector_outlookemail' | 'connector_sharepoint';
  headers?: Record<string, string> | unknown;
  require_approval?: RequireApprovalOption0Option0 | 'always' | 'never' | unknown;
  /**
   * Optional description of the MCP server, used to provide more context.

   */
  server_description?: string;
  /**
   * A label for this MCP server, used to identify it in tool calls.

   */
  server_label: string;
  /**
   * The URL for the MCP server. One of `server_url` or `connector_id` must be
provided.

   */
  server_url?: string;
  /**
   * The type of the MCP tool. Always `mcp`.
   */
  type: 'mcp';
}