// Code generated by schema2code at 2026-02-23 14:46:26. DO NOT EDIT.


/**
 * An object describing text to classify.
 */
export interface ModerationTextInput {
  /**
   * A string of text to classify.
   */
  text: string;
  /**
   * Always `text`.
   */
  type: 'text';
}