// Code generated by schema2code at 2026-02-23 14:46:27. DO NOT EDIT.


import { Project } from './Project';



export interface ProjectListResponse {
  data: (Project)[];
  first_id: string;
  has_more: boolean;
  last_id: string;
  object: 'list';
}