// Code generated by schema2code at 2026-02-23 14:46:27. DO NOT EDIT.


/**
 * Request payload for creating a custom role.
 */
export interface PublicCreateOrganizationRoleBody {
  /**
   * Optional description of the role.
   */
  description?: string | unknown;
  /**
   * Permissions to grant to the role.
   */
  permissions: (string)[];
  /**
   * Unique name for the role.
   */
  role_name: string;
}