// Code generated by schema2code at 2026-02-23 14:46:28. DO NOT EDIT.


import { RealtimeSessionCreateRequestGA } from './RealtimeSessionCreateRequestGa';



/**
 * Parameters required to initiate a realtime call and receive the SDP answer
needed to complete a WebRTC peer connection. Provide an SDP offer generated
by your client and optionally configure the session that will answer the call.
 */
export interface RealtimeCallCreateRequest {
  /**
   * WebRTC Session Description Protocol (SDP) offer generated by the caller.
   */
  sdp: string;
  /**
   * Optional session configuration to apply before the realtime session is
created. Use the same parameters you would send in a [`create client secret`](https://platform.openai.com/docs/api-reference/realtime-sessions/create-realtime-client-secret)
request.
   */
  session?: RealtimeSessionCreateRequestGA;
}