// Code generated by schema2code at 2026-02-23 14:46:28. DO NOT EDIT.


import { RealtimeBetaResponse } from './RealtimeBetaResponse';



/**
 * Returned when a new Response is created. The first event of response creation,
where the response is in an initial state of `in_progress`.

 */
export interface RealtimeBetaServerEventResponseCreated {
  /**
   * The unique ID of the server event.
   */
  event_id: string;
  response: RealtimeBetaResponse;
  /**
   * The event type, must be `response.created`.
   */
  type: string;
}