// Code generated by schema2code at 2026-02-23 14:46:29. DO NOT EDIT.


import { RealtimeSessionCreateRequestGA } from './RealtimeSessionCreateRequestGa';

import { RealtimeTranscriptionSessionCreateRequestGA } from './RealtimeTranscriptionSessionCreateRequestGa';



/**
 * Configuration for the client secret expiration. Expiration refers to the time after which
a client secret will no longer be valid for creating sessions. The session itself may
continue after that time once started. A secret can be used to create multiple sessions
until it expires.

 */
export interface Clientsecretexpiration {
  /**
   * The anchor point for the client secret expiration, meaning that `seconds` will be added to the `created_at` time of the client secret to produce an expiration timestamp. Only `created_at` is currently supported.

   */
  anchor?: 'created_at';
  /**
   * The number of seconds from the anchor point to the expiration. Select a value between `10` and `7200` (2 hours). This default to 600 seconds (10 minutes) if not specified.

   */
  seconds?: number;
}

/**
 * Create a session and client secret for the Realtime API. The request can specify
either a realtime or a transcription session configuration.
[Learn more about the Realtime API](https://platform.openai.com/docs/guides/realtime).

 */
export interface RealtimeCreateClientSecretRequest {
  /**
   * Configuration for the client secret expiration. Expiration refers to the time after which
a client secret will no longer be valid for creating sessions. The session itself may
continue after that time once started. A secret can be used to create multiple sessions
until it expires.

   */
  expires_after?: ExpiresAfter;
  /**
   * Session configuration to use for the client secret. Choose either a realtime
session or a transcription session.

   */
  session?: RealtimeSessionCreateRequestGA | RealtimeTranscriptionSessionCreateRequestGA;
}