// Code generated by schema2code at 2026-02-23 14:46:30. DO NOT EDIT.


/**
 * Reasoning text from the model.
 */
export interface ReasoningTextContent {
  /**
   * The reasoning text from the model.
   */
  text: string;
  /**
   * The type of the reasoning text. Always `reasoning_text`.
   */
  type: 'reasoning_text';
}