// Code generated by schema2code at 2026-02-23 14:46:32. DO NOT EDIT.


/**
 * A detailed breakdown of the input tokens.
 */
export interface InputTokensDetails {
  /**
   * The number of tokens that were retrieved from the cache. 
[More on prompt caching](https://platform.openai.com/docs/guides/prompt-caching).

   */
  cached_tokens: number;
}

/**
 * A detailed breakdown of the output tokens.
 */
export interface OutputTokensDetails {
  /**
   * The number of reasoning tokens.
   */
  reasoning_tokens: number;
}

/**
 * Represents token usage details including input tokens, output tokens,
a breakdown of output tokens, and the total tokens used.

 */
export interface ResponseUsage {
  /**
   * The number of input tokens.
   */
  input_tokens: number;
  /**
   * A detailed breakdown of the input tokens.
   */
  input_tokens_details: InputTokensDetails;
  /**
   * The number of output tokens.
   */
  output_tokens: number;
  /**
   * A detailed breakdown of the output tokens.
   */
  output_tokens_details: OutputTokensDetails;
  /**
   * The total number of tokens used.
   */
  total_tokens: number;
}