// Code generated by schema2code at 2026-02-23 14:46:32. DO NOT EDIT.


/**
 * The function definition.
 */
export interface Function {
  /**
   * The arguments that the model expects you to pass to the function.
   */
  arguments: string;
  /**
   * The name of the function.
   */
  name: string;
}

/**
 * Tool call objects
 */
export interface RunToolCallObject {
  /**
   * The function definition.
   */
  function: Function;
  /**
   * The ID of the tool call. This ID must be referenced when you submit the tool outputs in using the [Submit tool outputs to run](https://platform.openai.com/docs/api-reference/runs/submitToolOutputs) endpoint.
   */
  id: string;
  /**
   * The type of tool call the output is required for. For now, this is always `function`.
   */
  type: 'function';
}