// Code generated by schema2code at 2026-02-23 14:46:32. DO NOT EDIT.


/**
 * Forces the model to call the shell tool when a tool call is required.
 */
export interface SpecificFunctionShellParam {
  /**
   * The tool to call. Always `shell`.
   */
  type: 'shell';
}