// Code generated by schema2code at 2026-02-23 14:46:33. DO NOT EDIT.


export interface TranscriptionWord {
  /**
   * End time of the word in seconds.
   */
  end: number;
  /**
   * Start time of the word in seconds.
   */
  start: number;
  /**
   * The text content of the word.
   */
  word: string;
}