// Code generated by schema2code at 2026-02-23 14:46:34. DO NOT EDIT.


import { UrlAnnotationSource } from './UrlAnnotationSource';



/**
 * Annotation that references a URL.
 */
export interface UrlAnnotation {
  /**
   * URL referenced by the annotation.
   */
  source: UrlAnnotationSource;
  /**
   * Type discriminator that is always `url` for this annotation.
   */
  type: 'url';
}