// Code generated by schema2code at 2026-02-23 14:46:35. DO NOT EDIT.


import { WebSearchApproximateLocation } from './WebSearchApproximateLocation';



/**
 * Search the Internet for sources related to the prompt. Learn more about the
[web search tool](https://platform.openai.com/docs/guides/tools-web-search).

 */
export interface WebSearchTool {
  filters?: FiltersOption0 | unknown;
  /**
   * High level guidance for the amount of context window space to use for the search. One of `low`, `medium`, or `high`. `medium` is the default.
   */
  search_context_size?: 'low' | 'medium' | 'high';
  /**
   * The type of the web search tool. One of `web_search` or `web_search_2025_08_26`.
   */
  type: 'web_search' | 'web_search_2025_08_26';
  user_location?: WebSearchApproximateLocation;
}