# Code generated by schema2code at 2026-02-23 18:05:01. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ApplyPatchDeleteFileOperation(BaseModel):
    """Instruction for deleting an existing file via the apply_patch tool."""
    type: Annotated[Literal["delete_file"], Field(default='delete_file', description="The operation type. Always `delete_file`.")]
    """The operation type. Always `delete_file`."""
    path: Annotated[str, Field(..., description="Path of the file to delete relative to the workspace root.")]
    """Path of the file to delete relative to the workspace root."""

    class Config:
        extra = "ignore"