# Code generated by schema2code at 2026-02-23 14:46:55. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .assistant_tools_code import AssistantToolsCode
from .assistant_tools_file_search import AssistantToolsFileSearch
from .assistant_tools_file_search import FileSearch
from .assistant_tools_function import AssistantToolsFunction
from .file_search_ranker import FileSearchRanker
from .file_search_ranking_options import FileSearchRankingOptions
from .function_object import FunctionObject
from .function_parameters import FunctionParameters
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



AssistantTool = Union[AssistantToolsCode, AssistantToolsFileSearch, AssistantToolsFunction]