# Code generated by schema2code at 2026-02-23 14:46:36. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class BatchFileExpirationAfter(BaseModel):
    """The expiration policy for the output and/or error file that are generated for a batch."""
    anchor: Annotated[Literal["created_at"], Field(..., description="Anchor timestamp after which the expiration policy applies. Supported anchors: `created_at`. Note that the anchor is the file creation time, not the time the batch is created.")]
    """Anchor timestamp after which the expiration policy applies. Supported anchors: `created_at`. Note that the anchor is the file creation time, not the time the batch is created."""
    seconds: Annotated[int, Field(..., description="The number of seconds after the anchor time that the file will expire. Must be between 3600 (1 hour) and 2592000 (30 days).", ge=3600, le=2592000)]
    """The number of seconds after the anchor time that the file will expire. Must be between 3600 (1 hour) and 2592000 (30 days)."""

    class Config:
        extra = "ignore"