# Code generated by schema2code at 2026-02-23 18:05:01. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class BatchRequestCounts(BaseModel):
    """The request counts for different statuses within the batch."""
    total: Annotated[int, Field(..., description="Total number of requests in the batch.")]
    """Total number of requests in the batch."""
    completed: Annotated[int, Field(..., description="Number of requests that have been completed successfully.")]
    """Number of requests that have been completed successfully."""
    failed: Annotated[int, Field(..., description="Number of requests that have failed.")]
    """Number of requests that have failed."""

    class Config:
        extra = "ignore"

class Metadata(BaseModel):
    pass

class BatchError(BaseModel):
    code: Annotated[Optional[str], Field(default=None, description="An error code identifying the error type.")] = None
    """An error code identifying the error type."""
    message: Annotated[Optional[str], Field(default=None, description="A human-readable message providing more details about the error.")] = None
    """A human-readable message providing more details about the error."""
    param: Annotated[Optional[Union[str, Any]], Field(default=None)] = None
    line: Annotated[Optional[Union[int, Any]], Field(default=None)] = None

    class Config:
        extra = "ignore"

class Errors(BaseModel):
    object: Annotated[Optional[str], Field(default=None, description="The object type, which is always `list`.")] = None
    """The object type, which is always `list`."""
    data: Annotated[Optional[List[BatchError]], Field(default=None)] = None

    class Config:
        extra = "ignore"

class Usage(BaseModel):
    """Represents token usage details including input tokens, output tokens, a
breakdown of output tokens, and the total tokens used. Only populated on
batches created after September 7, 2025.
"""
    input_tokens: Annotated[int, Field(..., description="The number of input tokens.")]
    """The number of input tokens."""
    input_tokens_details: Annotated[InputTokensDetails, Field(..., description="A detailed breakdown of the input tokens.")]
    """A detailed breakdown of the input tokens."""
    output_tokens: Annotated[int, Field(..., description="The number of output tokens.")]
    """The number of output tokens."""
    output_tokens_details: Annotated[OutputTokensDetails, Field(..., description="A detailed breakdown of the output tokens.")]
    """A detailed breakdown of the output tokens."""
    total_tokens: Annotated[int, Field(..., description="The total number of tokens used.")]
    """The total number of tokens used."""

    class Config:
        extra = "ignore"

class InputTokensDetails(BaseModel):
    """A detailed breakdown of the input tokens."""
    cached_tokens: Annotated[int, Field(..., description="The number of tokens that were retrieved from the cache. [More on prompt caching](https://platform.openai.com/docs/guides/prompt-caching). ")]
    """The number of tokens that were retrieved from the cache. [More on prompt caching](https://platform.openai.com/docs/guides/prompt-caching). """

    class Config:
        extra = "ignore"

class OutputTokensDetails(BaseModel):
    """A detailed breakdown of the output tokens."""
    reasoning_tokens: Annotated[int, Field(..., description="The number of reasoning tokens.")]
    """The number of reasoning tokens."""

    class Config:
        extra = "ignore"

class Batch(BaseModel):
    id: Annotated[str, Field(...)]
    object: Annotated[Literal["batch"], Field(..., description="The object type, which is always `batch`.")]
    """The object type, which is always `batch`."""
    endpoint: Annotated[str, Field(..., description="The OpenAI API endpoint used by the batch.")]
    """The OpenAI API endpoint used by the batch."""
    model: Annotated[Optional[str], Field(default=None, description="Model ID used to process the batch, like `gpt-5-2025-08-07`. OpenAI offers a wide range of models with different capabilities, performance characteristics, and price points. Refer to the [model guide](https://platform.openai.com/docs/models) to browse and compare available models. ")] = None
    """Model ID used to process the batch, like `gpt-5-2025-08-07`. OpenAI offers a wide range of models with different capabilities, performance characteristics, and price points. Refer to the [model guide](https://platform.openai.com/docs/models) to browse and compare available models. """
    errors: Annotated[Optional[Errors], Field(default=None)] = None
    input_file_id: Annotated[str, Field(..., description="The ID of the input file for the batch.")]
    """The ID of the input file for the batch."""
    completion_window: Annotated[str, Field(..., description="The time frame within which the batch should be processed.")]
    """The time frame within which the batch should be processed."""
    status: Annotated[Literal["validating", "failed", "in_progress", "finalizing", "completed", "expired", "cancelling", "cancelled"], Field(..., description="The current status of the batch.")]
    """The current status of the batch."""
    output_file_id: Annotated[Optional[str], Field(default=None, description="The ID of the file containing the outputs of successfully executed requests.")] = None
    """The ID of the file containing the outputs of successfully executed requests."""
    error_file_id: Annotated[Optional[str], Field(default=None, description="The ID of the file containing the outputs of requests with errors.")] = None
    """The ID of the file containing the outputs of requests with errors."""
    created_at: Annotated[int, Field(..., description="The Unix timestamp (in seconds) for when the batch was created.")]
    """The Unix timestamp (in seconds) for when the batch was created."""
    in_progress_at: Annotated[Optional[int], Field(default=None, description="The Unix timestamp (in seconds) for when the batch started processing.")] = None
    """The Unix timestamp (in seconds) for when the batch started processing."""
    expires_at: Annotated[Optional[int], Field(default=None, description="The Unix timestamp (in seconds) for when the batch will expire.")] = None
    """The Unix timestamp (in seconds) for when the batch will expire."""
    finalizing_at: Annotated[Optional[int], Field(default=None, description="The Unix timestamp (in seconds) for when the batch started finalizing.")] = None
    """The Unix timestamp (in seconds) for when the batch started finalizing."""
    completed_at: Annotated[Optional[int], Field(default=None, description="The Unix timestamp (in seconds) for when the batch was completed.")] = None
    """The Unix timestamp (in seconds) for when the batch was completed."""
    failed_at: Annotated[Optional[int], Field(default=None, description="The Unix timestamp (in seconds) for when the batch failed.")] = None
    """The Unix timestamp (in seconds) for when the batch failed."""
    expired_at: Annotated[Optional[int], Field(default=None, description="The Unix timestamp (in seconds) for when the batch expired.")] = None
    """The Unix timestamp (in seconds) for when the batch expired."""
    cancelling_at: Annotated[Optional[int], Field(default=None, description="The Unix timestamp (in seconds) for when the batch started cancelling.")] = None
    """The Unix timestamp (in seconds) for when the batch started cancelling."""
    cancelled_at: Annotated[Optional[int], Field(default=None, description="The Unix timestamp (in seconds) for when the batch was cancelled.")] = None
    """The Unix timestamp (in seconds) for when the batch was cancelled."""
    request_counts: Annotated[Optional[BatchRequestCounts], Field(default=None)] = None
    usage: Annotated[Optional[Usage], Field(default=None, description="Represents token usage details including input tokens, output tokens, a breakdown of output tokens, and the total tokens used. Only populated on batches created after September 7, 2025. ")] = None
    """Represents token usage details including input tokens, output tokens, a breakdown of output tokens, and the total tokens used. Only populated on batches created after September 7, 2025. """
    metadata: Annotated[Optional[Metadata], Field(default=None)] = None

    class Config:
        extra = "ignore"

Batch.model_rebuild()