# Code generated by schema2code at 2026-02-23 18:05:01. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class InputAudio(BaseModel):
    data: Annotated[str, Field(..., description="Base64 encoded audio data.")]
    """Base64 encoded audio data."""
    format: Annotated[Literal["wav", "mp3"], Field(..., description="The format of the encoded audio data. Currently supports \"wav\" and \"mp3\". ")]
    """The format of the encoded audio data. Currently supports \"wav\" and \"mp3\". """

    class Config:
        extra = "ignore"

class AudioContentPart(BaseModel):
    """Learn about [audio inputs](https://platform.openai.com/docs/guides/audio).
"""
    type: Annotated[Literal["input_audio"], Field(..., description="The type of the content part. Always `input_audio`.")]
    """The type of the content part. Always `input_audio`."""
    input_audio: Annotated[InputAudio, Field(...)]

    class Config:
        extra = "ignore"

AudioContentPart.model_rebuild()