# Code generated by schema2code at 2026-02-23 18:05:01. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class CreateChatCompletionResponse(BaseModel):
    """Represents a chat completion response returned by model, based on the provided input."""
    id: Annotated[str, Field(..., description="A unique identifier for the chat completion.")]
    """A unique identifier for the chat completion."""
    choices: Annotated[List[ChoicesItem], Field(..., description="A list of chat completion choices. Can be more than one if `n` is greater than 1.")]
    """A list of chat completion choices. Can be more than one if `n` is greater than 1."""
    created: Annotated[int, Field(..., description="The Unix timestamp (in seconds) of when the chat completion was created.")]
    """The Unix timestamp (in seconds) of when the chat completion was created."""
    model: Annotated[str, Field(..., description="The model used for the chat completion.")]
    """The model used for the chat completion."""
    service_tier: Annotated[Optional[ServiceTier], Field(default=None)] = None
    system_fingerprint: Annotated[Optional[str], Field(default=None, description="This fingerprint represents the backend configuration that the model runs with.  Can be used in conjunction with the `seed` request parameter to understand when backend changes have been made that might impact determinism. ")] = None
    """This fingerprint represents the backend configuration that the model runs with.  Can be used in conjunction with the `seed` request parameter to understand when backend changes have been made that might impact determinism. """
    object: Annotated[Literal["chat.completion"], Field(..., description="The object type, which is always `chat.completion`.")]
    """The object type, which is always `chat.completion`."""
    usage: Annotated[Optional[CompletionUsage], Field(default=None)] = None

    class Config:
        extra = "ignore"

class ChatCompletionResponseMessage(BaseModel):
    """A chat completion message generated by the model."""
    content: Annotated[Union[str, Any], Field(...)]
    refusal: Annotated[Union[str, Any], Field(...)]
    tool_calls: Annotated[Optional[ChatCompletionMessageToolCalls], Field(default=None)] = None
    annotations: Annotated[Optional[List[AnnotationsItem]], Field(default=None, description="Annotations for the message, when applicable, as when using the [web search tool](https://platform.openai.com/docs/guides/tools-web-search?api-mode=chat). ")] = None
    """Annotations for the message, when applicable, as when using the [web search tool](https://platform.openai.com/docs/guides/tools-web-search?api-mode=chat). """
    role: Annotated[Literal["assistant"], Field(..., description="The role of the author of this message.")]
    """The role of the author of this message."""
    function_call: Annotated[Optional[FunctionCall], Field(default=None, description="Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.")] = None
    """Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model."""
    audio: Annotated[Optional[Union[Audio, Any]], Field(default=None)] = None

    class Config:
        extra = "ignore"

class ChatCompletionMessageToolCalls(BaseModel):
    """The tool calls generated by the model, such as function calls."""
    pass

class ChatCompletionMessageCustomToolCall(BaseModel):
    """A call to a custom tool created by the model.
"""
    id: Annotated[str, Field(..., description="The ID of the tool call.")]
    """The ID of the tool call."""
    type: Annotated[Literal["custom"], Field(..., description="The type of the tool. Always `custom`.")]
    """The type of the tool. Always `custom`."""
    custom: Annotated[Custom, Field(..., description="The custom tool that the model called.")]
    """The custom tool that the model called."""

    class Config:
        extra = "ignore"

class ChatCompletionMessageToolCall(BaseModel):
    """A call to a function tool created by the model.
"""
    id: Annotated[str, Field(..., description="The ID of the tool call.")]
    """The ID of the tool call."""
    type: Annotated[Literal["function"], Field(..., description="The type of the tool. Currently, only `function` is supported.")]
    """The type of the tool. Currently, only `function` is supported."""
    function: Annotated[Function, Field(..., description="The function that the model called.")]
    """The function that the model called."""

    class Config:
        extra = "ignore"

class CompletionUsage(BaseModel):
    """Usage statistics for the completion request."""
    completion_tokens: Annotated[int, Field(default=0, description="Number of tokens in the generated completion.")]
    """Number of tokens in the generated completion."""
    prompt_tokens: Annotated[int, Field(default=0, description="Number of tokens in the prompt.")]
    """Number of tokens in the prompt."""
    total_tokens: Annotated[int, Field(default=0, description="Total number of tokens used in the request (prompt + completion).")]
    """Total number of tokens used in the request (prompt + completion)."""
    completion_tokens_details: Annotated[Optional[CompletionTokensDetails], Field(default=None, description="Breakdown of tokens used in a completion.")] = None
    """Breakdown of tokens used in a completion."""
    prompt_tokens_details: Annotated[Optional[PromptTokensDetails], Field(default=None, description="Breakdown of tokens used in the prompt.")] = None
    """Breakdown of tokens used in the prompt."""

    class Config:
        extra = "ignore"

ServiceTier = Union[Literal["auto", "default", "flex", "scale", "priority"]]

class ChatCompletionTokenLogprob(BaseModel):
    token: Annotated[str, Field(..., description="The token.")]
    """The token."""
    logprob: Annotated[float, Field(..., description="The log probability of this token, if it is within the top 20 most likely tokens. Otherwise, the value `-9999.0` is used to signify that the token is very unlikely.")]
    """The log probability of this token, if it is within the top 20 most likely tokens. Otherwise, the value `-9999.0` is used to signify that the token is very unlikely."""
    bytes: Annotated[Union[List[int], Any], Field(...)]
    top_logprobs: Annotated[List[TopLogprobsItem], Field(..., description="List of the most likely tokens and their log probability, at this token position. In rare cases, there may be fewer than the number of requested `top_logprobs` returned.")]
    """List of the most likely tokens and their log probability, at this token position. In rare cases, there may be fewer than the number of requested `top_logprobs` returned."""

    class Config:
        extra = "ignore"

class ChatCompletionList(BaseModel):
    """An object representing a list of Chat Completions.
"""
    object: Annotated[Literal["list"], Field(default='list', description="The type of this object. It is always set to \"list\". ")]
    """The type of this object. It is always set to \"list\". """
    data: Annotated[List[CreateChatCompletionResponse], Field(..., description="An array of chat completion objects. ")]
    """An array of chat completion objects. """
    first_id: Annotated[str, Field(..., description="The identifier of the first chat completion in the data array.")]
    """The identifier of the first chat completion in the data array."""
    last_id: Annotated[str, Field(..., description="The identifier of the last chat completion in the data array.")]
    """The identifier of the last chat completion in the data array."""
    has_more: Annotated[bool, Field(..., description="Indicates whether there are more Chat Completions available.")]
    """Indicates whether there are more Chat Completions available."""

    class Config:
        extra = "ignore"

ChatCompletionList.model_rebuild()