# Code generated by schema2code at 2026-02-23 18:05:01. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class FunctionParameters(BaseModel):
    """The parameters the functions accepts, described as a JSON Schema object. See the [guide](https://platform.openai.com/docs/guides/function-calling) for examples, and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format. 

Omitting `parameters` defines a function with an empty parameter list."""
    pass

class ChatCompletionFunctions(BaseModel):
    description: Annotated[Optional[str], Field(default=None, description="A description of what the function does, used by the model to choose when and how to call the function.")] = None
    """A description of what the function does, used by the model to choose when and how to call the function."""
    name: Annotated[str, Field(..., description="The name of the function to be called. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64.")]
    """The name of the function to be called. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64."""
    parameters: Annotated[Optional[FunctionParameters], Field(default=None)] = None

    class Config:
        extra = "ignore"

ChatCompletionFunctions.model_rebuild()