# Code generated by schema2code at 2026-02-23 18:05:01. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ChatCompletionRequestAssistantMessage(BaseModel):
    """Messages sent by the model in response to user messages.
"""
    content: Annotated[Optional[Union[Union[str, List[ChatCompletionRequestAssistantMessageContentPart]], Any]], Field(default=None)] = None
    refusal: Annotated[Optional[Union[str, Any]], Field(default=None)] = None
    role: Annotated[Literal["assistant"], Field(..., description="The role of the messages author, in this case `assistant`.")]
    """The role of the messages author, in this case `assistant`."""
    name: Annotated[Optional[str], Field(default=None, description="An optional name for the participant. Provides the model information to differentiate between participants of the same role.")] = None
    """An optional name for the participant. Provides the model information to differentiate between participants of the same role."""
    audio: Annotated[Optional[Union[Audio, Any]], Field(default=None)] = None
    tool_calls: Annotated[Optional[ChatCompletionMessageToolCalls], Field(default=None)] = None
    function_call: Annotated[Optional[Union[FunctionCall, Any]], Field(default=None)] = None

    class Config:
        extra = "ignore"

ChatCompletionRequestAssistantMessageContentPart = Union[ChatCompletionRequestMessageContentPartText, ChatCompletionRequestMessageContentPartRefusal]

class ChatCompletionRequestMessageContentPartRefusal(BaseModel):
    type: Annotated[Literal["refusal"], Field(..., description="The type of the content part.")]
    """The type of the content part."""
    refusal: Annotated[str, Field(..., description="The refusal message generated by the model.")]
    """The refusal message generated by the model."""

    class Config:
        extra = "ignore"

class ChatCompletionRequestMessageContentPartText(BaseModel):
    """Learn about [text inputs](https://platform.openai.com/docs/guides/text-generation).
"""
    type: Annotated[Literal["text"], Field(..., description="The type of the content part.")]
    """The type of the content part."""
    text: Annotated[str, Field(..., description="The text content.")]
    """The text content."""

    class Config:
        extra = "ignore"

class ChatCompletionMessageToolCalls(BaseModel):
    """The tool calls generated by the model, such as function calls."""
    pass

class ChatCompletionMessageCustomToolCall(BaseModel):
    """A call to a custom tool created by the model.
"""
    id: Annotated[str, Field(..., description="The ID of the tool call.")]
    """The ID of the tool call."""
    type: Annotated[Literal["custom"], Field(..., description="The type of the tool. Always `custom`.")]
    """The type of the tool. Always `custom`."""
    custom: Annotated[Custom, Field(..., description="The custom tool that the model called.")]
    """The custom tool that the model called."""

    class Config:
        extra = "ignore"

class ChatCompletionMessageToolCall(BaseModel):
    """A call to a function tool created by the model.
"""
    id: Annotated[str, Field(..., description="The ID of the tool call.")]
    """The ID of the tool call."""
    type: Annotated[Literal["function"], Field(..., description="The type of the tool. Currently, only `function` is supported.")]
    """The type of the tool. Currently, only `function` is supported."""
    function: Annotated[Function, Field(..., description="The function that the model called.")]
    """The function that the model called."""

    class Config:
        extra = "ignore"

class ChatCompletionRequestSystemMessage(BaseModel):
    """Developer-provided instructions that the model should follow, regardless of
messages sent by the user. With o1 models and newer, use `developer` messages
for this purpose instead.
"""
    content: Annotated[Union[str, List[ChatCompletionRequestSystemMessageContentPart]], Field(..., description="The contents of the system message.")]
    """The contents of the system message."""
    role: Annotated[Literal["system"], Field(..., description="The role of the messages author, in this case `system`.")]
    """The role of the messages author, in this case `system`."""
    name: Annotated[Optional[str], Field(default=None, description="An optional name for the participant. Provides the model information to differentiate between participants of the same role.")] = None
    """An optional name for the participant. Provides the model information to differentiate between participants of the same role."""

    class Config:
        extra = "ignore"

ChatCompletionRequestSystemMessageContentPart = Union[ChatCompletionRequestMessageContentPartText]

class ChatCompletionRequestFunctionMessage(BaseModel):
    role: Annotated[Literal["function"], Field(..., description="The role of the messages author, in this case `function`.")]
    """The role of the messages author, in this case `function`."""
    content: Annotated[Union[str, Any], Field(...)]
    name: Annotated[str, Field(..., description="The name of the function to call.")]
    """The name of the function to call."""

    class Config:
        extra = "ignore"

class ChatCompletionRequestUserMessage(BaseModel):
    """Messages sent by an end user, containing prompts or additional context
information.
"""
    content: Annotated[Union[str, List[ChatCompletionRequestUserMessageContentPart]], Field(..., description="The contents of the user message. ")]
    """The contents of the user message. """
    role: Annotated[Literal["user"], Field(..., description="The role of the messages author, in this case `user`.")]
    """The role of the messages author, in this case `user`."""
    name: Annotated[Optional[str], Field(default=None, description="An optional name for the participant. Provides the model information to differentiate between participants of the same role.")] = None
    """An optional name for the participant. Provides the model information to differentiate between participants of the same role."""

    class Config:
        extra = "ignore"

ChatCompletionRequestUserMessageContentPart = Union[ChatCompletionRequestMessageContentPartText, ChatCompletionRequestMessageContentPartImage, ChatCompletionRequestMessageContentPartAudio, ChatCompletionRequestMessageContentPartFile]

class ChatCompletionRequestMessageContentPartFile(BaseModel):
    """Learn about [file inputs](https://platform.openai.com/docs/guides/text) for text generation.
"""
    type: Annotated[Literal["file"], Field(..., description="The type of the content part. Always `file`.")]
    """The type of the content part. Always `file`."""
    file: Annotated[File, Field(...)]

    class Config:
        extra = "ignore"

class ChatCompletionRequestMessageContentPartImage(BaseModel):
    """Learn about [image inputs](https://platform.openai.com/docs/guides/vision).
"""
    type: Annotated[Literal["image_url"], Field(..., description="The type of the content part.")]
    """The type of the content part."""
    image_url: Annotated[ImageUrl, Field(...)]

    class Config:
        extra = "ignore"

class ChatCompletionRequestMessageContentPartAudio(BaseModel):
    """Learn about [audio inputs](https://platform.openai.com/docs/guides/audio).
"""
    type: Annotated[Literal["input_audio"], Field(..., description="The type of the content part. Always `input_audio`.")]
    """The type of the content part. Always `input_audio`."""
    input_audio: Annotated[InputAudio, Field(...)]

    class Config:
        extra = "ignore"

class ChatCompletionRequestToolMessage(BaseModel):
    role: Annotated[Literal["tool"], Field(..., description="The role of the messages author, in this case `tool`.")]
    """The role of the messages author, in this case `tool`."""
    content: Annotated[Union[str, List[ChatCompletionRequestToolMessageContentPart]], Field(..., description="The contents of the tool message.")]
    """The contents of the tool message."""
    tool_call_id: Annotated[str, Field(..., description="Tool call that this message is responding to.")]
    """Tool call that this message is responding to."""

    class Config:
        extra = "ignore"

ChatCompletionRequestToolMessageContentPart = Union[ChatCompletionRequestMessageContentPartText]

class ChatCompletionRequestDeveloperMessage(BaseModel):
    """Developer-provided instructions that the model should follow, regardless of
messages sent by the user. With o1 models and newer, `developer` messages
replace the previous `system` messages.
"""
    content: Annotated[Union[str, List[ChatCompletionRequestMessageContentPartText]], Field(..., description="The contents of the developer message.")]
    """The contents of the developer message."""
    role: Annotated[Literal["developer"], Field(..., description="The role of the messages author, in this case `developer`.")]
    """The role of the messages author, in this case `developer`."""
    name: Annotated[Optional[str], Field(default=None, description="An optional name for the participant. Provides the model information to differentiate between participants of the same role.")] = None
    """An optional name for the participant. Provides the model information to differentiate between participants of the same role."""

    class Config:
        extra = "ignore"

ChatCompletionRequestMessage = Union[ChatCompletionRequestDeveloperMessage, ChatCompletionRequestSystemMessage, ChatCompletionRequestUserMessage, ChatCompletionRequestAssistantMessage, ChatCompletionRequestToolMessage, ChatCompletionRequestFunctionMessage]