# Code generated by schema2code at 2026-02-23 18:05:01. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class RateLimits(BaseModel):
    """Active per-minute request limit for the session."""
    max_requests_per_1_minute: Annotated[int, Field(..., description="Maximum allowed requests per one-minute window.")]
    """Maximum allowed requests per one-minute window."""

    class Config:
        extra = "ignore"