# Code generated by schema2code at 2026-02-23 14:46:39. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class Function(BaseModel):
    name: Annotated[str, Field(..., description="The name of the function to call.")]
    """The name of the function to call."""

    class Config:
        extra = "ignore"

class ChatCompletionNamedToolChoice(BaseModel):
    """Specifies a tool the model should use. Use to force the model to call a specific function."""
    function: Annotated[Function, Field(...)]
    type: Annotated[Literal["function"], Field(..., description="For function calling, the type is always `function`.")]
    """For function calling, the type is always `function`."""

    class Config:
        extra = "ignore"

ChatCompletionNamedToolChoice.model_rebuild()