# Code generated by schema2code at 2026-02-23 18:05:01. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ChatCompletionAllowedTools(BaseModel):
    """Constrains the tools available to the model to a pre-defined set.
"""
    mode: Annotated[Literal["auto", "required"], Field(..., description="Constrains the tools available to the model to a pre-defined set.  `auto` allows the model to pick from among the allowed tools and generate a message.  `required` requires the model to call one or more of the allowed tools. ")]
    """Constrains the tools available to the model to a pre-defined set.  `auto` allows the model to pick from among the allowed tools and generate a message.  `required` requires the model to call one or more of the allowed tools. """
    tools: Annotated[List[Dict[str, Any]], Field(..., description="A list of tool definitions that the model should be allowed to call.  For the Chat Completions API, the list of tool definitions might look like: ```json [   { \"type\": \"function\", \"function\": { \"name\": \"get_weather\" } },   { \"type\": \"function\", \"function\": { \"name\": \"get_time\" } } ] ``` ")]
    """A list of tool definitions that the model should be allowed to call.  For the Chat Completions API, the list of tool definitions might look like: ```json [   { \"type\": \"function\", \"function\": { \"name\": \"get_weather\" } },   { \"type\": \"function\", \"function\": { \"name\": \"get_time\" } } ] ``` """

    class Config:
        extra = "ignore"

class AllowedTools(BaseModel):
    """Constrains the tools available to the model to a pre-defined set.
"""
    type: Annotated[Literal["allowed_tools"], Field(..., description="Allowed tool configuration type. Always `allowed_tools`.")]
    """Allowed tool configuration type. Always `allowed_tools`."""
    allowed_tools: Annotated[ChatCompletionAllowedTools, Field(...)]

    class Config:
        extra = "ignore"

AllowedTools.model_rebuild()