# Code generated by schema2code at 2026-02-23 14:46:40. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .assistant_tools_code import AssistantToolsCode
from .assistant_tools_file_search_type_only import AssistantToolsFileSearchTypeOnly
from .create_message_request import CreateMessageRequest
from .message_content_image_file_object import MessageContentImageFileObject
from .message_content_image_url_object import MessageContentImageUrlObject
from .message_request_content_text_object import MessageRequestContentTextObject
from .metadata import Metadata
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class CodeInterpreter(BaseModel):
    file_ids: Annotated[Optional[List[str]], Field(default_factory=lambda: [], description="A list of [file](https://platform.openai.com/docs/api-reference/files) IDs made available to the `code_interpreter` tool. There can be a maximum of 20 files associated with the tool. ")]
    """A list of [file](https://platform.openai.com/docs/api-reference/files) IDs made available to the `code_interpreter` tool. There can be a maximum of 20 files associated with the tool. """

    class Config:
        extra = "ignore"

class FileSearch(BaseModel):
    vector_store_ids: Annotated[Optional[List[str]], Field(default=None, description="The [vector store](https://platform.openai.com/docs/api-reference/vector-stores/object) attached to this thread. There can be a maximum of 1 vector store attached to the thread. ")] = None
    """The [vector store](https://platform.openai.com/docs/api-reference/vector-stores/object) attached to this thread. There can be a maximum of 1 vector store attached to the thread. """
    vector_stores: Annotated[Optional[List[VectorStoresItem]], Field(default=None, description="A helper to create a [vector store](https://platform.openai.com/docs/api-reference/vector-stores/object) with file_ids and attach it to this thread. There can be a maximum of 1 vector store attached to the thread. ")] = None
    """A helper to create a [vector store](https://platform.openai.com/docs/api-reference/vector-stores/object) with file_ids and attach it to this thread. There can be a maximum of 1 vector store attached to the thread. """

    class Config:
        extra = "ignore"

class ToolResources(BaseModel):
    """A set of resources that are made available to the assistant's tools in this thread. The resources are specific to the type of tool. For example, the `code_interpreter` tool requires a list of file IDs, while the `file_search` tool requires a list of vector store IDs.
"""
    code_interpreter: Annotated[Optional[CodeInterpreter], Field(default=None)] = None
    file_search: Annotated[Optional[FileSearch], Field(default=None)] = None

    class Config:
        extra = "ignore"

class CreateThreadRequest(BaseModel):
    """Options to create a new thread. If no thread is provided when running a
request, an empty thread will be created.
"""
    messages: Annotated[Optional[List[CreateMessageRequest]], Field(default=None, description="A list of [messages](https://platform.openai.com/docs/api-reference/messages) to start the thread with.")] = None
    """A list of [messages](https://platform.openai.com/docs/api-reference/messages) to start the thread with."""
    metadata: Annotated[Optional[Metadata], Field(default=None)] = None
    tool_resources: Annotated[Optional[Union[ToolResources, Any]], Field(default=None)] = None

    class Config:
        extra = "ignore"

CreateThreadRequest.model_rebuild()