# Code generated by schema2code at 2026-02-23 18:05:01. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class CreateGroupBody(BaseModel):
    """Request payload for creating a new group in the organization."""
    name: Annotated[str, Field(..., description="Human readable name for the group.")]
    """Human readable name for the group."""

    class Config:
        extra = "ignore"