# Code generated by schema2code at 2026-02-23 14:46:40. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class CreateVoiceConsentRequest(BaseModel):
    language: Annotated[str, Field(..., description="The BCP 47 language tag for the consent phrase (for example, `en-US`).")]
    """The BCP 47 language tag for the consent phrase (for example, `en-US`)."""
    name: Annotated[str, Field(..., description="The label to use for this consent recording.")]
    """The label to use for this consent recording."""
    recording: Annotated[str, Field(..., description="The consent audio recording file. Maximum size is 10 MiB.  Supported MIME types: `audio/mpeg`, `audio/wav`, `audio/x-wav`, `audio/ogg`, `audio/aac`, `audio/flac`, `audio/webm`, `audio/mp4`. ")]
    """The consent audio recording file. Maximum size is 10 MiB.  Supported MIME types: `audio/mpeg`, `audio/wav`, `audio/x-wav`, `audio/ogg`, `audio/aac`, `audio/flac`, `audio/webm`, `audio/mp4`. """

    class Config:
        extra = "ignore"