# Code generated by schema2code at 2026-02-23 18:05:01. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class CreateFineTuningCheckpointPermissionRequest(BaseModel):
    project_ids: Annotated[List[str], Field(..., description="The project identifiers to grant access to.")]
    """The project identifiers to grant access to."""

    class Config:
        extra = "ignore"