# Code generated by schema2code at 2026-02-23 14:46:40. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class Categories(BaseModel):
    """A list of the categories, and whether they are flagged or not."""
    harassment: Annotated[bool, Field(..., description="Content that expresses, incites, or promotes harassing language towards any target.")]
    """Content that expresses, incites, or promotes harassing language towards any target."""
    harassment/threatening: Annotated[bool, Field(..., description="Harassment content that also includes violence or serious harm towards any target.")]
    """Harassment content that also includes violence or serious harm towards any target."""
    hate: Annotated[bool, Field(..., description="Content that expresses, incites, or promotes hate based on race, gender, ethnicity, religion, nationality, sexual orientation, disability status, or caste. Hateful content aimed at non-protected groups (e.g., chess players) is harassment.")]
    """Content that expresses, incites, or promotes hate based on race, gender, ethnicity, religion, nationality, sexual orientation, disability status, or caste. Hateful content aimed at non-protected groups (e.g., chess players) is harassment."""
    hate/threatening: Annotated[bool, Field(..., description="Hateful content that also includes violence or serious harm towards the targeted group based on race, gender, ethnicity, religion, nationality, sexual orientation, disability status, or caste.")]
    """Hateful content that also includes violence or serious harm towards the targeted group based on race, gender, ethnicity, religion, nationality, sexual orientation, disability status, or caste."""
    illicit: Annotated[Union[bool, Any], Field(...)]
    illicit/violent: Annotated[Union[bool, Any], Field(...)]
    self_harm: Annotated[bool, Field(..., description="Content that promotes, encourages, or depicts acts of self-harm, such as suicide, cutting, and eating disorders.", alias='self-harm')]
    """Content that promotes, encourages, or depicts acts of self-harm, such as suicide, cutting, and eating disorders."""
    self_harm/instructions: Annotated[bool, Field(..., description="Content that encourages performing acts of self-harm, such as suicide, cutting, and eating disorders, or that gives instructions or advice on how to commit such acts.", alias='self-harm/instructions')]
    """Content that encourages performing acts of self-harm, such as suicide, cutting, and eating disorders, or that gives instructions or advice on how to commit such acts."""
    self_harm/intent: Annotated[bool, Field(..., description="Content where the speaker expresses that they are engaging or intend to engage in acts of self-harm, such as suicide, cutting, and eating disorders.", alias='self-harm/intent')]
    """Content where the speaker expresses that they are engaging or intend to engage in acts of self-harm, such as suicide, cutting, and eating disorders."""
    sexual: Annotated[bool, Field(..., description="Content meant to arouse sexual excitement, such as the description of sexual activity, or that promotes sexual services (excluding sex education and wellness).")]
    """Content meant to arouse sexual excitement, such as the description of sexual activity, or that promotes sexual services (excluding sex education and wellness)."""
    sexual/minors: Annotated[bool, Field(..., description="Sexual content that includes an individual who is under 18 years old.")]
    """Sexual content that includes an individual who is under 18 years old."""
    violence: Annotated[bool, Field(..., description="Content that depicts death, violence, or physical injury.")]
    """Content that depicts death, violence, or physical injury."""
    violence/graphic: Annotated[bool, Field(..., description="Content that depicts death, violence, or physical injury in graphic detail.")]
    """Content that depicts death, violence, or physical injury in graphic detail."""

    class Config:
        extra = "ignore"

class CategoryAppliedInputTypes(BaseModel):
    """A list of the categories along with the input type(s) that the score applies to."""
    harassment: Annotated[List[Literal["text"]], Field(..., description="The applied input type(s) for the category 'harassment'.")]
    """The applied input type(s) for the category 'harassment'."""
    harassment/threatening: Annotated[List[Literal["text"]], Field(..., description="The applied input type(s) for the category 'harassment/threatening'.")]
    """The applied input type(s) for the category 'harassment/threatening'."""
    hate: Annotated[List[Literal["text"]], Field(..., description="The applied input type(s) for the category 'hate'.")]
    """The applied input type(s) for the category 'hate'."""
    hate/threatening: Annotated[List[Literal["text"]], Field(..., description="The applied input type(s) for the category 'hate/threatening'.")]
    """The applied input type(s) for the category 'hate/threatening'."""
    illicit: Annotated[List[Literal["text"]], Field(..., description="The applied input type(s) for the category 'illicit'.")]
    """The applied input type(s) for the category 'illicit'."""
    illicit/violent: Annotated[List[Literal["text"]], Field(..., description="The applied input type(s) for the category 'illicit/violent'.")]
    """The applied input type(s) for the category 'illicit/violent'."""
    self_harm: Annotated[List[Literal["text", "image"]], Field(..., description="The applied input type(s) for the category 'self-harm'.", alias='self-harm')]
    """The applied input type(s) for the category 'self-harm'."""
    self_harm/instructions: Annotated[List[Literal["text", "image"]], Field(..., description="The applied input type(s) for the category 'self-harm/instructions'.", alias='self-harm/instructions')]
    """The applied input type(s) for the category 'self-harm/instructions'."""
    self_harm/intent: Annotated[List[Literal["text", "image"]], Field(..., description="The applied input type(s) for the category 'self-harm/intent'.", alias='self-harm/intent')]
    """The applied input type(s) for the category 'self-harm/intent'."""
    sexual: Annotated[List[Literal["text", "image"]], Field(..., description="The applied input type(s) for the category 'sexual'.")]
    """The applied input type(s) for the category 'sexual'."""
    sexual/minors: Annotated[List[Literal["text"]], Field(..., description="The applied input type(s) for the category 'sexual/minors'.")]
    """The applied input type(s) for the category 'sexual/minors'."""
    violence: Annotated[List[Literal["text", "image"]], Field(..., description="The applied input type(s) for the category 'violence'.")]
    """The applied input type(s) for the category 'violence'."""
    violence/graphic: Annotated[List[Literal["text", "image"]], Field(..., description="The applied input type(s) for the category 'violence/graphic'.")]
    """The applied input type(s) for the category 'violence/graphic'."""

    class Config:
        extra = "ignore"

class CategoryScores(BaseModel):
    """A list of the categories along with their scores as predicted by model."""
    harassment: Annotated[float, Field(..., description="The score for the category 'harassment'.")]
    """The score for the category 'harassment'."""
    harassment/threatening: Annotated[float, Field(..., description="The score for the category 'harassment/threatening'.")]
    """The score for the category 'harassment/threatening'."""
    hate: Annotated[float, Field(..., description="The score for the category 'hate'.")]
    """The score for the category 'hate'."""
    hate/threatening: Annotated[float, Field(..., description="The score for the category 'hate/threatening'.")]
    """The score for the category 'hate/threatening'."""
    illicit: Annotated[float, Field(..., description="The score for the category 'illicit'.")]
    """The score for the category 'illicit'."""
    illicit/violent: Annotated[float, Field(..., description="The score for the category 'illicit/violent'.")]
    """The score for the category 'illicit/violent'."""
    self_harm: Annotated[float, Field(..., description="The score for the category 'self-harm'.", alias='self-harm')]
    """The score for the category 'self-harm'."""
    self_harm/instructions: Annotated[float, Field(..., description="The score for the category 'self-harm/instructions'.", alias='self-harm/instructions')]
    """The score for the category 'self-harm/instructions'."""
    self_harm/intent: Annotated[float, Field(..., description="The score for the category 'self-harm/intent'.", alias='self-harm/intent')]
    """The score for the category 'self-harm/intent'."""
    sexual: Annotated[float, Field(..., description="The score for the category 'sexual'.")]
    """The score for the category 'sexual'."""
    sexual/minors: Annotated[float, Field(..., description="The score for the category 'sexual/minors'.")]
    """The score for the category 'sexual/minors'."""
    violence: Annotated[float, Field(..., description="The score for the category 'violence'.")]
    """The score for the category 'violence'."""
    violence/graphic: Annotated[float, Field(..., description="The score for the category 'violence/graphic'.")]
    """The score for the category 'violence/graphic'."""

    class Config:
        extra = "ignore"

class ResultsItem(BaseModel):
    categories: Annotated[Categories, Field(..., description="A list of the categories, and whether they are flagged or not.")]
    """A list of the categories, and whether they are flagged or not."""
    category_applied_input_types: Annotated[CategoryAppliedInputTypes, Field(..., description="A list of the categories along with the input type(s) that the score applies to.")]
    """A list of the categories along with the input type(s) that the score applies to."""
    category_scores: Annotated[CategoryScores, Field(..., description="A list of the categories along with their scores as predicted by model.")]
    """A list of the categories along with their scores as predicted by model."""
    flagged: Annotated[bool, Field(..., description="Whether any of the below categories are flagged.")]
    """Whether any of the below categories are flagged."""

    class Config:
        extra = "ignore"

class CreateModerationResponse(BaseModel):
    """Represents if a given text input is potentially harmful."""
    id: Annotated[str, Field(..., description="The unique identifier for the moderation request.")]
    """The unique identifier for the moderation request."""
    model: Annotated[str, Field(..., description="The model used to generate the moderation results.")]
    """The model used to generate the moderation results."""
    results: Annotated[List[ResultsItem], Field(..., description="A list of moderation objects.")]
    """A list of moderation objects."""

    class Config:
        extra = "ignore"

CreateModerationResponse.model_rebuild()