# Code generated by schema2code at 2026-02-23 18:05:01. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class CreateVoiceRequest(BaseModel):
    name: Annotated[str, Field(..., description="The name of the new voice.")]
    """The name of the new voice."""
    audio_sample: Annotated[str, Field(..., description="The sample audio recording file. Maximum size is 10 MiB.  Supported MIME types: `audio/mpeg`, `audio/wav`, `audio/x-wav`, `audio/ogg`, `audio/aac`, `audio/flac`, `audio/webm`, `audio/mp4`. ")]
    """The sample audio recording file. Maximum size is 10 MiB.  Supported MIME types: `audio/mpeg`, `audio/wav`, `audio/x-wav`, `audio/ogg`, `audio/aac`, `audio/flac`, `audio/webm`, `audio/mp4`. """
    consent: Annotated[str, Field(..., description="The consent recording ID (for example, `cons_1234`).")]
    """The consent recording ID (for example, `cons_1234`)."""

    class Config:
        extra = "ignore"