# Code generated by schema2code at 2026-02-23 14:46:58. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class CustomToolCall(BaseModel):
    """A call to a custom tool created by the model.
"""
    call_id: Annotated[str, Field(..., description="An identifier used to map this custom tool call to a tool call output. ")]
    """An identifier used to map this custom tool call to a tool call output. """
    id: Annotated[Optional[str], Field(default=None, description="The unique ID of the custom tool call in the OpenAI platform. ")] = None
    """The unique ID of the custom tool call in the OpenAI platform. """
    input: Annotated[str, Field(..., description="The input for the custom tool call generated by the model. ")]
    """The input for the custom tool call generated by the model. """
    name: Annotated[str, Field(..., description="The name of the custom tool being called. ")]
    """The name of the custom tool being called. """
    type: Annotated[Literal["custom_tool_call"], Field(..., description="The type of the custom tool call. Always `custom_tool_call`. ")]
    """The type of the custom tool call. Always `custom_tool_call`. """

    class Config:
        extra = "ignore"