# Code generated by schema2code at 2026-02-23 18:05:01. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class Custom(BaseModel):
    """Properties of the custom tool.
"""
    name: Annotated[str, Field(..., description="The name of the custom tool, used to identify it in tool calls.")]
    """The name of the custom tool, used to identify it in tool calls."""
    description: Annotated[Optional[str], Field(default=None, description="Optional description of the custom tool, used to provide more context. ")] = None
    """Optional description of the custom tool, used to provide more context. """
    format: Annotated[Optional[Union[TextFormat, GrammarFormat]], Field(default=None, description="The input format for the custom tool. Default is unconstrained text. ")] = None
    """The input format for the custom tool. Default is unconstrained text. """

    class Config:
        extra = "ignore"

class TextFormat(BaseModel):
    """Unconstrained free-form text."""
    type: Annotated[Literal["text"], Field(..., description="Unconstrained text format. Always `text`.")]
    """Unconstrained text format. Always `text`."""

    class Config:
        extra = "ignore"

class Grammar(BaseModel):
    """Your chosen grammar."""
    definition: Annotated[str, Field(..., description="The grammar definition.")]
    """The grammar definition."""
    syntax: Annotated[Literal["lark", "regex"], Field(..., description="The syntax of the grammar definition. One of `lark` or `regex`.")]
    """The syntax of the grammar definition. One of `lark` or `regex`."""

    class Config:
        extra = "ignore"

class GrammarFormat(BaseModel):
    """A grammar defined by the user."""
    type: Annotated[Literal["grammar"], Field(..., description="Grammar format. Always `grammar`.")]
    """Grammar format. Always `grammar`."""
    grammar: Annotated[Grammar, Field(..., description="Your chosen grammar.")]
    """Your chosen grammar."""

    class Config:
        extra = "ignore"

class CustomTool(BaseModel):
    """A custom tool that processes input using a specified format.
"""
    type: Annotated[Literal["custom"], Field(..., description="The type of the custom tool. Always `custom`.")]
    """The type of the custom tool. Always `custom`."""
    custom: Annotated[Custom, Field(..., description="Properties of the custom tool. ")]
    """Properties of the custom tool. """

    class Config:
        extra = "ignore"

CustomTool.model_rebuild()