# Code generated by schema2code at 2026-02-23 18:05:01. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class DeletedRoleAssignmentResource(BaseModel):
    """Confirmation payload returned after unassigning a role."""
    object: Annotated[str, Field(..., description="Identifier for the deleted assignment, such as `group.role.deleted` or `user.role.deleted`.")]
    """Identifier for the deleted assignment, such as `group.role.deleted` or `user.role.deleted`."""
    deleted: Annotated[bool, Field(..., description="Whether the assignment was removed.")]
    """Whether the assignment was removed."""

    class Config:
        extra = "ignore"