# Code generated by schema2code at 2026-02-23 18:05:01. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class FileSearchRanker(str, Enum):
    """The ranker to use for the file search. If not specified will use the `auto` ranker."""
    AUTO = 'auto'
    DEFAULT_2024_08_21 = 'default_2024_08_21'

class FileSearchToolCallRankingOptions(BaseModel):
    """The ranking options for the file search. If not specified, the file search tool will use the `auto` ranker and a score_threshold of 0.

See the [file search tool documentation](https://platform.openai.com/docs/assistants/tools/file-search#customizing-file-search-settings) for more information.
"""
    ranker: Annotated[Optional[FileSearchRanker], Field(default=None)] = None
    score_threshold: Annotated[float, Field(..., description="The score threshold for the file search. All values must be a floating point number between 0 and 1.", ge=0, le=1)]
    """The score threshold for the file search. All values must be a floating point number between 0 and 1."""

    class Config:
        extra = "ignore"

FileSearchToolCallRankingOptions.model_rebuild()