# Code generated by schema2code at 2026-02-23 18:05:01. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class FileCitation(BaseModel):
    """A citation to a file."""
    type: Annotated[Literal["file_citation"], Field(default='file_citation', description="The type of the file citation. Always `file_citation`.")]
    """The type of the file citation. Always `file_citation`."""
    file_id: Annotated[str, Field(..., description="The ID of the file.")]
    """The ID of the file."""
    index: Annotated[int, Field(..., description="The index of the file in the list of files.")]
    """The index of the file in the list of files."""
    filename: Annotated[str, Field(..., description="The filename of the file cited.")]
    """The filename of the file cited."""

    class Config:
        extra = "ignore"