# Code generated by schema2code at 2026-02-23 14:46:42. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class FileUploadParam(BaseModel):
    """Controls whether users can upload files."""
    enabled: Annotated[Optional[bool], Field(default=None, description="Enable uploads for this session. Defaults to false.")] = None
    """Enable uploads for this session. Defaults to false."""
    max_file_size: Annotated[Optional[int], Field(default=None, description="Maximum size in megabytes for each uploaded file. Defaults to 512 MB, which is the maximum allowable size.", ge=1, le=512)] = None
    """Maximum size in megabytes for each uploaded file. Defaults to 512 MB, which is the maximum allowable size."""
    max_files: Annotated[Optional[int], Field(default=None, description="Maximum number of files that can be uploaded to the session. Defaults to 10.", ge=1)] = None
    """Maximum number of files that can be uploaded to the session. Defaults to 10."""

    class Config:
        extra = "ignore"