# Code generated by schema2code at 2026-02-23 18:05:01. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class FineTuneDPOMethod(BaseModel):
    """Configuration for the DPO fine-tuning method."""
    hyperparameters: Annotated[Optional[FineTuneDPOHyperparameters], Field(default=None)] = None

    class Config:
        extra = "ignore"

class FineTuneDPOHyperparameters(BaseModel):
    """The hyperparameters used for the DPO fine-tuning job."""
    beta: Annotated[Optional[Union[Literal["auto"], float]], Field(default=None, description="The beta value for the DPO method. A higher beta value will increase the weight of the penalty between the policy and reference model. ")] = None
    """The beta value for the DPO method. A higher beta value will increase the weight of the penalty between the policy and reference model. """
    batch_size: Annotated[Optional[Union[Literal["auto"], int]], Field(default='auto', description="Number of examples in each batch. A larger batch size means that model parameters are updated less frequently, but with lower variance. ")] = 'auto'
    """Number of examples in each batch. A larger batch size means that model parameters are updated less frequently, but with lower variance. """
    learning_rate_multiplier: Annotated[Optional[Union[Literal["auto"], float]], Field(default=None, description="Scaling factor for the learning rate. A smaller learning rate may be useful to avoid overfitting. ")] = None
    """Scaling factor for the learning rate. A smaller learning rate may be useful to avoid overfitting. """
    n_epochs: Annotated[Optional[Union[Literal["auto"], int]], Field(default='auto', description="The number of epochs to train the model for. An epoch refers to one full cycle through the training dataset. ")] = 'auto'
    """The number of epochs to train the model for. An epoch refers to one full cycle through the training dataset. """

    class Config:
        extra = "ignore"

class FineTuneReinforcementMethod(BaseModel):
    """Configuration for the reinforcement fine-tuning method."""
    grader: Annotated[Union[GraderStringCheck, GraderTextSimilarity, GraderPython, GraderScoreModel, GraderMulti], Field(..., description="The grader used for the fine-tuning job.")]
    """The grader used for the fine-tuning job."""
    hyperparameters: Annotated[Optional[FineTuneReinforcementHyperparameters], Field(default=None)] = None

    class Config:
        extra = "ignore"

class GraderMulti(BaseModel):
    """A MultiGrader object combines the output of multiple graders to produce a single score."""
    type: Annotated[Literal["multi"], Field(default='multi', description="The object type, which is always `multi`.")]
    """The object type, which is always `multi`."""
    name: Annotated[str, Field(..., description="The name of the grader.")]
    """The name of the grader."""
    graders: Annotated[Union[GraderStringCheck, GraderTextSimilarity, GraderPython, GraderScoreModel, GraderLabelModel], Field(...)]
    calculate_output: Annotated[str, Field(..., description="A formula to calculate the output based on grader results.")]
    """A formula to calculate the output based on grader results."""

    class Config:
        extra = "ignore"

class GraderLabelModel(BaseModel):
    """A LabelModelGrader object which uses a model to assign labels to each item
in the evaluation.
"""
    type: Annotated[Literal["label_model"], Field(..., description="The object type, which is always `label_model`.")]
    """The object type, which is always `label_model`."""
    name: Annotated[str, Field(..., description="The name of the grader.")]
    """The name of the grader."""
    model: Annotated[str, Field(..., description="The model to use for the evaluation. Must support structured outputs.")]
    """The model to use for the evaluation. Must support structured outputs."""
    input: Annotated[List[EvalItem], Field(...)]
    labels: Annotated[List[str], Field(..., description="The labels to assign to each item in the evaluation.")]
    """The labels to assign to each item in the evaluation."""
    passing_labels: Annotated[List[str], Field(..., description="The labels that indicate a passing result. Must be a subset of labels.")]
    """The labels that indicate a passing result. Must be a subset of labels."""

    class Config:
        extra = "ignore"

class EvalItem(BaseModel):
    """A message input to the model with a role indicating instruction following
hierarchy. Instructions given with the `developer` or `system` role take
precedence over instructions given with the `user` role. Messages with the
`assistant` role are presumed to have been generated by the model in previous
interactions.
"""
    role: Annotated[Literal["user", "assistant", "system", "developer"], Field(..., description="The role of the message input. One of `user`, `assistant`, `system`, or `developer`. ")]
    """The role of the message input. One of `user`, `assistant`, `system`, or `developer`. """
    content: Annotated[EvalItemContent, Field(...)]
    type: Annotated[Optional[Literal["message"]], Field(default=None, description="The type of the message input. Always `message`. ")] = None
    """The type of the message input. Always `message`. """

    class Config:
        extra = "ignore"

EvalItemContent = Union[EvalItemContentItem, EvalItemContentArray]

class EvalItemContentArray(BaseModel):
    """A list of inputs, each of which may be either an input text, output text, input
image, or input audio object.
"""
    pass

EvalItemContentItem = Union[EvalItemContentText, InputTextContent, EvalItemContentOutputText, EvalItemInputImage, InputAudio]

class InputTextContent(BaseModel):
    """A text input to the model."""
    type: Annotated[Literal["input_text"], Field(default='input_text', description="The type of the input item. Always `input_text`.")]
    """The type of the input item. Always `input_text`."""
    text: Annotated[str, Field(..., description="The text input to the model.")]
    """The text input to the model."""

    class Config:
        extra = "ignore"

class EvalItemInputImage(BaseModel):
    """An image input block used within EvalItem content arrays."""
    type: Annotated[Literal["input_image"], Field(..., description="The type of the image input. Always `input_image`. ")]
    """The type of the image input. Always `input_image`. """
    image_url: Annotated[str, Field(..., description="The URL of the image input. ")]
    """The URL of the image input. """
    detail: Annotated[Optional[str], Field(default=None, description="The detail level of the image to be sent to the model. One of `high`, `low`, or `auto`. Defaults to `auto`. ")] = None
    """The detail level of the image to be sent to the model. One of `high`, `low`, or `auto`. Defaults to `auto`. """

    class Config:
        extra = "ignore"

class InputAudio(BaseModel):
    """An audio input to the model.
"""
    type: Annotated[Literal["input_audio"], Field(..., description="The type of the input item. Always `input_audio`. ")]
    """The type of the input item. Always `input_audio`. """
    input_audio: Annotated[InputAudio, Field(...)]

    class Config:
        extra = "ignore"

class EvalItemContentOutputText(BaseModel):
    """A text output from the model.
"""
    type: Annotated[Literal["output_text"], Field(..., description="The type of the output text. Always `output_text`. ")]
    """The type of the output text. Always `output_text`. """
    text: Annotated[str, Field(..., description="The text output from the model. ")]
    """The text output from the model. """

    class Config:
        extra = "ignore"

class EvalItemContentText(BaseModel):
    """A text input to the model.
"""
    pass

class GraderTextSimilarity(BaseModel):
    """A TextSimilarityGrader object which grades text based on similarity metrics.
"""
    type: Annotated[Literal["text_similarity"], Field(default='text_similarity', description="The type of grader.")]
    """The type of grader."""
    name: Annotated[str, Field(..., description="The name of the grader.")]
    """The name of the grader."""
    input: Annotated[str, Field(..., description="The text being graded.")]
    """The text being graded."""
    reference: Annotated[str, Field(..., description="The text being graded against.")]
    """The text being graded against."""
    evaluation_metric: Annotated[Literal["cosine", "fuzzy_match", "bleu", "gleu", "meteor", "rouge_1", "rouge_2", "rouge_3", "rouge_4", "rouge_5", "rouge_l"], Field(..., description="The evaluation metric to use. One of `cosine`, `fuzzy_match`, `bleu`,  `gleu`, `meteor`, `rouge_1`, `rouge_2`, `rouge_3`, `rouge_4`, `rouge_5`,  or `rouge_l`. ")]
    """The evaluation metric to use. One of `cosine`, `fuzzy_match`, `bleu`,  `gleu`, `meteor`, `rouge_1`, `rouge_2`, `rouge_3`, `rouge_4`, `rouge_5`,  or `rouge_l`. """

    class Config:
        extra = "ignore"

class GraderScoreModel(BaseModel):
    """A ScoreModelGrader object that uses a model to assign a score to the input.
"""
    type: Annotated[Literal["score_model"], Field(..., description="The object type, which is always `score_model`.")]
    """The object type, which is always `score_model`."""
    name: Annotated[str, Field(..., description="The name of the grader.")]
    """The name of the grader."""
    model: Annotated[str, Field(..., description="The model to use for the evaluation.")]
    """The model to use for the evaluation."""
    sampling_params: Annotated[Optional[SamplingParams], Field(default=None, description="The sampling parameters for the model.")] = None
    """The sampling parameters for the model."""
    input: Annotated[List[EvalItem], Field(..., description="The input messages evaluated by the grader. Supports text, output text, input image, and input audio content blocks, and may include template strings. ")]
    """The input messages evaluated by the grader. Supports text, output text, input image, and input audio content blocks, and may include template strings. """
    range: Annotated[Optional[List[float]], Field(default=None, description="The range of the score. Defaults to `[0, 1]`.")] = None
    """The range of the score. Defaults to `[0, 1]`."""

    class Config:
        extra = "ignore"

ReasoningEffort = Union[Literal["none", "minimal", "low", "medium", "high", "xhigh"]]

class GraderStringCheck(BaseModel):
    """A StringCheckGrader object that performs a string comparison between input and reference using a specified operation.
"""
    type: Annotated[Literal["string_check"], Field(..., description="The object type, which is always `string_check`.")]
    """The object type, which is always `string_check`."""
    name: Annotated[str, Field(..., description="The name of the grader.")]
    """The name of the grader."""
    input: Annotated[str, Field(..., description="The input text. This may include template strings.")]
    """The input text. This may include template strings."""
    reference: Annotated[str, Field(..., description="The reference text. This may include template strings.")]
    """The reference text. This may include template strings."""
    operation: Annotated[Literal["eq", "ne", "like", "ilike"], Field(..., description="The string check operation to perform. One of `eq`, `ne`, `like`, or `ilike`.")]
    """The string check operation to perform. One of `eq`, `ne`, `like`, or `ilike`."""

    class Config:
        extra = "ignore"

class FineTuneReinforcementHyperparameters(BaseModel):
    """The hyperparameters used for the reinforcement fine-tuning job."""
    batch_size: Annotated[Optional[Union[Literal["auto"], int]], Field(default='auto', description="Number of examples in each batch. A larger batch size means that model parameters are updated less frequently, but with lower variance. ")] = 'auto'
    """Number of examples in each batch. A larger batch size means that model parameters are updated less frequently, but with lower variance. """
    learning_rate_multiplier: Annotated[Optional[Union[Literal["auto"], float]], Field(default=None, description="Scaling factor for the learning rate. A smaller learning rate may be useful to avoid overfitting. ")] = None
    """Scaling factor for the learning rate. A smaller learning rate may be useful to avoid overfitting. """
    n_epochs: Annotated[Optional[Union[Literal["auto"], int]], Field(default='auto', description="The number of epochs to train the model for. An epoch refers to one full cycle through the training dataset. ")] = 'auto'
    """The number of epochs to train the model for. An epoch refers to one full cycle through the training dataset. """
    reasoning_effort: Annotated[Optional[Literal["default", "low", "medium", "high"]], Field(default='default', description="Level of reasoning effort. ")] = 'default'
    """Level of reasoning effort. """
    compute_multiplier: Annotated[Optional[Union[Literal["auto"], float]], Field(default=None, description="Multiplier on amount of compute used for exploring search space during training. ")] = None
    """Multiplier on amount of compute used for exploring search space during training. """
    eval_interval: Annotated[Optional[Union[Literal["auto"], int]], Field(default='auto', description="The number of training steps between evaluation runs. ")] = 'auto'
    """The number of training steps between evaluation runs. """
    eval_samples: Annotated[Optional[Union[Literal["auto"], int]], Field(default='auto', description="Number of evaluation samples to generate per training step. ")] = 'auto'
    """Number of evaluation samples to generate per training step. """

    class Config:
        extra = "ignore"

class GraderPython(BaseModel):
    """A PythonGrader object that runs a python script on the input.
"""
    type: Annotated[Literal["python"], Field(..., description="The object type, which is always `python`.")]
    """The object type, which is always `python`."""
    name: Annotated[str, Field(..., description="The name of the grader.")]
    """The name of the grader."""
    source: Annotated[str, Field(..., description="The source code of the python script.")]
    """The source code of the python script."""
    image_tag: Annotated[Optional[str], Field(default=None, description="The image tag to use for the python script.")] = None
    """The image tag to use for the python script."""

    class Config:
        extra = "ignore"

class FineTuneSupervisedMethod(BaseModel):
    """Configuration for the supervised fine-tuning method."""
    hyperparameters: Annotated[Optional[FineTuneSupervisedHyperparameters], Field(default=None)] = None

    class Config:
        extra = "ignore"

class FineTuneSupervisedHyperparameters(BaseModel):
    """The hyperparameters used for the fine-tuning job."""
    batch_size: Annotated[Optional[Union[Literal["auto"], int]], Field(default='auto', description="Number of examples in each batch. A larger batch size means that model parameters are updated less frequently, but with lower variance. ")] = 'auto'
    """Number of examples in each batch. A larger batch size means that model parameters are updated less frequently, but with lower variance. """
    learning_rate_multiplier: Annotated[Optional[Union[Literal["auto"], float]], Field(default=None, description="Scaling factor for the learning rate. A smaller learning rate may be useful to avoid overfitting. ")] = None
    """Scaling factor for the learning rate. A smaller learning rate may be useful to avoid overfitting. """
    n_epochs: Annotated[Optional[Union[Literal["auto"], int]], Field(default='auto', description="The number of epochs to train the model for. An epoch refers to one full cycle through the training dataset. ")] = 'auto'
    """The number of epochs to train the model for. An epoch refers to one full cycle through the training dataset. """

    class Config:
        extra = "ignore"

class FineTuneMethod(BaseModel):
    """The method used for fine-tuning."""
    type: Annotated[Literal["supervised", "dpo", "reinforcement"], Field(..., description="The type of method. Is either `supervised`, `dpo`, or `reinforcement`.")]
    """The type of method. Is either `supervised`, `dpo`, or `reinforcement`."""
    supervised: Annotated[Optional[FineTuneSupervisedMethod], Field(default=None)] = None
    dpo: Annotated[Optional[FineTuneDPOMethod], Field(default=None)] = None
    reinforcement: Annotated[Optional[FineTuneReinforcementMethod], Field(default=None)] = None

    class Config:
        extra = "ignore"

FineTuneMethod.model_rebuild()