# Code generated by schema2code at 2026-02-23 18:05:01. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class FunctionToolCallOutput(BaseModel):
    """The output of a function tool call.
"""
    id: Annotated[Optional[str], Field(default=None, description="The unique ID of the function tool call output. Populated when this item is returned via API. ")] = None
    """The unique ID of the function tool call output. Populated when this item is returned via API. """
    type: Annotated[Literal["function_call_output"], Field(..., description="The type of the function tool call output. Always `function_call_output`. ")]
    """The type of the function tool call output. Always `function_call_output`. """
    call_id: Annotated[str, Field(..., description="The unique ID of the function tool call generated by the model. ")]
    """The unique ID of the function tool call generated by the model. """
    output: Annotated[Union[str, List[FunctionAndCustomToolCallOutput]], Field(..., description="The output from the function call generated by your code. Can be a string or an list of output content. ")]
    """The output from the function call generated by your code. Can be a string or an list of output content. """
    status: Annotated[Optional[Literal["in_progress", "completed", "incomplete"]], Field(default=None, description="The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API. ")] = None
    """The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API. """

    class Config:
        extra = "ignore"

FunctionAndCustomToolCallOutput = Union[InputTextContent, InputImageContent, InputFileContent]

class InputImageContent(BaseModel):
    """An image input to the model. Learn about [image inputs](https://platform.openai.com/docs/guides/vision)."""
    type: Annotated[Literal["input_image"], Field(default='input_image', description="The type of the input item. Always `input_image`.")]
    """The type of the input item. Always `input_image`."""
    image_url: Annotated[Optional[Union[str, Any]], Field(default=None)] = None
    file_id: Annotated[Optional[Union[str, Any]], Field(default=None)] = None
    detail: Annotated[ImageDetail, Field(..., description="The detail level of the image to be sent to the model. One of `high`, `low`, or `auto`. Defaults to `auto`.")]
    """The detail level of the image to be sent to the model. One of `high`, `low`, or `auto`. Defaults to `auto`."""

    class Config:
        extra = "ignore"

class ImageDetail(str, Enum):
    LOW = 'low'
    HIGH = 'high'
    AUTO = 'auto'

class InputFileContent(BaseModel):
    """A file input to the model."""
    type: Annotated[Literal["input_file"], Field(default='input_file', description="The type of the input item. Always `input_file`.")]
    """The type of the input item. Always `input_file`."""
    file_id: Annotated[Optional[Union[str, Any]], Field(default=None)] = None
    filename: Annotated[Optional[str], Field(default=None, description="The name of the file to be sent to the model.")] = None
    """The name of the file to be sent to the model."""
    file_url: Annotated[Optional[str], Field(default=None, description="The URL of the file to be sent to the model.")] = None
    """The URL of the file to be sent to the model."""
    file_data: Annotated[Optional[str], Field(default=None, description="The content of the file to be sent to the model. ")] = None
    """The content of the file to be sent to the model. """

    class Config:
        extra = "ignore"

class InputTextContent(BaseModel):
    """A text input to the model."""
    type: Annotated[Literal["input_text"], Field(default='input_text', description="The type of the input item. Always `input_text`.")]
    """The type of the input item. Always `input_text`."""
    text: Annotated[str, Field(..., description="The text input to the model.")]
    """The text input to the model."""

    class Config:
        extra = "ignore"

class FunctionToolCallOutputResource(BaseModel):
    id: Annotated[str, Field(..., description="The unique ID of the function call tool output. ")]
    """The unique ID of the function call tool output. """
    type: Annotated[Literal["function_call_output"], Field(..., description="The type of the function tool call output. Always `function_call_output`. ")]
    """The type of the function tool call output. Always `function_call_output`. """
    call_id: Annotated[str, Field(..., description="The unique ID of the function tool call generated by the model. ")]
    """The unique ID of the function tool call generated by the model. """
    output: Annotated[Union[str, List[FunctionAndCustomToolCallOutput]], Field(..., description="The output from the function call generated by your code. Can be a string or an list of output content. ")]
    """The output from the function call generated by your code. Can be a string or an list of output content. """
    status: Annotated[Optional[Literal["in_progress", "completed", "incomplete"]], Field(default=None, description="The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API. ")] = None
    """The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API. """

    class Config:
        extra = "ignore"

FunctionToolCallOutputResource.model_rebuild()