# Code generated by schema2code at 2026-02-23 14:46:57. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class FunctionShellCallOutputExitOutcome(BaseModel):
    """Indicates that the shell commands finished and returned an exit code."""
    exit_code: Annotated[int, Field(..., description="Exit code from the shell process.")]
    """Exit code from the shell process."""
    type: Annotated[Literal["exit"], Field(default='exit', description="The outcome type. Always `exit`.")]
    """The outcome type. Always `exit`."""

    class Config:
        extra = "ignore"