# Code generated by schema2code at 2026-02-23 18:05:01. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ImageDetail(str, Enum):
    LOW = 'low'
    HIGH = 'high'
    AUTO = 'auto'

class InputImage(BaseModel):
    """An image input to the model. Learn about [image inputs](https://platform.openai.com/docs/guides/vision)."""
    type: Annotated[Literal["input_image"], Field(default='input_image', description="The type of the input item. Always `input_image`.")]
    """The type of the input item. Always `input_image`."""
    image_url: Annotated[Optional[Union[str, Any]], Field(default=None)] = None
    file_id: Annotated[Optional[Union[str, Any]], Field(default=None)] = None
    detail: Annotated[ImageDetail, Field(..., description="The detail level of the image to be sent to the model. One of `high`, `low`, or `auto`. Defaults to `auto`.")]
    """The detail level of the image to be sent to the model. One of `high`, `low`, or `auto`. Defaults to `auto`."""

    class Config:
        extra = "ignore"

InputImage.model_rebuild()