# Code generated by schema2code at 2026-02-23 14:46:44. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class InviteDeleteResponse(BaseModel):
    deleted: Annotated[bool, Field(...)]
    id: Annotated[str, Field(...)]
    object: Annotated[Literal["organization.invite.deleted"], Field(..., description="The object type, which is always `organization.invite.deleted`")]
    """The object type, which is always `organization.invite.deleted`"""

    class Config:
        extra = "ignore"