# Code generated by schema2code at 2026-02-23 14:46:45. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .batch import Batch
from .batch_error import BatchError
from .batch_request_counts import BatchRequestCounts
from .metadata import Metadata
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ListBatchesResponse(BaseModel):
    data: Annotated[List[Batch], Field(...)]
    first_id: Annotated[Optional[str], Field(default=None)] = None
    has_more: Annotated[bool, Field(...)]
    last_id: Annotated[Optional[str], Field(default=None)] = None
    object: Annotated[Literal["list"], Field(...)]

    class Config:
        extra = "ignore"