# Code generated by schema2code at 2026-02-23 18:05:01. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class MessageContentRefusalObject(BaseModel):
    """The refusal content generated by the assistant."""
    type: Annotated[Literal["refusal"], Field(..., description="Always `refusal`.")]
    """Always `refusal`."""
    refusal: Annotated[str, Field(...)]

    class Config:
        extra = "ignore"

class MessageContentImageUrlObject(BaseModel):
    """References an image URL in the content of a message."""
    type: Annotated[Literal["image_url"], Field(..., description="The type of the content part.")]
    """The type of the content part."""
    image_url: Annotated[ImageUrl, Field(...)]

    class Config:
        extra = "ignore"

class MessageContentTextObject(BaseModel):
    """The text content that is part of a message."""
    type: Annotated[Literal["text"], Field(..., description="Always `text`.")]
    """Always `text`."""
    text: Annotated[Text, Field(...)]

    class Config:
        extra = "ignore"

TextAnnotation = Union[MessageContentTextAnnotationsFileCitationObject, MessageContentTextAnnotationsFilePathObject]

class MessageContentTextAnnotationsFileCitationObject(BaseModel):
    """A citation within the message that points to a specific quote from a specific File associated with the assistant or the message. Generated when the assistant uses the "file_search" tool to search files."""
    type: Annotated[Literal["file_citation"], Field(..., description="Always `file_citation`.")]
    """Always `file_citation`."""
    text: Annotated[str, Field(..., description="The text in the message content that needs to be replaced.")]
    """The text in the message content that needs to be replaced."""
    file_citation: Annotated[FileCitation, Field(...)]
    start_index: Annotated[int, Field(..., ge=0)]
    end_index: Annotated[int, Field(..., ge=0)]

    class Config:
        extra = "ignore"

class MessageContentTextAnnotationsFilePathObject(BaseModel):
    """A URL for the file that's generated when the assistant used the `code_interpreter` tool to generate a file."""
    type: Annotated[Literal["file_path"], Field(..., description="Always `file_path`.")]
    """Always `file_path`."""
    text: Annotated[str, Field(..., description="The text in the message content that needs to be replaced.")]
    """The text in the message content that needs to be replaced."""
    file_path: Annotated[FilePath, Field(...)]
    start_index: Annotated[int, Field(..., ge=0)]
    end_index: Annotated[int, Field(..., ge=0)]

    class Config:
        extra = "ignore"

class MessageContentImageFileObject(BaseModel):
    """References an image [File](https://platform.openai.com/docs/api-reference/files) in the content of a message."""
    type: Annotated[Literal["image_file"], Field(..., description="Always `image_file`.")]
    """Always `image_file`."""
    image_file: Annotated[ImageFile, Field(...)]

    class Config:
        extra = "ignore"

class ImageFile(BaseModel):
    file_id: Annotated[str, Field(..., description="The [File](https://platform.openai.com/docs/api-reference/files) ID of the image in the message content. Set `purpose=\"vision\"` when uploading the File if you need to later display the file content.")]
    """The [File](https://platform.openai.com/docs/api-reference/files) ID of the image in the message content. Set `purpose=\"vision\"` when uploading the File if you need to later display the file content."""
    detail: Annotated[Optional[Literal["auto", "low", "high"]], Field(default='auto', description="Specifies the detail level of the image if specified by the user. `low` uses fewer tokens, you can opt in to high resolution using `high`.")] = 'auto'
    """Specifies the detail level of the image if specified by the user. `low` uses fewer tokens, you can opt in to high resolution using `high`."""

    class Config:
        extra = "ignore"

class ImageUrl(BaseModel):
    url: Annotated[AnyUrl, Field(..., description="The external URL of the image, must be a supported image types: jpeg, jpg, png, gif, webp.")]
    """The external URL of the image, must be a supported image types: jpeg, jpg, png, gif, webp."""
    detail: Annotated[Optional[Literal["auto", "low", "high"]], Field(default='auto', description="Specifies the detail level of the image. `low` uses fewer tokens, you can opt in to high resolution using `high`. Default value is `auto`")] = 'auto'
    """Specifies the detail level of the image. `low` uses fewer tokens, you can opt in to high resolution using `high`. Default value is `auto`"""

    class Config:
        extra = "ignore"

class Text(BaseModel):
    value: Annotated[str, Field(..., description="The data that makes up the text.")]
    """The data that makes up the text."""
    annotations: Annotated[List[TextAnnotation], Field(...)]

    class Config:
        extra = "ignore"

MessageContent = Union[MessageContentImageFileObject, MessageContentImageUrlObject, MessageContentTextObject, MessageContentRefusalObject]