# Code generated by schema2code at 2026-02-23 14:46:46. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .chat_model import ChatModel
from .model_ids_responses import ModelIdsResponses
from .model_ids_shared import ModelIdsShared
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



ModelIds = Union[ModelIdsShared, ModelIdsResponses]