# Code generated by schema2code at 2026-02-23 18:05:01. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ProjectRateLimit(BaseModel):
    """Represents a project rate limit config."""
    object: Annotated[Literal["project.rate_limit"], Field(..., description="The object type, which is always `project.rate_limit`")]
    """The object type, which is always `project.rate_limit`"""
    id: Annotated[str, Field(..., description="The identifier, which can be referenced in API endpoints.")]
    """The identifier, which can be referenced in API endpoints."""
    model: Annotated[str, Field(..., description="The model this rate limit applies to.")]
    """The model this rate limit applies to."""
    max_requests_per_1_minute: Annotated[int, Field(..., description="The maximum requests per minute.")]
    """The maximum requests per minute."""
    max_tokens_per_1_minute: Annotated[int, Field(..., description="The maximum tokens per minute.")]
    """The maximum tokens per minute."""
    max_images_per_1_minute: Annotated[Optional[int], Field(default=None, description="The maximum images per minute. Only present for relevant models.")] = None
    """The maximum images per minute. Only present for relevant models."""
    max_audio_megabytes_per_1_minute: Annotated[Optional[int], Field(default=None, description="The maximum audio megabytes per minute. Only present for relevant models.")] = None
    """The maximum audio megabytes per minute. Only present for relevant models."""
    max_requests_per_1_day: Annotated[Optional[int], Field(default=None, description="The maximum requests per day. Only present for relevant models.")] = None
    """The maximum requests per day. Only present for relevant models."""
    batch_1_day_max_input_tokens: Annotated[Optional[int], Field(default=None, description="The maximum batch input tokens per day. Only present for relevant models.")] = None
    """The maximum batch input tokens per day. Only present for relevant models."""

    class Config:
        extra = "ignore"

class ProjectRateLimitListResponse(BaseModel):
    object: Annotated[Literal["list"], Field(...)]
    data: Annotated[List[ProjectRateLimit], Field(...)]
    first_id: Annotated[str, Field(...)]
    last_id: Annotated[str, Field(...)]
    has_more: Annotated[bool, Field(...)]

    class Config:
        extra = "ignore"

ProjectRateLimitListResponse.model_rebuild()