# Code generated by schema2code at 2026-02-23 14:46:47. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .project_service_account_api_key import ProjectServiceAccountApiKey
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ProjectServiceAccountCreateResponse(BaseModel):
    api_key: Annotated[ProjectServiceAccountApiKey, Field(...)]
    created_at: Annotated[int, Field(...)]
    id: Annotated[str, Field(...)]
    name: Annotated[str, Field(...)]
    object: Annotated[Literal["organization.project.service_account"], Field(...)]
    role: Annotated[Literal["member"], Field(..., description="Service accounts can only have one role of type `member`")]
    """Service accounts can only have one role of type `member`"""

    class Config:
        extra = "ignore"