# Code generated by schema2code at 2026-02-23 14:46:48. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ProjectUser(BaseModel):
    """Represents an individual user in a project."""
    added_at: Annotated[int, Field(..., description="The Unix timestamp (in seconds) of when the project was added.")]
    """The Unix timestamp (in seconds) of when the project was added."""
    email: Annotated[str, Field(..., description="The email address of the user")]
    """The email address of the user"""
    id: Annotated[str, Field(..., description="The identifier, which can be referenced in API endpoints")]
    """The identifier, which can be referenced in API endpoints"""
    name: Annotated[str, Field(..., description="The name of the user")]
    """The name of the user"""
    object: Annotated[Literal["organization.project.user"], Field(..., description="The object type, which is always `organization.project.user`")]
    """The object type, which is always `organization.project.user`"""
    role: Annotated[Literal["owner", "member"], Field(..., description="`owner` or `member`")]
    """`owner` or `member`"""

    class Config:
        extra = "ignore"