# Code generated by schema2code at 2026-02-23 18:05:01. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class Part(BaseModel):
    """The content part that was added."""
    type: Annotated[Optional[Literal["text", "audio"]], Field(default=None, description="The content type (\"text\", \"audio\").")] = None
    """The content type (\"text\", \"audio\")."""
    text: Annotated[Optional[str], Field(default=None, description="The text content (if type is \"text\").")] = None
    """The text content (if type is \"text\")."""
    audio: Annotated[Optional[str], Field(default=None, description="Base64-encoded audio data (if type is \"audio\").")] = None
    """Base64-encoded audio data (if type is \"audio\")."""
    transcript: Annotated[Optional[str], Field(default=None, description="The transcript of the audio (if type is \"audio\").")] = None
    """The transcript of the audio (if type is \"audio\")."""

    class Config:
        extra = "ignore"

class RealtimeBetaServerEventResponseContentPartAdded(BaseModel):
    """Returned when a new content part is added to an assistant message item during
response generation.
"""
    event_id: Annotated[str, Field(..., description="The unique ID of the server event.")]
    """The unique ID of the server event."""
    type: Annotated[str, Field(..., description="The event type, must be `response.content_part.added`.")]
    """The event type, must be `response.content_part.added`."""
    response_id: Annotated[str, Field(..., description="The ID of the response.")]
    """The ID of the response."""
    item_id: Annotated[str, Field(..., description="The ID of the item to which the content part was added.")]
    """The ID of the item to which the content part was added."""
    output_index: Annotated[int, Field(..., description="The index of the output item in the response.")]
    """The index of the output item in the response."""
    content_index: Annotated[int, Field(..., description="The index of the content part in the item's content array.")]
    """The index of the content part in the item's content array."""
    part: Annotated[Part, Field(..., description="The content part that was added.")]
    """The content part that was added."""

    class Config:
        extra = "ignore"

RealtimeBetaServerEventResponseContentPartAdded.model_rebuild()