# Code generated by schema2code at 2026-02-23 18:05:01. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



RealtimeConversationItem = Union[RealtimeConversationItemMessageSystem, RealtimeConversationItemMessageUser, RealtimeConversationItemMessageAssistant, RealtimeConversationItemFunctionCall, RealtimeConversationItemFunctionCallOutput, RealtimeMCPApprovalResponse, RealtimeMCPListTools, RealtimeMCPToolCall, RealtimeMCPApprovalRequest]

class RealtimeConversationItemFunctionCall(BaseModel):
    """A function call item in a Realtime conversation."""
    id: Annotated[Optional[str], Field(default=None, description="The unique ID of the item. This may be provided by the client or generated by the server.")] = None
    """The unique ID of the item. This may be provided by the client or generated by the server."""
    object: Annotated[Optional[Literal["realtime.item"]], Field(default=None, description="Identifier for the API object being returned - always `realtime.item`. Optional when creating a new item.")] = None
    """Identifier for the API object being returned - always `realtime.item`. Optional when creating a new item."""
    type: Annotated[Literal["function_call"], Field(..., description="The type of the item. Always `function_call`.")]
    """The type of the item. Always `function_call`."""
    status: Annotated[Optional[Literal["completed", "incomplete", "in_progress"]], Field(default=None, description="The status of the item. Has no effect on the conversation.")] = None
    """The status of the item. Has no effect on the conversation."""
    call_id: Annotated[Optional[str], Field(default=None, description="The ID of the function call.")] = None
    """The ID of the function call."""
    name: Annotated[str, Field(..., description="The name of the function being called.")]
    """The name of the function being called."""
    arguments: Annotated[str, Field(..., description="The arguments of the function call. This is a JSON-encoded string representing the arguments passed to the function, for example `{\"arg1\": \"value1\", \"arg2\": 42}`.")]
    """The arguments of the function call. This is a JSON-encoded string representing the arguments passed to the function, for example `{\"arg1\": \"value1\", \"arg2\": 42}`."""

    class Config:
        extra = "ignore"

class RealtimeConversationItemMessageAssistant(BaseModel):
    """An assistant message item in a Realtime conversation."""
    id: Annotated[Optional[str], Field(default=None, description="The unique ID of the item. This may be provided by the client or generated by the server.")] = None
    """The unique ID of the item. This may be provided by the client or generated by the server."""
    object: Annotated[Optional[Literal["realtime.item"]], Field(default=None, description="Identifier for the API object being returned - always `realtime.item`. Optional when creating a new item.")] = None
    """Identifier for the API object being returned - always `realtime.item`. Optional when creating a new item."""
    type: Annotated[Literal["message"], Field(..., description="The type of the item. Always `message`.")]
    """The type of the item. Always `message`."""
    status: Annotated[Optional[Literal["completed", "incomplete", "in_progress"]], Field(default=None, description="The status of the item. Has no effect on the conversation.")] = None
    """The status of the item. Has no effect on the conversation."""
    role: Annotated[Literal["assistant"], Field(..., description="The role of the message sender. Always `assistant`.")]
    """The role of the message sender. Always `assistant`."""
    content: Annotated[List[ContentItem], Field(..., description="The content of the message.")]
    """The content of the message."""

    class Config:
        extra = "ignore"

class RealtimeConversationItemMessageSystem(BaseModel):
    """A system message in a Realtime conversation can be used to provide additional context or instructions to the model. This is similar but distinct from the instruction prompt provided at the start of a conversation, as system messages can be added at any point in the conversation. For major changes to the conversation's behavior, use instructions, but for smaller updates (e.g. "the user is now asking about a different topic"), use system messages."""
    id: Annotated[Optional[str], Field(default=None, description="The unique ID of the item. This may be provided by the client or generated by the server.")] = None
    """The unique ID of the item. This may be provided by the client or generated by the server."""
    object: Annotated[Optional[Literal["realtime.item"]], Field(default=None, description="Identifier for the API object being returned - always `realtime.item`. Optional when creating a new item.")] = None
    """Identifier for the API object being returned - always `realtime.item`. Optional when creating a new item."""
    type: Annotated[Literal["message"], Field(..., description="The type of the item. Always `message`.")]
    """The type of the item. Always `message`."""
    status: Annotated[Optional[Literal["completed", "incomplete", "in_progress"]], Field(default=None, description="The status of the item. Has no effect on the conversation.")] = None
    """The status of the item. Has no effect on the conversation."""
    role: Annotated[Literal["system"], Field(..., description="The role of the message sender. Always `system`.")]
    """The role of the message sender. Always `system`."""
    content: Annotated[List[ContentItem], Field(..., description="The content of the message.")]
    """The content of the message."""

    class Config:
        extra = "ignore"

class RealtimeMCPToolCall(BaseModel):
    """A Realtime item representing an invocation of a tool on an MCP server.
"""
    type: Annotated[Literal["mcp_call"], Field(..., description="The type of the item. Always `mcp_call`.")]
    """The type of the item. Always `mcp_call`."""
    id: Annotated[str, Field(..., description="The unique ID of the tool call.")]
    """The unique ID of the tool call."""
    server_label: Annotated[str, Field(..., description="The label of the MCP server running the tool.")]
    """The label of the MCP server running the tool."""
    name: Annotated[str, Field(..., description="The name of the tool that was run.")]
    """The name of the tool that was run."""
    arguments: Annotated[str, Field(..., description="A JSON string of the arguments passed to the tool.")]
    """A JSON string of the arguments passed to the tool."""
    approval_request_id: Annotated[Optional[Union[str, Any]], Field(default=None)] = None
    output: Annotated[Optional[Union[str, Any]], Field(default=None)] = None
    error: Annotated[Optional[Union[Union[RealtimeMCPProtocolError, RealtimeMCPToolExecutionError, RealtimeMCPHTTPError], Any]], Field(default=None)] = None

    class Config:
        extra = "ignore"

class RealtimeMCPProtocolError(BaseModel):
    type: Annotated[Literal["protocol_error"], Field(...)]
    code: Annotated[int, Field(...)]
    message: Annotated[str, Field(...)]

    class Config:
        extra = "ignore"

class RealtimeMCPToolExecutionError(BaseModel):
    type: Annotated[Literal["tool_execution_error"], Field(...)]
    message: Annotated[str, Field(...)]

    class Config:
        extra = "ignore"

class RealtimeMCPHTTPError(BaseModel):
    type: Annotated[Literal["http_error"], Field(...)]
    code: Annotated[int, Field(...)]
    message: Annotated[str, Field(...)]

    class Config:
        extra = "ignore"

class RealtimeMCPApprovalRequest(BaseModel):
    """A Realtime item requesting human approval of a tool invocation.
"""
    type: Annotated[Literal["mcp_approval_request"], Field(..., description="The type of the item. Always `mcp_approval_request`.")]
    """The type of the item. Always `mcp_approval_request`."""
    id: Annotated[str, Field(..., description="The unique ID of the approval request.")]
    """The unique ID of the approval request."""
    server_label: Annotated[str, Field(..., description="The label of the MCP server making the request.")]
    """The label of the MCP server making the request."""
    name: Annotated[str, Field(..., description="The name of the tool to run.")]
    """The name of the tool to run."""
    arguments: Annotated[str, Field(..., description="A JSON string of arguments for the tool.")]
    """A JSON string of arguments for the tool."""

    class Config:
        extra = "ignore"

class RealtimeMCPApprovalResponse(BaseModel):
    """A Realtime item responding to an MCP approval request.
"""
    type: Annotated[Literal["mcp_approval_response"], Field(..., description="The type of the item. Always `mcp_approval_response`.")]
    """The type of the item. Always `mcp_approval_response`."""
    id: Annotated[str, Field(..., description="The unique ID of the approval response.")]
    """The unique ID of the approval response."""
    approval_request_id: Annotated[str, Field(..., description="The ID of the approval request being answered.")]
    """The ID of the approval request being answered."""
    approve: Annotated[bool, Field(..., description="Whether the request was approved.")]
    """Whether the request was approved."""
    reason: Annotated[Optional[Union[str, Any]], Field(default=None)] = None

    class Config:
        extra = "ignore"

class RealtimeConversationItemMessageUser(BaseModel):
    """A user message item in a Realtime conversation."""
    id: Annotated[Optional[str], Field(default=None, description="The unique ID of the item. This may be provided by the client or generated by the server.")] = None
    """The unique ID of the item. This may be provided by the client or generated by the server."""
    object: Annotated[Optional[Literal["realtime.item"]], Field(default=None, description="Identifier for the API object being returned - always `realtime.item`. Optional when creating a new item.")] = None
    """Identifier for the API object being returned - always `realtime.item`. Optional when creating a new item."""
    type: Annotated[Literal["message"], Field(..., description="The type of the item. Always `message`.")]
    """The type of the item. Always `message`."""
    status: Annotated[Optional[Literal["completed", "incomplete", "in_progress"]], Field(default=None, description="The status of the item. Has no effect on the conversation.")] = None
    """The status of the item. Has no effect on the conversation."""
    role: Annotated[Literal["user"], Field(..., description="The role of the message sender. Always `user`.")]
    """The role of the message sender. Always `user`."""
    content: Annotated[List[ContentItem], Field(..., description="The content of the message.")]
    """The content of the message."""

    class Config:
        extra = "ignore"

class RealtimeConversationItemFunctionCallOutput(BaseModel):
    """A function call output item in a Realtime conversation."""
    id: Annotated[Optional[str], Field(default=None, description="The unique ID of the item. This may be provided by the client or generated by the server.")] = None
    """The unique ID of the item. This may be provided by the client or generated by the server."""
    object: Annotated[Optional[Literal["realtime.item"]], Field(default=None, description="Identifier for the API object being returned - always `realtime.item`. Optional when creating a new item.")] = None
    """Identifier for the API object being returned - always `realtime.item`. Optional when creating a new item."""
    type: Annotated[Literal["function_call_output"], Field(..., description="The type of the item. Always `function_call_output`.")]
    """The type of the item. Always `function_call_output`."""
    status: Annotated[Optional[Literal["completed", "incomplete", "in_progress"]], Field(default=None, description="The status of the item. Has no effect on the conversation.")] = None
    """The status of the item. Has no effect on the conversation."""
    call_id: Annotated[str, Field(..., description="The ID of the function call this output is for.")]
    """The ID of the function call this output is for."""
    output: Annotated[str, Field(..., description="The output of the function call, this is free text and can contain any information or simply be empty.")]
    """The output of the function call, this is free text and can contain any information or simply be empty."""

    class Config:
        extra = "ignore"

class RealtimeMCPListTools(BaseModel):
    """A Realtime item listing tools available on an MCP server.
"""
    type: Annotated[Literal["mcp_list_tools"], Field(..., description="The type of the item. Always `mcp_list_tools`.")]
    """The type of the item. Always `mcp_list_tools`."""
    id: Annotated[Optional[str], Field(default=None, description="The unique ID of the list.")] = None
    """The unique ID of the list."""
    server_label: Annotated[str, Field(..., description="The label of the MCP server.")]
    """The label of the MCP server."""
    tools: Annotated[List[MCPListToolsTool], Field(..., description="The tools available on the server.")]
    """The tools available on the server."""

    class Config:
        extra = "ignore"

class MCPListToolsTool(BaseModel):
    """A tool available on an MCP server.
"""
    name: Annotated[str, Field(..., description="The name of the tool. ")]
    """The name of the tool. """
    description: Annotated[Optional[Union[str, Any]], Field(default=None)] = None
    input_schema: Annotated[Dict[str, Any], Field(..., description="The JSON schema describing the tool's input. ")]
    """The JSON schema describing the tool's input. """
    annotations: Annotated[Optional[Union[Dict[str, Any], Any]], Field(default=None)] = None

    class Config:
        extra = "ignore"

class RealtimeBetaServerEventConversationItemCreated(BaseModel):
    """Returned when a conversation item is created. There are several scenarios that produce this event:
  - The server is generating a Response, which if successful will produce
    either one or two Items, which will be of type `message`
    (role `assistant`) or type `function_call`.
  - The input audio buffer has been committed, either by the client or the
    server (in `server_vad` mode). The server will take the content of the
    input audio buffer and add it to a new user message Item.
  - The client has sent a `conversation.item.create` event to add a new Item
    to the Conversation.
"""
    event_id: Annotated[str, Field(..., description="The unique ID of the server event.")]
    """The unique ID of the server event."""
    type: Annotated[str, Field(..., description="The event type, must be `conversation.item.created`.")]
    """The event type, must be `conversation.item.created`."""
    previous_item_id: Annotated[Optional[Union[str, Any]], Field(default=None)] = None
    item: Annotated[RealtimeConversationItem, Field(...)]

    class Config:
        extra = "ignore"

RealtimeBetaServerEventConversationItemCreated.model_rebuild()