# Code generated by schema2code at 2026-02-23 18:05:01. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ResponseMCPCallFailedEvent(BaseModel):
    """Emitted when an MCP  tool call has failed.
"""
    type: Annotated[Literal["response.mcp_call.failed"], Field(..., description="The type of the event. Always 'response.mcp_call.failed'.")]
    """The type of the event. Always 'response.mcp_call.failed'."""
    item_id: Annotated[str, Field(..., description="The ID of the MCP tool call item that failed.")]
    """The ID of the MCP tool call item that failed."""
    output_index: Annotated[int, Field(..., description="The index of the output item that failed.")]
    """The index of the output item that failed."""
    sequence_number: Annotated[int, Field(..., description="The sequence number of this event.")]
    """The sequence number of this event."""

    class Config:
        extra = "ignore"