# Code generated by schema2code at 2026-02-23 18:05:01. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class RoleDeletedResource(BaseModel):
    """Confirmation payload returned after deleting a role."""
    object: Annotated[Literal["role.deleted"], Field(..., description="Always `role.deleted`.")]
    """Always `role.deleted`."""
    id: Annotated[str, Field(..., description="Identifier of the deleted role.")]
    """Identifier of the deleted role."""
    deleted: Annotated[bool, Field(..., description="Whether the role was deleted.")]
    """Whether the role was deleted."""

    class Config:
        extra = "ignore"