# Code generated by schema2code at 2026-02-23 18:05:01. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class SummaryText(BaseModel):
    """A summary text from the model."""
    type: Annotated[Literal["summary_text"], Field(default='summary_text', description="The type of the object. Always `summary_text`.")]
    """The type of the object. Always `summary_text`."""
    text: Annotated[str, Field(..., description="A summary of the reasoning output from the model so far.")]
    """A summary of the reasoning output from the model so far."""

    class Config:
        extra = "ignore"