# Code generated by schema2code at 2026-02-23 14:46:56. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .metadata import Metadata
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class CodeInterpreter(BaseModel):
    file_ids: Annotated[Optional[List[str]], Field(default_factory=lambda: [], description="A list of [file](https://platform.openai.com/docs/api-reference/files) IDs made available to the `code_interpreter` tool. There can be a maximum of 20 files associated with the tool. ")]
    """A list of [file](https://platform.openai.com/docs/api-reference/files) IDs made available to the `code_interpreter` tool. There can be a maximum of 20 files associated with the tool. """

    class Config:
        extra = "ignore"

class FileSearch(BaseModel):
    vector_store_ids: Annotated[Optional[List[str]], Field(default=None, description="The [vector store](https://platform.openai.com/docs/api-reference/vector-stores/object) attached to this thread. There can be a maximum of 1 vector store attached to the thread. ")] = None
    """The [vector store](https://platform.openai.com/docs/api-reference/vector-stores/object) attached to this thread. There can be a maximum of 1 vector store attached to the thread. """

    class Config:
        extra = "ignore"

class ToolResources(BaseModel):
    """A set of resources that are made available to the assistant's tools in this thread. The resources are specific to the type of tool. For example, the `code_interpreter` tool requires a list of file IDs, while the `file_search` tool requires a list of vector store IDs.
"""
    code_interpreter: Annotated[Optional[CodeInterpreter], Field(default=None)] = None
    file_search: Annotated[Optional[FileSearch], Field(default=None)] = None

    class Config:
        extra = "ignore"

class ThreadObject(BaseModel):
    """Represents a thread that contains [messages](https://platform.openai.com/docs/api-reference/messages)."""
    created_at: Annotated[int, Field(..., description="The Unix timestamp (in seconds) for when the thread was created.")]
    """The Unix timestamp (in seconds) for when the thread was created."""
    id: Annotated[str, Field(..., description="The identifier, which can be referenced in API endpoints.")]
    """The identifier, which can be referenced in API endpoints."""
    metadata: Annotated[Metadata, Field(...)]
    object: Annotated[Literal["thread"], Field(..., description="The object type, which is always `thread`.")]
    """The object type, which is always `thread`."""
    tool_resources: Annotated[Union[ToolResources, Any], Field(...)]

    class Config:
        extra = "ignore"

ThreadObject.model_rebuild()