# Code generated by schema2code at 2026-02-23 18:05:01. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class TaskGroupItem(BaseModel):
    """Collection of workflow tasks grouped together in the thread."""
    id: Annotated[str, Field(..., description="Identifier of the thread item.")]
    """Identifier of the thread item."""
    object: Annotated[Literal["chatkit.thread_item"], Field(default='chatkit.thread_item', description="Type discriminator that is always `chatkit.thread_item`.")]
    """Type discriminator that is always `chatkit.thread_item`."""
    created_at: Annotated[int, Field(..., description="Unix timestamp (in seconds) for when the item was created.")]
    """Unix timestamp (in seconds) for when the item was created."""
    thread_id: Annotated[str, Field(..., description="Identifier of the parent thread.")]
    """Identifier of the parent thread."""
    type: Annotated[Literal["chatkit.task_group"], Field(default='chatkit.task_group', description="Type discriminator that is always `chatkit.task_group`.")]
    """Type discriminator that is always `chatkit.task_group`."""
    tasks: Annotated[List[TaskGroupTask], Field(..., description="Tasks included in the group.")]
    """Tasks included in the group."""

    class Config:
        extra = "ignore"

class TaskGroupTask(BaseModel):
    """Task entry that appears within a TaskGroup."""
    type: Annotated[TaskType, Field(..., description="Subtype for the grouped task.")]
    """Subtype for the grouped task."""
    heading: Annotated[Union[str, Any], Field(...)]
    summary: Annotated[Union[str, Any], Field(...)]

    class Config:
        extra = "ignore"

class TaskType(str, Enum):
    CUSTOM = 'custom'
    THOUGHT = 'thought'

class AssistantMessageItem(BaseModel):
    """Assistant-authored message within a thread."""
    id: Annotated[str, Field(..., description="Identifier of the thread item.")]
    """Identifier of the thread item."""
    object: Annotated[Literal["chatkit.thread_item"], Field(default='chatkit.thread_item', description="Type discriminator that is always `chatkit.thread_item`.")]
    """Type discriminator that is always `chatkit.thread_item`."""
    created_at: Annotated[int, Field(..., description="Unix timestamp (in seconds) for when the item was created.")]
    """Unix timestamp (in seconds) for when the item was created."""
    thread_id: Annotated[str, Field(..., description="Identifier of the parent thread.")]
    """Identifier of the parent thread."""
    type: Annotated[Literal["chatkit.assistant_message"], Field(default='chatkit.assistant_message', description="Type discriminator that is always `chatkit.assistant_message`.")]
    """Type discriminator that is always `chatkit.assistant_message`."""
    content: Annotated[List[ResponseOutputText], Field(..., description="Ordered assistant response segments.")]
    """Ordered assistant response segments."""

    class Config:
        extra = "ignore"

class ResponseOutputText(BaseModel):
    """Assistant response text accompanied by optional annotations."""
    type: Annotated[Literal["output_text"], Field(default='output_text', description="Type discriminator that is always `output_text`.")]
    """Type discriminator that is always `output_text`."""
    text: Annotated[str, Field(..., description="Assistant generated text.")]
    """Assistant generated text."""
    annotations: Annotated[List[Union[FileAnnotation, UrlAnnotation]], Field(..., description="Ordered list of annotations attached to the response text.")]
    """Ordered list of annotations attached to the response text."""

    class Config:
        extra = "ignore"

class FileAnnotation(BaseModel):
    """Annotation that references an uploaded file."""
    type: Annotated[Literal["file"], Field(default='file', description="Type discriminator that is always `file` for this annotation.")]
    """Type discriminator that is always `file` for this annotation."""
    source: Annotated[FileAnnotationSource, Field(..., description="File attachment referenced by the annotation.")]
    """File attachment referenced by the annotation."""

    class Config:
        extra = "ignore"

class FileAnnotationSource(BaseModel):
    """Attachment source referenced by an annotation."""
    type: Annotated[Literal["file"], Field(default='file', description="Type discriminator that is always `file`.")]
    """Type discriminator that is always `file`."""
    filename: Annotated[str, Field(..., description="Filename referenced by the annotation.")]
    """Filename referenced by the annotation."""

    class Config:
        extra = "ignore"

class UrlAnnotation(BaseModel):
    """Annotation that references a URL."""
    type: Annotated[Literal["url"], Field(default='url', description="Type discriminator that is always `url` for this annotation.")]
    """Type discriminator that is always `url` for this annotation."""
    source: Annotated[UrlAnnotationSource, Field(..., description="URL referenced by the annotation.")]
    """URL referenced by the annotation."""

    class Config:
        extra = "ignore"

class UrlAnnotationSource(BaseModel):
    """URL backing an annotation entry."""
    type: Annotated[Literal["url"], Field(default='url', description="Type discriminator that is always `url`.")]
    """Type discriminator that is always `url`."""
    url: Annotated[str, Field(..., description="URL referenced by the annotation.")]
    """URL referenced by the annotation."""

    class Config:
        extra = "ignore"

class UserMessageItem(BaseModel):
    """User-authored messages within a thread."""
    id: Annotated[str, Field(..., description="Identifier of the thread item.")]
    """Identifier of the thread item."""
    object: Annotated[Literal["chatkit.thread_item"], Field(default='chatkit.thread_item', description="Type discriminator that is always `chatkit.thread_item`.")]
    """Type discriminator that is always `chatkit.thread_item`."""
    created_at: Annotated[int, Field(..., description="Unix timestamp (in seconds) for when the item was created.")]
    """Unix timestamp (in seconds) for when the item was created."""
    thread_id: Annotated[str, Field(..., description="Identifier of the parent thread.")]
    """Identifier of the parent thread."""
    type: Annotated[Literal["chatkit.user_message"], Field(default='chatkit.user_message')]
    content: Annotated[List[Union[UserMessageInputText, UserMessageQuotedText]], Field(..., description="Ordered content elements supplied by the user.")]
    """Ordered content elements supplied by the user."""
    attachments: Annotated[List[Attachment], Field(..., description="Attachments associated with the user message. Defaults to an empty list.")]
    """Attachments associated with the user message. Defaults to an empty list."""
    inference_options: Annotated[Union[InferenceOptions, Any], Field(...)]

    class Config:
        extra = "ignore"

class UserMessageQuotedText(BaseModel):
    """Quoted snippet that the user referenced in their message."""
    type: Annotated[Literal["quoted_text"], Field(default='quoted_text', description="Type discriminator that is always `quoted_text`.")]
    """Type discriminator that is always `quoted_text`."""
    text: Annotated[str, Field(..., description="Quoted text content.")]
    """Quoted text content."""

    class Config:
        extra = "ignore"

class Attachment(BaseModel):
    """Attachment metadata included on thread items."""
    type: Annotated[AttachmentType, Field(..., description="Attachment discriminator.")]
    """Attachment discriminator."""
    id: Annotated[str, Field(..., description="Identifier for the attachment.")]
    """Identifier for the attachment."""
    name: Annotated[str, Field(..., description="Original display name for the attachment.")]
    """Original display name for the attachment."""
    mime_type: Annotated[str, Field(..., description="MIME type of the attachment.")]
    """MIME type of the attachment."""
    preview_url: Annotated[Union[str, Any], Field(...)]

    class Config:
        extra = "ignore"

class AttachmentType(str, Enum):
    IMAGE = 'image'
    FILE = 'file'

class InferenceOptions(BaseModel):
    """Model and tool overrides applied when generating the assistant response."""
    tool_choice: Annotated[Union[ToolChoice, Any], Field(...)]
    model: Annotated[Union[str, Any], Field(...)]

    class Config:
        extra = "ignore"

class ToolChoice(BaseModel):
    """Tool selection that the assistant should honor when executing the item."""
    id: Annotated[str, Field(..., description="Identifier of the requested tool.")]
    """Identifier of the requested tool."""

    class Config:
        extra = "ignore"

class UserMessageInputText(BaseModel):
    """Text block that a user contributed to the thread."""
    type: Annotated[Literal["input_text"], Field(default='input_text', description="Type discriminator that is always `input_text`.")]
    """Type discriminator that is always `input_text`."""
    text: Annotated[str, Field(..., description="Plain-text content supplied by the user.")]
    """Plain-text content supplied by the user."""

    class Config:
        extra = "ignore"

class TaskItem(BaseModel):
    """Task emitted by the workflow to show progress and status updates."""
    id: Annotated[str, Field(..., description="Identifier of the thread item.")]
    """Identifier of the thread item."""
    object: Annotated[Literal["chatkit.thread_item"], Field(default='chatkit.thread_item', description="Type discriminator that is always `chatkit.thread_item`.")]
    """Type discriminator that is always `chatkit.thread_item`."""
    created_at: Annotated[int, Field(..., description="Unix timestamp (in seconds) for when the item was created.")]
    """Unix timestamp (in seconds) for when the item was created."""
    thread_id: Annotated[str, Field(..., description="Identifier of the parent thread.")]
    """Identifier of the parent thread."""
    type: Annotated[Literal["chatkit.task"], Field(default='chatkit.task', description="Type discriminator that is always `chatkit.task`.")]
    """Type discriminator that is always `chatkit.task`."""
    task_type: Annotated[TaskType, Field(..., description="Subtype for the task.")]
    """Subtype for the task."""
    heading: Annotated[Union[str, Any], Field(...)]
    summary: Annotated[Union[str, Any], Field(...)]

    class Config:
        extra = "ignore"

class WidgetMessageItem(BaseModel):
    """Thread item that renders a widget payload."""
    id: Annotated[str, Field(..., description="Identifier of the thread item.")]
    """Identifier of the thread item."""
    object: Annotated[Literal["chatkit.thread_item"], Field(default='chatkit.thread_item', description="Type discriminator that is always `chatkit.thread_item`.")]
    """Type discriminator that is always `chatkit.thread_item`."""
    created_at: Annotated[int, Field(..., description="Unix timestamp (in seconds) for when the item was created.")]
    """Unix timestamp (in seconds) for when the item was created."""
    thread_id: Annotated[str, Field(..., description="Identifier of the parent thread.")]
    """Identifier of the parent thread."""
    type: Annotated[Literal["chatkit.widget"], Field(default='chatkit.widget', description="Type discriminator that is always `chatkit.widget`.")]
    """Type discriminator that is always `chatkit.widget`."""
    widget: Annotated[str, Field(..., description="Serialized widget payload rendered in the UI.")]
    """Serialized widget payload rendered in the UI."""

    class Config:
        extra = "ignore"

class ClientToolCallItem(BaseModel):
    """Record of a client side tool invocation initiated by the assistant."""
    id: Annotated[str, Field(..., description="Identifier of the thread item.")]
    """Identifier of the thread item."""
    object: Annotated[Literal["chatkit.thread_item"], Field(default='chatkit.thread_item', description="Type discriminator that is always `chatkit.thread_item`.")]
    """Type discriminator that is always `chatkit.thread_item`."""
    created_at: Annotated[int, Field(..., description="Unix timestamp (in seconds) for when the item was created.")]
    """Unix timestamp (in seconds) for when the item was created."""
    thread_id: Annotated[str, Field(..., description="Identifier of the parent thread.")]
    """Identifier of the parent thread."""
    type: Annotated[Literal["chatkit.client_tool_call"], Field(default='chatkit.client_tool_call', description="Type discriminator that is always `chatkit.client_tool_call`.")]
    """Type discriminator that is always `chatkit.client_tool_call`."""
    status: Annotated[ClientToolCallStatus, Field(..., description="Execution status for the tool call.")]
    """Execution status for the tool call."""
    call_id: Annotated[str, Field(..., description="Identifier for the client tool call.")]
    """Identifier for the client tool call."""
    name: Annotated[str, Field(..., description="Tool name that was invoked.")]
    """Tool name that was invoked."""
    arguments: Annotated[str, Field(..., description="JSON-encoded arguments that were sent to the tool.")]
    """JSON-encoded arguments that were sent to the tool."""
    output: Annotated[Union[str, Any], Field(...)]

    class Config:
        extra = "ignore"

class ClientToolCallStatus(str, Enum):
    IN_PROGRESS = 'in_progress'
    COMPLETED = 'completed'

TheThreadItem = Union[UserMessageItem, AssistantMessageItem, WidgetMessageItem, ClientToolCallItem, TaskItem, TaskGroupItem]