# Code generated by schema2code at 2026-02-23 14:46:57. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .metadata import Metadata
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class UpdateConversationBody(BaseModel):
    metadata: Annotated[Metadata, Field(..., description="Set of 16 key-value pairs that can be attached to an object. This can be         useful for storing additional information about the object in a structured         format, and querying for objects via API or the dashboard.         Keys are strings with a maximum length of 64 characters. Values are strings         with a maximum length of 512 characters.")]
    """Set of 16 key-value pairs that can be attached to an object. This can be         useful for storing additional information about the object in a structured         format, and querying for objects via API or the dashboard.         Keys are strings with a maximum length of 64 characters. Values are strings         with a maximum length of 512 characters."""

    class Config:
        extra = "ignore"