# Code generated by schema2code at 2026-02-23 14:46:57. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .metadata import Metadata
from .vector_store_expiration_after import VectorStoreExpirationAfter
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class UpdateVectorStoreRequest(BaseModel):
    expires_after: Annotated[Optional[str], Field(default=None)] = None
    metadata: Annotated[Optional[Metadata], Field(default=None)] = None
    name: Annotated[Optional[str], Field(default=None, description="The name of the vector store.")] = None
    """The name of the vector store."""

    class Config:
        extra = "ignore"