// Code generated by schema2code at 2026-02-23 15:57:14. DO NOT EDIT.

package schema


// APIResponse A test schema with an acronym in the title
type APIResponse struct {
	StatusCode *int   `json:"status_code" yaml:"status_code"` // HTTP status code
	Body       *string `json:"body" yaml:"body"` // Response body
}
