// Code generated by schema2code at 2026-02-23 15:57:26. DO NOT EDIT.

package schema


type AttachmentType string

const (
	AttachmentTypeImage AttachmentType = "image"
	AttachmentTypeFile AttachmentType = "file"
)