// Code generated by schema2code at 2025-10-27 18:24:53. DO NOT EDIT.

package schema


// AvailableToolType The type of the tool
type AvailableToolType string

const (
	AvailableToolTypeStatic AvailableToolType = "static"
	AvailableToolTypeDynamic AvailableToolType = "dynamic"
)
// AvailableTool A tool made available for use in the system
type AvailableTool struct {
	Name        *string `json:"name" yaml:"name"` // The name of the tool
	Description *string `json:"description" yaml:"description"` // A description of the tool's purpose
	Type        *AvailableToolType `json:"type" yaml:"type"` // The type of the tool
}
