// Code generated by schema2code at 2026-02-23 15:57:30. DO NOT EDIT.

package schema



// ChatCompletionRequestMessageContentPartImageType The type of the content part.
type ChatCompletionRequestMessageContentPartImageType string

const (
	ChatCompletionRequestMessageContentPartImageTypeImageUrl ChatCompletionRequestMessageContentPartImageType = "image_url"
)
// ChatCompletionRequestMessageContentPartImage Learn about [image inputs](https://platform.openai.com/docs/guides/vision).

type ChatCompletionRequestMessageContentPartImage struct {
	ImageURL ImageUrl `json:"image_url" yaml:"image_url" validate:"required"`
	Type     ChatCompletionRequestMessageContentPartImageType `json:"type" yaml:"type" validate:"required"` // The type of the content part.
}
