// Code generated by schema2code at 2026-02-23 15:57:32. DO NOT EDIT.

package schema


// ChatSessionHistory History retention preferences returned for the session.
type ChatSessionHistory struct {
	Enabled       bool        `json:"enabled" yaml:"enabled" validate:"required"` // Indicates if chat history is persisted for the session.
	RecentThreads interface{} `json:"recent_threads" yaml:"recent_threads" validate:"required"`
}
