// Code generated by schema2code at 2026-02-23 15:57:50. DO NOT EDIT.

package schema



// ChatCompletionToolType The type of the tool. Currently, only `function` is supported.
type ChatCompletionToolType string

const (
	ChatCompletionToolTypeFunction ChatCompletionToolType = "function"
)
// ChatCompletionTool A function tool that can be used to generate a response.

type ChatCompletionTool struct {
	Function FunctionObject `json:"function" yaml:"function" validate:"required"`
	Type     ChatCompletionToolType `json:"type" yaml:"type" validate:"required"` // The type of the tool. Currently, only `function` is supported.
}
