// Code generated by schema2code at 2026-02-23 15:58:39. DO NOT EDIT.

package schema


// ClientToolCallItemObject Type discriminator that is always `chatkit.thread_item`.
type ClientToolCallItemObject string

const (
	ClientToolCallItemObjectChatkitThreadItem ClientToolCallItemObject = "chatkit.thread_item"
)
// ClientToolCallItemType Type discriminator that is always `chatkit.client_tool_call`.
type ClientToolCallItemType string

const (
	ClientToolCallItemTypeChatkitClientToolCall ClientToolCallItemType = "chatkit.client_tool_call"
)
// ClientToolCallItem Record of a client side tool invocation initiated by the assistant.
type ClientToolCallItem struct {
	Arguments string               `json:"arguments" yaml:"arguments" validate:"required"` // JSON-encoded arguments that were sent to the tool.
	CallID    string               `json:"call_id" yaml:"call_id" validate:"required"` // Identifier for the client tool call.
	CreatedAt int                  `json:"created_at" yaml:"created_at" validate:"required"` // Unix timestamp (in seconds) for when the item was created.
	ID        string               `json:"id" yaml:"id" validate:"required"` // Identifier of the thread item.
	Name      string               `json:"name" yaml:"name" validate:"required"` // Tool name that was invoked.
	Object    ClientToolCallItemObject `json:"object" yaml:"object" validate:"default="chatkit.thread_item",required"` // Type discriminator that is always `chatkit.thread_item`.
	Output    interface{}          `json:"output" yaml:"output" validate:"required"`
	Status    ClientToolCallStatus `json:"status" yaml:"status" validate:"required"` // Execution status for the tool call.
	ThreadID  string               `json:"thread_id" yaml:"thread_id" validate:"required"` // Identifier of the parent thread.
	Type      ClientToolCallItemType `json:"type" yaml:"type" validate:"default="chatkit.client_tool_call",required"` // Type discriminator that is always `chatkit.client_tool_call`.
}
