// Code generated by schema2code at 2026-02-23 15:58:40. DO NOT EDIT.

package schema


type ComputerEnvironment string

const (
	ComputerEnvironmentWindows ComputerEnvironment = "windows"
	ComputerEnvironmentMac ComputerEnvironment = "mac"
	ComputerEnvironmentLinux ComputerEnvironment = "linux"
	ComputerEnvironmentUbuntu ComputerEnvironment = "ubuntu"
	ComputerEnvironmentBrowser ComputerEnvironment = "browser"
)