// Code generated by schema2code at 2026-02-23 15:58:05. DO NOT EDIT.

package schema


// ComputerCallSafetyCheckParam A pending safety check for the computer call.
type ComputerCallSafetyCheckParam struct {
	Code    interface{} `json:"code" yaml:"code"`
	ID      string      `json:"id" yaml:"id" validate:"required"` // The ID of the pending safety check.
	Message interface{} `json:"message" yaml:"message"`
}
