// Code generated by schema2code at 2025-08-03 11:47:25. DO NOT EDIT.

package schema
















// Config Application configuration
type Config struct {
	Server            ServerConfig           `json:"server" yaml:"server"`
	Database          DatabaseConfig         `json:"database" yaml:"database"`
	Redis             RedisConfig            `json:"redis" yaml:"redis"`
	Rabbitmq          RabbitmqConfig         `json:"rabbitmq" yaml:"rabbitmq"`
	Auth              AuthConfig             `json:"auth" yaml:"auth"`
	InferenceServices InferenceServiceConfig `json:"inference_services" yaml:"inference_services"`
	Summarization     SummarizationConfig    `json:"summarization" yaml:"summarization"`
	Memory            MemoryConfig           `json:"memory" yaml:"memory"`
	WebSearch         WebSearchConfig        `json:"web_search" yaml:"web_search"`
	Preferences       PreferencesConfig      `json:"preferences" yaml:"preferences"`
	ModelProfiles     ModelProfileConfig     `json:"model_profiles" yaml:"model_profiles"`
	Refinement        RefinementConfig       `json:"refinement" yaml:"refinement"`
	ImageGeneration   ImageGenerationConfig  `json:"image_generation" yaml:"image_generation"`
	LogLevel          string                 `json:"log_level" yaml:"log_level"` // Log level
	Internal          *InternalConfig        `json:"internal" yaml:"internal"`
}
