// Code generated by schema2code at 2026-02-23 15:57:35. DO NOT EDIT.

package schema


type ContainerFileListResource struct {
	Data    []ContainerFileResource `json:"data" yaml:"data" validate:"required"` // A list of container files.
	FirstID string                  `json:"first_id" yaml:"first_id" validate:"required"` // The ID of the first file in the list.
	HasMore bool                    `json:"has_more" yaml:"has_more" validate:"required"` // Whether there are more files available.
	LastID  string                  `json:"last_id" yaml:"last_id" validate:"required"` // The ID of the last file in the list.
	Object  string                  `json:"object" yaml:"object" validate:"required"` // The type of object returned, must be 'list'.
}
