// Code generated by schema2code at 2026-02-23 15:57:36. DO NOT EDIT.

package schema


// ConversationParam The conversation that this response belongs to. Items from this conversation are prepended to `input_items` for this response request.
Input items and output items from this response are automatically added to this conversation after this response completes.

type ConversationParam struct {
}
