// Code generated by schema2code at 2026-02-23 15:57:39. DO NOT EDIT.

package schema


// Hyperparameters The hyperparameters used for the fine-tuning job.
This value is now deprecated in favor of `method`, and should be passed in under the `method` parameter.

type Hyperparameters struct {
	BatchSize              interface{} `json:"batch_size" yaml:"batch_size" validate:"default="auto""` // Number of examples in each batch. A larger batch size means that model parameters
are updated less frequently, but with lower variance.

	LearningRateMultiplier interface{} `json:"learning_rate_multiplier" yaml:"learning_rate_multiplier"` // Scaling factor for the learning rate. A smaller learning rate may be useful to avoid
overfitting.

	NEpochs                interface{} `json:"n_epochs" yaml:"n_epochs" validate:"default="auto""` // The number of epochs to train the model for. An epoch refers to one full cycle
through the training dataset.

}

// Wandb The settings for your integration with Weights and Biases. This payload specifies the project that
metrics will be sent to. Optionally, you can set an explicit display name for your run, add tags
to your run, and set a default entity (team, username, etc) to be associated with your run.

type Wandb struct {
	Entity  *string  `json:"entity" yaml:"entity"` // The entity to use for the run. This allows you to set the team or username of the WandB user that you would
like associated with the run. If not set, the default entity for the registered WandB API key is used.

	Name    *string  `json:"name" yaml:"name"` // A display name to set for the run. If not set, we will use the Job ID as the name.

	Project string   `json:"project" yaml:"project" validate:"required"` // The name of the project that the new run will be created under.

	Tags    []string `json:"tags" yaml:"tags"` // A list of tags to be attached to the newly created run. These tags are passed through directly to WandB. Some
default tags are generated by OpenAI: "openai/finetune", "openai/{base-model}", "openai/{ftjob-abcdef}".

}

type IntegrationsItem struct {
	Type  interface{} `json:"type" yaml:"type" validate:"required"` // The type of integration to enable. Currently, only "wandb" (Weights and Biases) is supported.

	Wandb Wandb       `json:"wandb" yaml:"wandb" validate:"required"` // The settings for your integration with Weights and Biases. This payload specifies the project that
metrics will be sent to. Optionally, you can set an explicit display name for your run, add tags
to your run, and set a default entity (team, username, etc) to be associated with your run.

}


type CreateFineTuningJobRequest struct {
	Hyperparameters *Hyperparameters   `json:"hyperparameters" yaml:"hyperparameters"` // The hyperparameters used for the fine-tuning job.
This value is now deprecated in favor of `method`, and should be passed in under the `method` parameter.

	Integrations    []Integrationsitem `json:"integrations" yaml:"integrations"` // A list of integrations to enable for your fine-tuning job.
	Metadata        *Metadata          `json:"metadata" yaml:"metadata"`
	Method          *FineTuneMethod    `json:"method" yaml:"method"`
	Model           interface{}        `json:"model" yaml:"model" validate:"required"` // The name of the model to fine-tune. You can select one of the
[supported models](https://platform.openai.com/docs/guides/fine-tuning#which-models-can-be-fine-tuned).

	Seed            *int               `json:"seed" yaml:"seed" validate:"min=0,max=2147483647"` // The seed controls the reproducibility of the job. Passing in the same seed and job parameters should produce the same results, but may differ in rare cases.
If a seed is not specified, one will be generated for you.

	Suffix          *string            `json:"suffix" yaml:"suffix" validate:"default=None"` // A string of up to 64 characters that will be added to your fine-tuned model name.

For example, a `suffix` of "custom-model-name" would produce a model name like `ft:gpt-4o-mini:openai:custom-model-name:7p4lURel`.

	TrainingFile    string             `json:"training_file" yaml:"training_file" validate:"required"` // The ID of an uploaded file that contains training data.

See [upload file](https://platform.openai.com/docs/api-reference/files/create) for how to upload a file.

Your dataset must be formatted as a JSONL file. Additionally, you must upload your file with the purpose `fine-tune`.

The contents of the file should differ depending on if the model uses the [chat](https://platform.openai.com/docs/api-reference/fine-tuning/chat-input), [completions](https://platform.openai.com/docs/api-reference/fine-tuning/completions-input) format, or if the fine-tuning method uses the [preference](https://platform.openai.com/docs/api-reference/fine-tuning/preference-input) format.

See the [fine-tuning guide](https://platform.openai.com/docs/guides/model-optimization) for more details.

	ValidationFile  *string            `json:"validation_file" yaml:"validation_file"` // The ID of an uploaded file that contains validation data.

If you provide this file, the data is used to generate validation
metrics periodically during fine-tuning. These metrics can be viewed in
the fine-tuning results file.
The same data should not be present in both train and validation files.

Your dataset must be formatted as a JSONL file. You must upload your file with the purpose `fine-tune`.

See the [fine-tuning guide](https://platform.openai.com/docs/guides/model-optimization) for more details.

}
