// Code generated by schema2code at 2026-02-23 15:57:41. DO NOT EDIT.

package schema


type CodeInterpreter struct {
	FileIds []string `json:"file_ids" yaml:"file_ids" validate:"default=[]"` // A list of [file](https://platform.openai.com/docs/api-reference/files) IDs made available to the `code_interpreter` tool. There can be a maximum of 20 files associated with the tool.

}

// AutoChunkingStrategyType Always `auto`.
type AutoChunkingStrategyType string

const (
	AutoChunkingStrategyTypeAuto AutoChunkingStrategyType = "auto"
)
// AutoChunkingStrategy The default strategy. This strategy currently uses a `max_chunk_size_tokens` of `800` and `chunk_overlap_tokens` of `400`.
type AutoChunkingStrategy struct {
	Type AutoChunkingStrategyType `json:"type" yaml:"type" validate:"required"` // Always `auto`.
}

type Static struct {
	ChunkOverlapTokens int `json:"chunk_overlap_tokens" yaml:"chunk_overlap_tokens" validate:"required"` // The number of tokens that overlap between chunks. The default value is `400`.

Note that the overlap must not exceed half of `max_chunk_size_tokens`.

	MaxChunkSizeTokens int `json:"max_chunk_size_tokens" yaml:"max_chunk_size_tokens" validate:"min=100,max=4096,required"` // The maximum number of tokens in each chunk. The default value is `800`. The minimum value is `100` and the maximum value is `4096`.
}

// StaticChunkingStrategyType Always `static`.
type StaticChunkingStrategyType string

const (
	StaticChunkingStrategyTypeStatic StaticChunkingStrategyType = "static"
)
type StaticChunkingStrategy struct {
	Static Static `json:"static" yaml:"static" validate:"required"`
	Type   StaticChunkingStrategyType `json:"type" yaml:"type" validate:"required"` // Always `static`.
}

type VectorStoresItem struct {
	ChunkingStrategy interface{} `json:"chunking_strategy" yaml:"chunking_strategy"` // The chunking strategy used to chunk the file(s). If not set, will use the `auto` strategy.
	FileIds          []string    `json:"file_ids" yaml:"file_ids"` // A list of [file](https://platform.openai.com/docs/api-reference/files) IDs to add to the vector store. There can be a maximum of 10000 files in a vector store.

	Metadata         *Metadata   `json:"metadata" yaml:"metadata"`
}

type FileSearch struct {
	VectorStoreIds []string           `json:"vector_store_ids" yaml:"vector_store_ids"` // The [vector store](https://platform.openai.com/docs/api-reference/vector-stores/object) attached to this thread. There can be a maximum of 1 vector store attached to the thread.

	VectorStores   []VectorStoresitem `json:"vector_stores" yaml:"vector_stores"` // A helper to create a [vector store](https://platform.openai.com/docs/api-reference/vector-stores/object) with file_ids and attach it to this thread. There can be a maximum of 1 vector store attached to the thread.

}

// ToolResources A set of resources that are made available to the assistant's tools in this thread. The resources are specific to the type of tool. For example, the `code_interpreter` tool requires a list of file IDs, while the `file_search` tool requires a list of vector store IDs.

type ToolResources struct {
	CodeInterpreter *CodeInterpreter `json:"code_interpreter" yaml:"code_interpreter"`
	FileSearch      interface{}     `json:"file_search" yaml:"file_search"`
}

// CreateThreadRequest Options to create a new thread. If no thread is provided when running a
request, an empty thread will be created.

type CreateThreadRequest struct {
	Messages      []CreateMessageRequest `json:"messages" yaml:"messages"` // A list of [messages](https://platform.openai.com/docs/api-reference/messages) to start the thread with.
	Metadata      *Metadata              `json:"metadata" yaml:"metadata"`
	ToolResources interface{}            `json:"tool_resources" yaml:"tool_resources"`
}
