// Code generated by schema2code at 2026-02-23 15:57:44. DO NOT EDIT.

package schema


// DoubleClickActionType Specifies the event type. For a double click action, this property is always set to `double_click`.
type DoubleClickActionType string

const (
	DoubleClickActionTypeDoubleClick DoubleClickActionType = "double_click"
)
// DoubleClickAction A double click action.
type DoubleClickAction struct {
	Type DoubleClickActionType `json:"type" yaml:"type" validate:"default="double_click",required"` // Specifies the event type. For a double click action, this property is always set to `double_click`.
	X    int    `json:"x" yaml:"x" validate:"required"` // The x-coordinate where the double click occurred.
	Y    int    `json:"y" yaml:"y" validate:"required"` // The y-coordinate where the double click occurred.
}
