// Code generated by schema2code at 2026-02-23 15:58:52. DO NOT EDIT.

package schema

import (
	"time"
)

// DynamicTool Schema for DynamicTool object
type DynamicTool struct {
	ID           *int                   `json:"id" yaml:"id"` // The unique identifier for the tool
	UserID       interface{}            `json:"user_id" yaml:"user_id" validate:"required"` // The unique identifier for the user
	Name         string                 `json:"name" yaml:"name" validate:"required"` // The name of the tool
	Description  string                 `json:"description" yaml:"description" validate:"required"` // Description of what the tool does
	Embedding    []float32              `json:"embedding" yaml:"embedding"` // The tool's embedding vector
	Code         string                 `json:"code" yaml:"code" validate:"required"` // The tool's implementation code
	FunctionName string                 `json:"function_name" yaml:"function_name" validate:"required"` // The name of the function to be called
	Parameters   map[string]interface{} `json:"parameters" yaml:"parameters"` // Parameters for the tool with any values
	CreatedAt    *time.Time             `json:"created_at" yaml:"created_at"` // The timestamp when the tool was created
	UpdatedAt    *time.Time             `json:"updated_at" yaml:"updated_at"` // The timestamp when the tool was last updated
}
