// Code generated by schema2code at 2026-02-23 15:57:45. DO NOT EDIT.

package schema


type Error struct {
	Code    interface{} `json:"code" yaml:"code" validate:"required"`
	Message string      `json:"message" yaml:"message" validate:"required"`
	Param   interface{} `json:"param" yaml:"param" validate:"required"`
	Type    string      `json:"type" yaml:"type" validate:"required"`
}
