// Code generated by schema2code at 2026-02-23 15:57:51. DO NOT EDIT.

package schema


// FunctionShellCallOutputExitOutcomeParamType The outcome type. Always `exit`.
type FunctionShellCallOutputExitOutcomeParamType string

const (
	FunctionShellCallOutputExitOutcomeParamTypeExit FunctionShellCallOutputExitOutcomeParamType = "exit"
)
// FunctionShellCallOutputExitOutcomeParam Indicates that the shell commands finished and returned an exit code.
type FunctionShellCallOutputExitOutcomeParam struct {
	ExitCode int    `json:"exit_code" yaml:"exit_code" validate:"required"` // The exit code returned by the shell process.
	Type     FunctionShellCallOutputExitOutcomeParamType `json:"type" yaml:"type" validate:"default="exit",required"` // The outcome type. Always `exit`.
}
