// Code generated by schema2code at 2026-02-23 15:57:54. DO NOT EDIT.

package schema




// ImageEditCompletedEventBackground The background setting for the edited image.

type ImageEditCompletedEventBackground string

const (
	ImageEditCompletedEventBackgroundTransparent ImageEditCompletedEventBackground = "transparent"
	ImageEditCompletedEventBackgroundOpaque ImageEditCompletedEventBackground = "opaque"
	ImageEditCompletedEventBackgroundAuto ImageEditCompletedEventBackground = "auto"
)
// ImageEditCompletedEventOutputFormat The output format for the edited image.

type ImageEditCompletedEventOutputFormat string

const (
	ImageEditCompletedEventOutputFormatPng ImageEditCompletedEventOutputFormat = "png"
	ImageEditCompletedEventOutputFormatWebp ImageEditCompletedEventOutputFormat = "webp"
	ImageEditCompletedEventOutputFormatJpeg ImageEditCompletedEventOutputFormat = "jpeg"
)
// ImageEditCompletedEventQuality The quality setting for the edited image.

type ImageEditCompletedEventQuality string

const (
	ImageEditCompletedEventQualityLow ImageEditCompletedEventQuality = "low"
	ImageEditCompletedEventQualityMedium ImageEditCompletedEventQuality = "medium"
	ImageEditCompletedEventQualityHigh ImageEditCompletedEventQuality = "high"
	ImageEditCompletedEventQualityAuto ImageEditCompletedEventQuality = "auto"
)
// ImageEditCompletedEventSize The size of the edited image.

type ImageEditCompletedEventSize string

const (
	ImageEditCompletedEventSize1024x1024 ImageEditCompletedEventSize = "1024x1024"
	ImageEditCompletedEventSize1024x1536 ImageEditCompletedEventSize = "1024x1536"
	ImageEditCompletedEventSize1536x1024 ImageEditCompletedEventSize = "1536x1024"
	ImageEditCompletedEventSizeAuto ImageEditCompletedEventSize = "auto"
)
// ImageEditCompletedEventType The type of the event. Always `image_edit.completed`.

type ImageEditCompletedEventType string

const (
	ImageEditCompletedEventTypeImageEditCompleted ImageEditCompletedEventType = "image_edit.completed"
)
// ImageEditCompletedEvent Emitted when image editing has completed and the final image is available.

type ImageEditCompletedEvent struct {
	B64JSON      string      `json:"b64_json" yaml:"b64_json" validate:"required"` // Base64-encoded final edited image data, suitable for rendering as an image.

	Background   ImageEditCompletedEventBackground `json:"background" yaml:"background" validate:"required"` // The background setting for the edited image.

	CreatedAt    int         `json:"created_at" yaml:"created_at" validate:"required"` // The Unix timestamp when the event was created.

	OutputFormat ImageEditCompletedEventOutputFormat `json:"output_format" yaml:"output_format" validate:"required"` // The output format for the edited image.

	Quality      ImageEditCompletedEventQuality `json:"quality" yaml:"quality" validate:"required"` // The quality setting for the edited image.

	Size         ImageEditCompletedEventSize `json:"size" yaml:"size" validate:"required"` // The size of the edited image.

	Type         ImageEditCompletedEventType `json:"type" yaml:"type" validate:"required"` // The type of the event. Always `image_edit.completed`.

	Usage        ImagesUsage `json:"usage" yaml:"usage" validate:"required"`
}
