// Code generated by schema2code at 2026-02-23 15:57:55. DO NOT EDIT.

package schema



// InputTokensDetails The input tokens detailed information for the image generation.
type InputTokensDetails struct {
	ImageTokens int `json:"image_tokens" yaml:"image_tokens" validate:"required"` // The number of image tokens in the input prompt.
	TextTokens  int `json:"text_tokens" yaml:"text_tokens" validate:"required"` // The number of text tokens in the input prompt.
}

type ImageGenStreamEvent struct {
}
