// Code generated by schema2code at 2026-02-23 15:57:20. DO NOT EDIT.

package schema



// InferenceServiceConfig Inference services configuration
type InferenceServiceConfig struct {
	Ollama          InferenceService `json:"ollama" yaml:"ollama" validate:"required"`
	StableDiffusion InferenceService `json:"stable_diffusion" yaml:"stable_diffusion" validate:"required"`
	Host            string           `json:"host" yaml:"host" validate:"required"` // Host for the inference service
	Port            int              `json:"port" yaml:"port" validate:"required"` // Port for the inference service
}
