// Code generated by schema2code at 2026-02-23 15:57:56. DO NOT EDIT.

package schema


// InputImageContentParamAutoParamType The type of the input item. Always `input_image`.
type InputImageContentParamAutoParamType string

const (
	InputImageContentParamAutoParamTypeInputImage InputImageContentParamAutoParamType = "input_image"
)
// InputImageContentParamAutoParam An image input to the model. Learn about [image inputs](https://platform.openai.com/docs/guides/vision)
type InputImageContentParamAutoParam struct {
	Detail   interface{} `json:"detail" yaml:"detail"`
	FileID   interface{} `json:"file_id" yaml:"file_id"`
	ImageURL interface{} `json:"image_url" yaml:"image_url"`
	Type     InputImageContentParamAutoParamType `json:"type" yaml:"type" validate:"default="input_image",required"` // The type of the input item. Always `input_image`.
}
