// Code generated by schema2code at 2026-01-24 15:16:52. DO NOT EDIT.

package schema


// LangGraphState Strongly typed state for LangGraph workflows.
type LangGraphState struct {
	Messages            []LangChainMessage     `json:"messages" yaml:"messages" validate:"required"` // Sequence of messages
	UserInput           string                 `json:"user_input" yaml:"user_input" validate:"required"` // Latest user input
	ErrorCount          int                    `json:"error_count" yaml:"error_count" validate:"default=0,required"` // Number of errors encountered during workflow execution
	MaxIterations       int                    `json:"max_iterations" yaml:"max_iterations" validate:"default=10,required"` // Maximum number of iterations allowed in the workflow
	CurrentIteration    int                    `json:"current_iteration" yaml:"current_iteration" validate:"default=0,required"` // Current iteration count in the workflow execution
	ToolsUsed           []string               `json:"tools_used" yaml:"tools_used" validate:"default=[],required"` // List of tools or functions that have been used in the workflow
	IntermediateResults map[string]interface{} `json:"intermediate_results" yaml:"intermediate_results" validate:"default={},required"` // Storage for intermediate computation results during workflow execution
}
