// Code generated by schema2code at 2026-02-23 15:58:06. DO NOT EDIT.

package schema


type LocalShellCallStatus string

const (
	LocalShellCallStatusInProgress LocalShellCallStatus = "in_progress"
	LocalShellCallStatusCompleted LocalShellCallStatus = "completed"
	LocalShellCallStatusIncomplete LocalShellCallStatus = "incomplete"
)