// Code generated by schema2code at 2026-02-23 15:58:01. DO NOT EDIT.

package schema


// MCPApprovalResponseResourceType The type of the item. Always `mcp_approval_response`.

type MCPApprovalResponseResourceType string

const (
	MCPApprovalResponseResourceTypeMcpApprovalResponse MCPApprovalResponseResourceType = "mcp_approval_response"
)
// MCPApprovalResponseResource A response to an MCP approval request.

type MCPApprovalResponseResource struct {
	ApprovalRequestID string      `json:"approval_request_id" yaml:"approval_request_id" validate:"required"` // The ID of the approval request being answered.

	Approve           bool        `json:"approve" yaml:"approve" validate:"required"` // Whether the request was approved.

	ID                string      `json:"id" yaml:"id" validate:"required"` // The unique ID of the approval response

	Reason            interface{} `json:"reason" yaml:"reason"`
	Type              MCPApprovalResponseResourceType `json:"type" yaml:"type" validate:"required"` // The type of the item. Always `mcp_approval_response`.

}
