// Code generated by schema2code at 2026-01-24 15:16:53. DO NOT EDIT.

package schema


// MemorySource Source type for a memory
type MemorySource string

const (
	MemorySourceSummary MemorySource = "summary" // Memory type for conversation summaries
	MemorySourceMessage MemorySource = "message" // Memory type for conversation messages
	MemorySourceSearch MemorySource = "search" // Memory type for search topic syntheses
)