// Code generated by schema2code at 2025-10-27 18:24:53. DO NOT EDIT.

package schema


// MemoryConfig Memory retrieval settings
type MemoryConfig struct {
	Enabled                 bool    `json:"enabled" yaml:"enabled" validate:"required"` // Whether memory retrieval is enabled
	Limit                   int     `json:"limit" yaml:"limit" validate:"required"` // Retrieval limit
	EnableCrossUser         bool    `json:"enable_cross_user" yaml:"enable_cross_user" validate:"required"` // Enable cross-user retrieval
	EnableCrossConversation bool    `json:"enable_cross_conversation" yaml:"enable_cross_conversation" validate:"required"` // Enable cross-conversation retrieval
	SimilarityThreshold     float32 `json:"similarity_threshold" yaml:"similarity_threshold" validate:"required"` // Similarity threshold
	AlwaysRetrieve          bool    `json:"always_retrieve" yaml:"always_retrieve" validate:"required"` // Always retrieve
}
