// Code generated by schema2code at 2026-02-23 15:58:04. DO NOT EDIT.

package schema


// ModerationTextInputType Always `text`.
type ModerationTextInputType string

const (
	ModerationTextInputTypeText ModerationTextInputType = "text"
)
// ModerationTextInput An object describing text to classify.
type ModerationTextInput struct {
	Text string `json:"text" yaml:"text" validate:"required"` // A string of text to classify.
	Type ModerationTextInputType `json:"type" yaml:"type" validate:"required"` // Always `text`.
}
