// Code generated by schema2code at 2025-08-26 22:17:38. DO NOT EDIT.

package schema


// ModelTask ModelTask represents the task associated with a machine learning model
type ModelTask string

const (
	ModelTaskTextToText ModelTask = "TextToText"
	ModelTaskTextToImage ModelTask = "TextToImage"
	ModelTaskImageToText ModelTask = "ImageToText"
	ModelTaskImageToImage ModelTask = "ImageToImage"
	ModelTaskTextToAudio ModelTask = "TextToAudio"
	ModelTaskAudioToText ModelTask = "AudioToText"
	ModelTaskTextToVideo ModelTask = "TextToVideo"
	ModelTaskVideoToText ModelTask = "VideoToText"
	ModelTaskTextToSpeech ModelTask = "TextToSpeech"
	ModelTaskSpeechToText ModelTask = "SpeechToText"
	ModelTaskTextToEmbeddings ModelTask = "TextToEmbeddings"
	ModelTaskVisionTextToText ModelTask = "VisionTextToText"
	ModelTaskImageTextToImage ModelTask = "ImageTextToImage"
)