// Code generated by schema2code at 2026-01-24 15:16:54. DO NOT EDIT.

package schema


// ModelProvider Provider / runtime of the model (e.g., 'llama.cpp', 'hf', 'hugging face', 'openai', 'stable-diffusion.cpp', 'anthropic')
type ModelProvider string

const (
	ModelProviderLlamaCpp ModelProvider = "llama_cpp"
	ModelProviderHf ModelProvider = "hf"
	ModelProviderHuggingFace ModelProvider = "hugging_face"
	ModelProviderOpenai ModelProvider = "openai"
	ModelProviderStableDiffusionCpp ModelProvider = "stable_diffusion_cpp"
	ModelProviderAnthropic ModelProvider = "anthropic"
	ModelProviderOther ModelProvider = "other"
)