// Code generated by schema2code at 2026-01-24 15:16:55. DO NOT EDIT.

package schema


// PipelinePriority Pipeline priority levels for cache eviction and resource management
type PipelinePriority int

const (
	PipelinePriority1 PipelinePriority = 1
	PipelinePriority5 PipelinePriority = 5
	PipelinePriority10 PipelinePriority = 10
	PipelinePriority20 PipelinePriority = 20
)