// Code generated by schema2code at 2026-02-23 15:58:07. DO NOT EDIT.

package schema


// ProjectGroupObject Always `project.group`.
type ProjectGroupObject string

const (
	ProjectGroupObjectProjectGroup ProjectGroupObject = "project.group"
)
// ProjectGroup Details about a group's membership in a project.
type ProjectGroup struct {
	CreatedAt int    `json:"created_at" yaml:"created_at" validate:"required"` // Unix timestamp (in seconds) when the group was granted project access.
	GroupID   string `json:"group_id" yaml:"group_id" validate:"required"` // Identifier of the group that has access to the project.
	GroupName string `json:"group_name" yaml:"group_name" validate:"required"` // Display name of the group.
	Object    ProjectGroupObject `json:"object" yaml:"object" validate:"required"` // Always `project.group`.
	ProjectID string `json:"project_id" yaml:"project_id" validate:"required"` // Identifier of the project.
}
