// Code generated by schema2code at 2026-02-23 15:58:08. DO NOT EDIT.

package schema


// ProjectServiceAccountObject The object type, which is always `organization.project.service_account`
type ProjectServiceAccountObject string

const (
	ProjectServiceAccountObjectOrganizationProjectServiceAccount ProjectServiceAccountObject = "organization.project.service_account"
)
// ProjectServiceAccountRole `owner` or `member`
type ProjectServiceAccountRole string

const (
	ProjectServiceAccountRoleOwner ProjectServiceAccountRole = "owner"
	ProjectServiceAccountRoleMember ProjectServiceAccountRole = "member"
)
// ProjectServiceAccount Represents an individual service account in a project.
type ProjectServiceAccount struct {
	CreatedAt int    `json:"created_at" yaml:"created_at" validate:"required"` // The Unix timestamp (in seconds) of when the service account was created
	ID        string `json:"id" yaml:"id" validate:"required"` // The identifier, which can be referenced in API endpoints
	Name      string `json:"name" yaml:"name" validate:"required"` // The name of the service account
	Object    ProjectServiceAccountObject `json:"object" yaml:"object" validate:"required"` // The object type, which is always `organization.project.service_account`
	Role      ProjectServiceAccountRole `json:"role" yaml:"role" validate:"required"` // `owner` or `member`
}
