// Code generated by schema2code at 2026-02-23 15:58:18. DO NOT EDIT.

package schema


type RealtimeMCPHTTPErrorType string

const (
	RealtimeMCPHTTPErrorTypeHttpError RealtimeMCPHTTPErrorType = "http_error"
)
type RealtimeMCPHTTPError struct {
	Code    int    `json:"code" yaml:"code" validate:"required"`
	Message string `json:"message" yaml:"message" validate:"required"`
	Type    RealtimeMCPHTTPErrorType `json:"type" yaml:"type" validate:"required"`
}
