// Code generated by schema2code at 2026-02-23 15:58:18. DO NOT EDIT.

package schema


// RealtimeMCPApprovalRequestType The type of the item. Always `mcp_approval_request`.
type RealtimeMCPApprovalRequestType string

const (
	RealtimeMCPApprovalRequestTypeMcpApprovalRequest RealtimeMCPApprovalRequestType = "mcp_approval_request"
)
// RealtimeMCPApprovalRequest A Realtime item requesting human approval of a tool invocation.

type RealtimeMCPApprovalRequest struct {
	Arguments   string `json:"arguments" yaml:"arguments" validate:"required"` // A JSON string of arguments for the tool.
	ID          string `json:"id" yaml:"id" validate:"required"` // The unique ID of the approval request.
	Name        string `json:"name" yaml:"name" validate:"required"` // The name of the tool to run.
	ServerLabel string `json:"server_label" yaml:"server_label" validate:"required"` // The label of the MCP server making the request.
	Type        RealtimeMCPApprovalRequestType `json:"type" yaml:"type" validate:"required"` // The type of the item. Always `mcp_approval_request`.
}
