// Code generated by schema2code at 2026-02-23 15:58:24. DO NOT EDIT.

package schema


// InputAudioNoiseReduction Configuration for input audio noise reduction. This can be set to `null` to turn off.
Noise reduction filters audio added to the input audio buffer before it is sent to VAD and the model.
Filtering the audio can improve VAD and turn detection accuracy (reducing false positives) and model performance by improving perception of the input audio.

type InputAudioNoiseReduction struct {
	Type *NoiseReductionType `json:"type" yaml:"type"`
}

// RealtimeSessionInputAudioFormat The format of input audio. Options are `pcm16`, `g711_ulaw`, or `g711_alaw`.
For `pcm16`, input audio must be 16-bit PCM at a 24kHz sample rate,
single channel (mono), and little-endian byte order.

type RealtimeSessionInputAudioFormat string

const (
	RealtimeSessionInputAudioFormatPcm16 RealtimeSessionInputAudioFormat = "pcm16"
	RealtimeSessionInputAudioFormatG711Ulaw RealtimeSessionInputAudioFormat = "g711_ulaw"
	RealtimeSessionInputAudioFormatG711Alaw RealtimeSessionInputAudioFormat = "g711_alaw"
)
// RealtimeSessionObject The object type. Always `realtime.session`.
type RealtimeSessionObject string

const (
	RealtimeSessionObjectRealtimeSession RealtimeSessionObject = "realtime.session"
)
// RealtimeSessionOutputAudioFormat The format of output audio. Options are `pcm16`, `g711_ulaw`, or `g711_alaw`.
For `pcm16`, output audio is sampled at a rate of 24kHz.

type RealtimeSessionOutputAudioFormat string

const (
	RealtimeSessionOutputAudioFormatPcm16 RealtimeSessionOutputAudioFormat = "pcm16"
	RealtimeSessionOutputAudioFormatG711Ulaw RealtimeSessionOutputAudioFormat = "g711_ulaw"
	RealtimeSessionOutputAudioFormatG711Alaw RealtimeSessionOutputAudioFormat = "g711_alaw"
)
// RealtimeSession Realtime session object for the beta interface.
type RealtimeSession struct {
	ExpiresAt                *int                     `json:"expires_at" yaml:"expires_at"` // Expiration timestamp for the session, in seconds since epoch.
	ID                       *string                  `json:"id" yaml:"id"` // Unique identifier for the session that looks like `sess_1234567890abcdef`.

	Include                  interface{}              `json:"include" yaml:"include"`
	InputAudioFormat         *RealtimeSessionInputAudioFormat `json:"input_audio_format" yaml:"input_audio_format" validate:"default="pcm16""` // The format of input audio. Options are `pcm16`, `g711_ulaw`, or `g711_alaw`.
For `pcm16`, input audio must be 16-bit PCM at a 24kHz sample rate,
single channel (mono), and little-endian byte order.

	InputAudioNoiseReduction *InputAudioNoiseReduction `json:"input_audio_noise_reduction" yaml:"input_audio_noise_reduction"` // Configuration for input audio noise reduction. This can be set to `null` to turn off.
Noise reduction filters audio added to the input audio buffer before it is sent to VAD and the model.
Filtering the audio can improve VAD and turn detection accuracy (reducing false positives) and model performance by improving perception of the input audio.

	InputAudioTranscription  interface{}              `json:"input_audio_transcription" yaml:"input_audio_transcription"`
	Instructions             *string                  `json:"instructions" yaml:"instructions"` // The default system instructions (i.e. system message) prepended to model
calls. This field allows the client to guide the model on desired
responses. The model can be instructed on response content and format,
(e.g. "be extremely succinct", "act friendly", "here are examples of good
responses") and on audio behavior (e.g. "talk quickly", "inject emotion
into your voice", "laugh frequently"). The instructions are not
guaranteed to be followed by the model, but they provide guidance to the
model on the desired behavior.


Note that the server sets default instructions which will be used if this
field is not set and are visible in the `session.created` event at the
start of the session.

	MaxResponseOutputTokens  interface{}              `json:"max_response_output_tokens" yaml:"max_response_output_tokens"` // Maximum number of output tokens for a single assistant response,
inclusive of tool calls. Provide an integer between 1 and 4096 to
limit output tokens, or `inf` for the maximum available tokens for a
given model. Defaults to `inf`.

	Modalities               *string                  `json:"modalities" yaml:"modalities"` // The set of modalities the model can respond with. To disable audio,
set this to ["text"].

	Model                    interface{}              `json:"model" yaml:"model"` // The Realtime model used for this session.

	Object                   *RealtimeSessionObject   `json:"object" yaml:"object"` // The object type. Always `realtime.session`.
	OutputAudioFormat        *RealtimeSessionOutputAudioFormat `json:"output_audio_format" yaml:"output_audio_format" validate:"default="pcm16""` // The format of output audio. Options are `pcm16`, `g711_ulaw`, or `g711_alaw`.
For `pcm16`, output audio is sampled at a rate of 24kHz.

	Prompt                   interface{}              `json:"prompt" yaml:"prompt"`
	Speed                    *float32                 `json:"speed" yaml:"speed" validate:"min=0.25,max=1.5,default=1"` // The speed of the model's spoken response. 1.0 is the default speed. 0.25 is
the minimum speed. 1.5 is the maximum speed. This value can only be changed
in between model turns, not while a response is in progress.

	Temperature              *float32                 `json:"temperature" yaml:"temperature" validate:"default=0.8"` // Sampling temperature for the model, limited to [0.6, 1.2]. For audio models a temperature of 0.8 is highly recommended for best performance.

	ToolChoice               *string                  `json:"tool_choice" yaml:"tool_choice" validate:"default="auto""` // How the model chooses tools. Options are `auto`, `none`, `required`, or
specify a function.

	Tools                    []RealtimeFunctionTool   `json:"tools" yaml:"tools"` // Tools (functions) available to the model.
	Tracing                  interface{}              `json:"tracing" yaml:"tracing"`
	TurnDetection            *RealtimeTurnDetection   `json:"turn_detection" yaml:"turn_detection"`
	Voice                    *VoiceIdsShared          `json:"voice" yaml:"voice"` // The voice the model uses to respond. Voice cannot be changed during the
session once the model has responded with audio at least once. Current
voice options are `alloy`, `ash`, `ballad`, `coral`, `echo`, `sage`,
`shimmer`, and `verse`.

}
