// Code generated by schema2code at 2026-02-23 15:58:10. DO NOT EDIT.

package schema


// RealtimeBetaServerEventConversationItemCreated Returned when a conversation item is created. There are several scenarios that produce this event:
  - The server is generating a Response, which if successful will produce
    either one or two Items, which will be of type `message`
    (role `assistant`) or type `function_call`.
  - The input audio buffer has been committed, either by the client or the
    server (in `server_vad` mode). The server will take the content of the
    input audio buffer and add it to a new user message Item.
  - The client has sent a `conversation.item.create` event to add a new Item
    to the Conversation.

type RealtimeBetaServerEventConversationItemCreated struct {
	EventID        string                   `json:"event_id" yaml:"event_id" validate:"required"` // The unique ID of the server event.
	Item           RealtimeConversationItem `json:"item" yaml:"item" validate:"required"`
	PreviousItemID interface{}              `json:"previous_item_id" yaml:"previous_item_id"`
	Type           string                   `json:"type" yaml:"type" validate:"required"` // The event type, must be `conversation.item.created`.
}
