// Code generated by schema2code at 2026-02-23 15:58:13. DO NOT EDIT.

package schema


// RealtimeBetaServerEventResponseMCPCallArgumentsDelta Returned when MCP tool call arguments are updated during response generation.
type RealtimeBetaServerEventResponseMCPCallArgumentsDelta struct {
	Delta       string      `json:"delta" yaml:"delta" validate:"required"` // The JSON-encoded arguments delta.
	EventID     string      `json:"event_id" yaml:"event_id" validate:"required"` // The unique ID of the server event.
	ItemID      string      `json:"item_id" yaml:"item_id" validate:"required"` // The ID of the MCP tool call item.
	Obfuscation interface{} `json:"obfuscation" yaml:"obfuscation"`
	OutputIndex int         `json:"output_index" yaml:"output_index" validate:"required"` // The index of the output item in the response.
	ResponseID  string      `json:"response_id" yaml:"response_id" validate:"required"` // The ID of the response.
	Type        string      `json:"type" yaml:"type" validate:"required"` // The event type, must be `response.mcp_call_arguments.delta`.
}
