// Code generated by schema2code at 2026-02-23 15:58:14. DO NOT EDIT.

package schema



// InputAudioNoiseReduction Configuration for input audio noise reduction. This can be set to `null` to turn off.
Noise reduction filters audio added to the input audio buffer before it is sent to VAD and the model.
Filtering the audio can improve VAD and turn detection accuracy (reducing false positives) and model performance by improving perception of the input audio.

type InputAudioNoiseReduction struct {
	Type *NoiseReductionType `json:"type" yaml:"type"`
}

// RealtimeBetaServerEventSessionUpdated Returned when a session is updated with a `session.update` event, unless
there is an error.

type RealtimeBetaServerEventSessionUpdated struct {
	EventID string          `json:"event_id" yaml:"event_id" validate:"required"` // The unique ID of the server event.
	Session RealtimeSession `json:"session" yaml:"session" validate:"required"`
	Type    string          `json:"type" yaml:"type" validate:"required"` // The event type, must be `session.updated`.
}
