// Code generated by schema2code at 2026-02-23 15:58:10. DO NOT EDIT.

package schema


// ToolsItemType The type of the tool, i.e. `function`.
type ToolsItemType string

const (
	ToolsItemTypeFunction ToolsItemType = "function"
)
type ToolsItem struct {
	Description *string                `json:"description" yaml:"description"` // The description of the function, including guidance on when and how 
to call it, and guidance about what to tell the user when calling 
(if anything).

	Name        *string                `json:"name" yaml:"name"` // The name of the function.
	Parameters  map[string]interface{} `json:"parameters" yaml:"parameters"` // Parameters of the function in JSON Schema.
	Type        *ToolsItemType         `json:"type" yaml:"type"` // The type of the tool, i.e. `function`.
}

// RealtimeBetaResponseCreateParamsOutputAudioFormat The format of output audio. Options are `pcm16`, `g711_ulaw`, or `g711_alaw`.

type RealtimeBetaResponseCreateParamsOutputAudioFormat string

const (
	RealtimeBetaResponseCreateParamsOutputAudioFormatPcm16 RealtimeBetaResponseCreateParamsOutputAudioFormat = "pcm16"
	RealtimeBetaResponseCreateParamsOutputAudioFormatG711Ulaw RealtimeBetaResponseCreateParamsOutputAudioFormat = "g711_ulaw"
	RealtimeBetaResponseCreateParamsOutputAudioFormatG711Alaw RealtimeBetaResponseCreateParamsOutputAudioFormat = "g711_alaw"
)
// RealtimeBetaResponseCreateParams Create a new Realtime response with these parameters
type RealtimeBetaResponseCreateParams struct {
	Conversation      interface{}                `json:"conversation" yaml:"conversation"` // Controls which conversation the response is added to. Currently supports
`auto` and `none`, with `auto` as the default value. The `auto` value
means that the contents of the response will be added to the default
conversation. Set this to `none` to create an out-of-band response which 
will not add items to default conversation.

	Input             []RealtimeConversationItem `json:"input" yaml:"input"` // Input items to include in the prompt for the model. Using this field
creates a new context for this Response instead of using the default
conversation. An empty array `[]` will clear the context for this Response.
Note that this can include references to items from the default conversation.

	Instructions      *string                    `json:"instructions" yaml:"instructions"` // The default system instructions (i.e. system message) prepended to model 
calls. This field allows the client to guide the model on desired 
responses. The model can be instructed on response content and format, 
(e.g. "be extremely succinct", "act friendly", "here are examples of good 
responses") and on audio behavior (e.g. "talk quickly", "inject emotion 
into your voice", "laugh frequently"). The instructions are not guaranteed 
to be followed by the model, but they provide guidance to the model on the 
desired behavior.

Note that the server sets default instructions which will be used if this 
field is not set and are visible in the `session.created` event at the 
start of the session.

	MaxOutputTokens   interface{}                `json:"max_output_tokens" yaml:"max_output_tokens"` // Maximum number of output tokens for a single assistant response,
inclusive of tool calls. Provide an integer between 1 and 4096 to
limit output tokens, or `inf` for the maximum available tokens for a
given model. Defaults to `inf`.

	Metadata          *Metadata                  `json:"metadata" yaml:"metadata"`
	Modalities        []string                   `json:"modalities" yaml:"modalities"` // The set of modalities the model can respond with. To disable audio,
set this to ["text"].

	OutputAudioFormat *RealtimeBetaResponseCreateParamsOutputAudioFormat `json:"output_audio_format" yaml:"output_audio_format"` // The format of output audio. Options are `pcm16`, `g711_ulaw`, or `g711_alaw`.

	Prompt            *Prompt                    `json:"prompt" yaml:"prompt"`
	Temperature       *float32                   `json:"temperature" yaml:"temperature"` // Sampling temperature for the model, limited to [0.6, 1.2]. Defaults to 0.8.

	ToolChoice        interface{}                `json:"tool_choice" yaml:"tool_choice" validate:"default="auto""` // How the model chooses tools. Provide one of the string modes or force a specific
function/MCP tool.

	Tools             []Toolsitem                `json:"tools" yaml:"tools"` // Tools (functions) available to the model.
	Voice             *VoiceIdsShared            `json:"voice" yaml:"voice"` // The voice the model uses to respond. Supported built-in voices are `alloy`, `ash`, `ballad`, `coral`, `echo`, `sage`, `shimmer`, `verse`, `marin`, and `cedar`. Voice cannot be changed during the session once the model has responded with audio at least once.
}
