// Code generated by schema2code at 2026-02-23 15:58:12. DO NOT EDIT.

package schema


// RealtimeBetaServerEventResponseAudioTranscriptDone Returned when the model-generated transcription of audio output is done
streaming. Also emitted when a Response is interrupted, incomplete, or
cancelled.

type RealtimeBetaServerEventResponseAudioTranscriptDone struct {
	ContentIndex int    `json:"content_index" yaml:"content_index" validate:"required"` // The index of the content part in the item's content array.
	EventID      string `json:"event_id" yaml:"event_id" validate:"required"` // The unique ID of the server event.
	ItemID       string `json:"item_id" yaml:"item_id" validate:"required"` // The ID of the item.
	OutputIndex  int    `json:"output_index" yaml:"output_index" validate:"required"` // The index of the output item in the response.
	ResponseID   string `json:"response_id" yaml:"response_id" validate:"required"` // The ID of the response.
	Transcript   string `json:"transcript" yaml:"transcript" validate:"required"` // The final transcript of the audio.
	Type         string `json:"type" yaml:"type" validate:"required"` // The event type, must be `response.output_audio_transcript.done`.
}
