// Code generated by schema2code at 2026-02-23 15:58:23. DO NOT EDIT.

package schema


// RealtimeServerEventInputAudioBufferSpeechStopped Returned in `server_vad` mode when the server detects the end of speech in 
the audio buffer. The server will also send an `conversation.item.created` 
event with the user message item that is created from the audio buffer.

type RealtimeServerEventInputAudioBufferSpeechStopped struct {
	AudioEndMs int    `json:"audio_end_ms" yaml:"audio_end_ms" validate:"required"` // Milliseconds since the session started when speech stopped. This will 
correspond to the end of audio sent to the model, and thus includes the 
`min_silence_duration_ms` configured in the Session.

	EventID    string `json:"event_id" yaml:"event_id" validate:"required"` // The unique ID of the server event.
	ItemID     string `json:"item_id" yaml:"item_id" validate:"required"` // The ID of the user message item that will be created.
	Type       string `json:"type" yaml:"type" validate:"required"` // The event type, must be `input_audio_buffer.speech_stopped`.
}
