// Code generated by schema2code at 2026-02-23 15:58:14. DO NOT EDIT.

package schema



// ClientSecret Ephemeral key returned by the API. Only present when the session is
created on the server via REST API.

type ClientSecret struct {
	ExpiresAt int    `json:"expires_at" yaml:"expires_at" validate:"required"` // Timestamp for when the token expires. Currently, all tokens expire
after one minute.

	Value     string `json:"value" yaml:"value" validate:"required"` // Ephemeral key usable in client environments to authenticate connections
to the Realtime API. Use this in client-side environments rather than
a standard API token, which should only be used server-side.

}

// TurnDetection Configuration for turn detection. Can be set to `null` to turn off. Server
VAD means that the model will detect the start and end of speech based on
audio volume and respond at the end of user speech.

type TurnDetection struct {
	PrefixPaddingMs   *int    `json:"prefix_padding_ms" yaml:"prefix_padding_ms"` // Amount of audio to include before the VAD detected speech (in
milliseconds). Defaults to 300ms.

	SilenceDurationMs *int    `json:"silence_duration_ms" yaml:"silence_duration_ms"` // Duration of silence to detect speech stop (in milliseconds). Defaults
to 500ms. With shorter values the model will respond more quickly,
but may jump in on short pauses from the user.

	Threshold         *float32 `json:"threshold" yaml:"threshold"` // Activation threshold for VAD (0.0 to 1.0), this defaults to 0.5. A
higher threshold will require louder audio to activate the model, and
thus might perform better in noisy environments.

	Type              *string `json:"type" yaml:"type"` // Type of turn detection, only `server_vad` is currently supported.

}

// RealtimeBetaServerEventTranscriptionSessionCreated Returned when a transcription session is created.

type RealtimeBetaServerEventTranscriptionSessionCreated struct {
	EventID string                                     `json:"event_id" yaml:"event_id" validate:"required"` // The unique ID of the server event.
	Session RealtimeTranscriptionSessionCreateResponse `json:"session" yaml:"session" validate:"required"`
	Type    string                                     `json:"type" yaml:"type" validate:"required"` // The event type, must be `transcription_session.created`.
}
