// Code generated by schema2code at 2025-09-18 14:55:48. DO NOT EDIT.

package schema



// ResearchPlan Plan for executing a research task
type ResearchPlan struct {
	MainIntent   string             `json:"main_intent" yaml:"main_intent" validate:"required"` // Main intent or goal of the research
	SubQuestions []ResearchQuestion `json:"sub_questions" yaml:"sub_questions" validate:"required"` // Sub-questions to investigate as part of the research
	RawPlan      *string            `json:"raw_plan" yaml:"raw_plan"` // Original plan text from LLM
}
