// Code generated by schema2code at 2025-09-18 14:55:48. DO NOT EDIT.

package schema


// ResearchQuestion Sub-question in a research plan
type ResearchQuestion struct {
	ID       int      `json:"id" yaml:"id" validate:"required"` // Unique identifier for the question
	Question string   `json:"question" yaml:"question" validate:"required"` // The question to investigate
	Keywords []string `json:"keywords" yaml:"keywords" validate:"required"` // Keywords relevant to the question
}
