// Code generated by schema2code at 2026-02-23 15:58:32. DO NOT EDIT.

package schema


// ResponseFailedEventType The type of the event. Always `response.failed`.

type ResponseFailedEventType string

const (
	ResponseFailedEventTypeResponseFailed ResponseFailedEventType = "response.failed"
)
// ResponseFailedEvent An event that is emitted when a response fails.

type ResponseFailedEvent struct {
	Response       Response `json:"response" yaml:"response" validate:"required"` // The response that failed.

	SequenceNumber int      `json:"sequence_number" yaml:"sequence_number" validate:"required"` // The sequence number of this event.
	Type           ResponseFailedEventType `json:"type" yaml:"type" validate:"required"` // The type of the event. Always `response.failed`.

}
