// Code generated by schema2code at 2026-02-23 15:58:38. DO NOT EDIT.

package schema


// ResponseFormatJsonSchemaSchema The schema for the response format, described as a JSON Schema object.
Learn how to build JSON schemas [here](https://json-schema.org/).

type ResponseFormatJsonSchemaSchema struct {
}
