// Code generated by schema2code at 2026-02-23 15:58:36. DO NOT EDIT.

package schema


// Function The function definition.
type Function struct {
	Arguments string `json:"arguments" yaml:"arguments" validate:"required"` // The arguments that the model expects you to pass to the function.
	Name      string `json:"name" yaml:"name" validate:"required"` // The name of the function.
}

// RunToolCallObjectType The type of tool call the output is required for. For now, this is always `function`.
type RunToolCallObjectType string

const (
	RunToolCallObjectTypeFunction RunToolCallObjectType = "function"
)
// RunToolCallObject Tool call objects
type RunToolCallObject struct {
	Function Function `json:"function" yaml:"function" validate:"required"` // The function definition.
	ID       string   `json:"id" yaml:"id" validate:"required"` // The ID of the tool call. This ID must be referenced when you submit the tool outputs in using the [Submit tool outputs to run](https://platform.openai.com/docs/api-reference/runs/submitToolOutputs) endpoint.
	Type     RunToolCallObjectType `json:"type" yaml:"type" validate:"required"` // The type of tool call the output is required for. For now, this is always `function`.
}
