// Code generated by schema2code at 2026-02-23 15:58:35. DO NOT EDIT.

package schema


// CodeInterpreter The Code Interpreter tool call definition.
type CodeInterpreter struct {
	Input   string        `json:"input" yaml:"input" validate:"required"` // The input to the Code Interpreter tool call.
	Outputs []interface{} `json:"outputs" yaml:"outputs" validate:"required"` // The outputs from the Code Interpreter tool call. Code Interpreter can output one or more items, including text (`logs`) or images (`image`). Each of these are represented by a different object type.
}

// RunStepDetailsToolCallsCodeObjectType The type of tool call. This is always going to be `code_interpreter` for this type of tool call.
type RunStepDetailsToolCallsCodeObjectType string

const (
	RunStepDetailsToolCallsCodeObjectTypeCodeInterpreter RunStepDetailsToolCallsCodeObjectType = "code_interpreter"
)
// RunStepDetailsToolCallsCodeObject Details of the Code Interpreter tool call the run step was involved in.
type RunStepDetailsToolCallsCodeObject struct {
	CodeInterpreter CodeInterpreter `json:"code_interpreter" yaml:"code_interpreter" validate:"required"` // The Code Interpreter tool call definition.
	ID              string          `json:"id" yaml:"id" validate:"required"` // The ID of the tool call.
	Type            RunStepDetailsToolCallsCodeObjectType `json:"type" yaml:"type" validate:"required"` // The type of tool call. This is always going to be `code_interpreter` for this type of tool call.
}
