// Code generated by schema2code at 2025-09-18 14:55:48. DO NOT EDIT.

package schema


// ServerConfig Server configuration
type ServerConfig struct {
	Host    string `json:"host" yaml:"host" validate:"required"` // Server host
	Port    int    `json:"port" yaml:"port" validate:"required"` // Server port
	BaseURL string `json:"base_url" yaml:"base_url" validate:"required"` // Base URL
}
