// Code generated by schema2code at 2025-08-26 22:17:40. DO NOT EDIT.

package schema

import (
	"time"
)

// Summary Summary represents a consolidated summary of messages or other summaries
type Summary struct {
	Content        string    `json:"content" yaml:"content"` // Text content of the summary
	Level          int       `json:"level" yaml:"level"` // Level of the summary in the hierarchy
	ID             int       `json:"id" yaml:"id"` // Unique identifier for the summary
	ConversationID int       `json:"conversation_id" yaml:"conversation_id"` // Id of the conversation this summary belongs to
	SourceIds      []int     `json:"source_ids" yaml:"source_ids"` // IDs of the source messages or summaries
	CreatedAt      time.Time `json:"created_at" yaml:"created_at"` // Timestamp of when the summary was created
}
