// Code generated by schema2code at 2026-02-23 15:58:39. DO NOT EDIT.

package schema


// TaskGroupTask Task entry that appears within a TaskGroup.
type TaskGroupTask struct {
	Heading interface{} `json:"heading" yaml:"heading" validate:"required"`
	Summary interface{} `json:"summary" yaml:"summary" validate:"required"`
	Type    TaskType    `json:"type" yaml:"type" validate:"required"` // Subtype for the grouped task.
}
