// Code generated by schema2code at 2026-02-23 15:58:38. DO NOT EDIT.

package schema


// TextResponseFormatJsonSchemaType The type of response format being defined. Always `json_schema`.
type TextResponseFormatJsonSchemaType string

const (
	TextResponseFormatJsonSchemaTypeJsonSchema TextResponseFormatJsonSchemaType = "json_schema"
)
// TextResponseFormatJsonSchema JSON Schema response format. Used to generate structured JSON responses.
Learn more about [Structured Outputs](https://platform.openai.com/docs/guides/structured-outputs).

type TextResponseFormatJsonSchema struct {
	Description *string                        `json:"description" yaml:"description"` // A description of what the response format is for, used by the model to
determine how to respond in the format.

	Name        string                         `json:"name" yaml:"name" validate:"required"` // The name of the response format. Must be a-z, A-Z, 0-9, or contain
underscores and dashes, with a maximum length of 64.

	Schema      ResponseFormatJsonSchemaSchema `json:"schema" yaml:"schema" validate:"required"`
	Strict      interface{}                    `json:"strict" yaml:"strict"`
	Type        TextResponseFormatJsonSchemaType `json:"type" yaml:"type" validate:"required"` // The type of response format being defined. Always `json_schema`.
}
