// Code generated by schema2code at 2026-02-23 15:58:40. DO NOT EDIT.

package schema


// TopLogProb The top log probability of a token.
type TopLogProb struct {
	Bytes   []int   `json:"bytes" yaml:"bytes" validate:"required"`
	Logprob float32 `json:"logprob" yaml:"logprob" validate:"required"`
	Token   string  `json:"token" yaml:"token" validate:"required"`
}
