// Code generated by schema2code at 2026-02-23 15:58:41. DO NOT EDIT.

package schema


// InputTokenDetails Details about the input tokens billed for this request.
type InputTokenDetails struct {
	AudioTokens *int `json:"audio_tokens" yaml:"audio_tokens"` // Number of audio tokens billed for this request.
	TextTokens  *int `json:"text_tokens" yaml:"text_tokens"` // Number of text tokens billed for this request.
}

// TranscriptTextUsageTokensType The type of the usage object. Always `tokens` for this variant.
type TranscriptTextUsageTokensType string

const (
	TranscriptTextUsageTokensTypeTokens TranscriptTextUsageTokensType = "tokens"
)
// TranscriptTextUsageTokens Usage statistics for models billed by token usage.
type TranscriptTextUsageTokens struct {
	InputTokenDetails *InputTokenDetails `json:"input_token_details" yaml:"input_token_details"` // Details about the input tokens billed for this request.
	InputTokens       int               `json:"input_tokens" yaml:"input_tokens" validate:"required"` // Number of input tokens billed for this request.
	OutputTokens      int               `json:"output_tokens" yaml:"output_tokens" validate:"required"` // Number of output tokens generated.
	TotalTokens       int               `json:"total_tokens" yaml:"total_tokens" validate:"required"` // Total number of tokens used (input + output).
	Type              TranscriptTextUsageTokensType `json:"type" yaml:"type" validate:"required"` // The type of the usage object. Always `tokens` for this variant.
}
