// Code generated by schema2code at 2026-02-23 15:58:44. DO NOT EDIT.

package schema


// UserMessageQuotedTextType Type discriminator that is always `quoted_text`.
type UserMessageQuotedTextType string

const (
	UserMessageQuotedTextTypeQuotedText UserMessageQuotedTextType = "quoted_text"
)
// UserMessageQuotedText Quoted snippet that the user referenced in their message.
type UserMessageQuotedText struct {
	Text string `json:"text" yaml:"text" validate:"required"` // Quoted text content.
	Type UserMessageQuotedTextType `json:"type" yaml:"type" validate:"default="quoted_text",required"` // Type discriminator that is always `quoted_text`.
}
