// Code generated by schema2code at 2026-02-23 15:58:46. DO NOT EDIT.

package schema


type VideoListResource struct {
	Data    []VideoResource `json:"data" yaml:"data" validate:"required"` // A list of items
	FirstID interface{}     `json:"first_id" yaml:"first_id" validate:"required"`
	HasMore bool            `json:"has_more" yaml:"has_more" validate:"required"` // Whether there are more items available.
	LastID  interface{}     `json:"last_id" yaml:"last_id" validate:"required"`
	Object  string          `json:"object" yaml:"object" validate:"default="list",required"` // The type of object returned, must be `list`.
}
