// Code generated by schema2code at 2026-02-23 15:58:46. DO NOT EDIT.

package schema


type VoiceConsentListResourceObject string

const (
	VoiceConsentListResourceObjectList VoiceConsentListResourceObject = "list"
)
type VoiceConsentListResource struct {
	Data    []VoiceConsentResource `json:"data" yaml:"data" validate:"required"`
	FirstID interface{}            `json:"first_id" yaml:"first_id"`
	HasMore bool                   `json:"has_more" yaml:"has_more" validate:"required"`
	LastID  interface{}            `json:"last_id" yaml:"last_id"`
	Object  VoiceConsentListResourceObject `json:"object" yaml:"object" validate:"required"`
}
