// Code generated by schema2code at 2026-02-23 15:58:47. DO NOT EDIT.

package schema


// WaitType Specifies the event type. For a wait action, this property is 
always set to `wait`.

type WaitType string

const (
	WaitTypeWait WaitType = "wait"
)
// Wait A wait action.

type Wait struct {
	Type WaitType `json:"type" yaml:"type" validate:"default="wait",required"` // Specifies the event type. For a wait action, this property is 
always set to `wait`.

}
