// Code generated by schema2code at 2026-02-23 15:58:49. DO NOT EDIT.

package schema


// Data Event data payload.

type Data struct {
	ID string `json:"id" yaml:"id" validate:"required"` // The unique ID of the model response.

}

// WebhookResponseFailedObject The object of the event. Always `event`.

type WebhookResponseFailedObject string

const (
	WebhookResponseFailedObjectEvent WebhookResponseFailedObject = "event"
)
// WebhookResponseFailedType The type of the event. Always `response.failed`.

type WebhookResponseFailedType string

const (
	WebhookResponseFailedTypeResponseFailed WebhookResponseFailedType = "response.failed"
)
// WebhookResponseFailed Sent when a background response has failed.

type WebhookResponseFailed struct {
	CreatedAt int    `json:"created_at" yaml:"created_at" validate:"required"` // The Unix timestamp (in seconds) of when the model response failed.

	Data      Data   `json:"data" yaml:"data" validate:"required"` // Event data payload.

	ID        string `json:"id" yaml:"id" validate:"required"` // The unique ID of the event.

	Object    *WebhookResponseFailedObject `json:"object" yaml:"object"` // The object of the event. Always `event`.

	Type      WebhookResponseFailedType `json:"type" yaml:"type" validate:"required"` // The type of the event. Always `response.failed`.

}
