// Code generated by schema2code at 2026-02-23 15:58:49. DO NOT EDIT.

package schema



// WorkflowParam Workflow reference and overrides applied to the chat session.
type WorkflowParam struct {
	ID             string                 `json:"id" yaml:"id" validate:"required"` // Identifier for the workflow invoked by the session.
	StateVariables map[string]interface{} `json:"state_variables" yaml:"state_variables"` // State variables forwarded to the workflow. Keys may be up to 64 characters, values must be primitive types, and the map defaults to an empty object.
	Tracing        *WorkflowTracingParam  `json:"tracing" yaml:"tracing"` // Optional tracing overrides for the workflow invocation. When omitted, tracing is enabled by default.
	Version        *string                `json:"version" yaml:"version"` // Specific workflow version to run. Defaults to the latest deployed version.
}
