// Code generated by schema2code at 2026-02-23 15:55:39. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// Instruction for updating an existing file via the apply_patch tool.
    /// </summary>
    public class ApplyPatchUpdateFileOperationParam
    {
        /// <summary>
        /// Unified diff content to apply to the existing file.
        /// </summary>
        [JsonPropertyName("diff")]
        public string Diff { get; set; } = default!;
        /// <summary>
        /// Path of the file to update relative to the workspace root.
        /// </summary>
        [JsonPropertyName("path")]
        public string Path { get; set; } = default!;
        /// <summary>
        /// The operation type. Always `update_file`.
        /// </summary>
        [JsonPropertyName("type")]
        public Type Type { get; set; } = "update_file";
    }
}