// Code generated by schema2code at 2026-02-23 15:55:39. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// Instruction describing how to update a file via the apply_patch tool.
    /// </summary>
    public class ApplyPatchUpdateFileOperation
    {
        /// <summary>
        /// Diff to apply.
        /// </summary>
        [JsonPropertyName("diff")]
        public string Diff { get; set; } = default!;
        /// <summary>
        /// Path of the file to update.
        /// </summary>
        [JsonPropertyName("path")]
        public string Path { get; set; } = default!;
        /// <summary>
        /// Update an existing file with the provided diff.
        /// </summary>
        [JsonPropertyName("type")]
        public Type Type { get; set; } = "update_file";
    }
}