// Code generated by schema2code at 2026-02-23 15:55:39. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum ApplyPatchCallStatus
    {
        [JsonPropertyName("in_progress")]
        IN_PROGRESS,
        [JsonPropertyName("completed")]
        COMPLETED
    }
}