// Code generated by schema2code at 2026-02-23 15:55:39. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// The streamed output emitted by an apply patch tool call.
    /// </summary>
    public class ApplyPatchToolCallOutputItemParam
    {
        /// <summary>
        /// The unique ID of the apply patch tool call generated by the model.
        /// </summary>
        [JsonPropertyName("call_id")]
        public string CallId { get; set; } = default!;
        [JsonPropertyName("id")]
        public object? Id { get; set; }
        [JsonPropertyName("output")]
        public object? Output { get; set; }
        /// <summary>
        /// The status of the apply patch tool call output. One of `completed` or `failed`.
        /// </summary>
        [JsonPropertyName("status")]
        public ApplyPatchCallOutputStatusParam Status { get; set; } = default!;
        /// <summary>
        /// The type of the item. Always `apply_patch_call_output`.
        /// </summary>
        [JsonPropertyName("type")]
        public Type Type { get; set; } = "apply_patch_call_output";
    }
}