// Code generated by schema2code at 2026-02-23 15:56:19. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// Represents an `assistant` that can call the model and use tools.
    /// </summary>
    public class AssistantObject
    {
        /// <summary>
        /// The Unix timestamp (in seconds) for when the assistant was created.
        /// </summary>
        [JsonPropertyName("created_at")]
        public long CreatedAt { get; set; } = default!;
        [JsonPropertyName("description")]
        public object Description { get; set; } = default!;
        /// <summary>
        /// The identifier, which can be referenced in API endpoints.
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; } = default!;
        [JsonPropertyName("instructions")]
        public object Instructions { get; set; } = default!;
        [JsonPropertyName("metadata")]
        public Metadata Metadata { get; set; } = default!;
        /// <summary>
        /// ID of the model to use. You can use the [List models](https://platform.openai.com/docs/api-reference/models/list) API to see all of your available models, or see our [Model overview](https://platform.openai.com/docs/models) for descriptions of them.

        /// </summary>
        [JsonPropertyName("model")]
        public string Model { get; set; } = default!;
        [JsonPropertyName("name")]
        public object Name { get; set; } = default!;
        /// <summary>
        /// The object type, which is always `assistant`.
        /// </summary>
        [JsonPropertyName("object")]
        public Object Object { get; set; } = default!;
        [JsonPropertyName("response_format")]
        public object? ResponseFormat { get; set; }
        [JsonPropertyName("temperature")]
        public object? Temperature { get; set; }
        [JsonPropertyName("tool_resources")]
        public object? ToolResources { get; set; }
        /// <summary>
        /// A list of tool enabled on the assistant. There can be a maximum of 128 tools per assistant. Tools can be of types `code_interpreter`, `file_search`, or `function`.

        /// </summary>
        [JsonPropertyName("tools")]
        public List<AssistantTool> Tools { get; set; } = [];
        [JsonPropertyName("top_p")]
        public object? TopP { get; set; }
    }
}