// Code generated by schema2code at 2026-02-23 15:55:48. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// Represents a ChatKit session and its resolved configuration.
    /// </summary>
    public class ChatSessionResource
    {
        /// <summary>
        /// Resolved ChatKit feature configuration for the session.
        /// </summary>
        [JsonPropertyName("chatkit_configuration")]
        public ChatSessionChatkitConfiguration ChatkitConfiguration { get; set; } = default!;
        /// <summary>
        /// Ephemeral client secret that authenticates session requests.
        /// </summary>
        [JsonPropertyName("client_secret")]
        public string ClientSecret { get; set; } = default!;
        /// <summary>
        /// Unix timestamp (in seconds) for when the session expires.
        /// </summary>
        [JsonPropertyName("expires_at")]
        public long ExpiresAt { get; set; } = default!;
        /// <summary>
        /// Identifier for the ChatKit session.
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; } = default!;
        /// <summary>
        /// Convenience copy of the per-minute request limit.
        /// </summary>
        [JsonPropertyName("max_requests_per_1_minute")]
        public long MaxRequestsPer1Minute { get; set; } = default!;
        /// <summary>
        /// Type discriminator that is always `chatkit.session`.
        /// </summary>
        [JsonPropertyName("object")]
        public Object Object { get; set; } = "chatkit.session";
        /// <summary>
        /// Resolved rate limit values.
        /// </summary>
        [JsonPropertyName("rate_limits")]
        public ChatSessionRateLimits RateLimits { get; set; } = default!;
        /// <summary>
        /// Current lifecycle state of the session.
        /// </summary>
        [JsonPropertyName("status")]
        public ChatSessionStatus Status { get; set; } = default!;
        /// <summary>
        /// User identifier associated with the session.
        /// </summary>
        [JsonPropertyName("user")]
        public string User { get; set; } = default!;
        /// <summary>
        /// Workflow metadata for the session.
        /// </summary>
        [JsonPropertyName("workflow")]
        public ChatkitWorkflow Workflow { get; set; } = default!;
    }
}