// Code generated by schema2code at 2026-02-23 15:55:48. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// History retention preferences returned for the session.
    /// </summary>
    public class ChatSessionHistory
    {
        /// <summary>
        /// Indicates if chat history is persisted for the session.
        /// </summary>
        [JsonPropertyName("enabled")]
        public bool Enabled { get; set; } = default!;
        [JsonPropertyName("recent_threads")]
        public object RecentThreads { get; set; } = default!;
    }
}