// Code generated by schema2code at 2026-02-23 15:55:48. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// Active per-minute request limit for the session.
    /// </summary>
    public class ChatSessionRateLimits
    {
        /// <summary>
        /// Maximum allowed requests per one-minute window.
        /// </summary>
        [JsonPropertyName("max_requests_per_1_minute")]
        public long MaxRequestsPer1Minute { get; set; } = default!;
    }
}