// Code generated by schema2code at 2026-02-23 15:55:49. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// Record of a client side tool invocation initiated by the assistant.
    /// </summary>
    public class ClientToolCallItem
    {
        /// <summary>
        /// JSON-encoded arguments that were sent to the tool.
        /// </summary>
        [JsonPropertyName("arguments")]
        public string Arguments { get; set; } = default!;
        /// <summary>
        /// Identifier for the client tool call.
        /// </summary>
        [JsonPropertyName("call_id")]
        public string CallId { get; set; } = default!;
        /// <summary>
        /// Unix timestamp (in seconds) for when the item was created.
        /// </summary>
        [JsonPropertyName("created_at")]
        public long CreatedAt { get; set; } = default!;
        /// <summary>
        /// Identifier of the thread item.
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; } = default!;
        /// <summary>
        /// Tool name that was invoked.
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; } = default!;
        /// <summary>
        /// Type discriminator that is always `chatkit.thread_item`.
        /// </summary>
        [JsonPropertyName("object")]
        public Object Object { get; set; } = "chatkit.thread_item";
        [JsonPropertyName("output")]
        public object Output { get; set; } = default!;
        /// <summary>
        /// Execution status for the tool call.
        /// </summary>
        [JsonPropertyName("status")]
        public ClientToolCallStatus Status { get; set; } = default!;
        /// <summary>
        /// Identifier of the parent thread.
        /// </summary>
        [JsonPropertyName("thread_id")]
        public string ThreadId { get; set; } = default!;
        /// <summary>
        /// Type discriminator that is always `chatkit.client_tool_call`.
        /// </summary>
        [JsonPropertyName("type")]
        public Type Type { get; set; } = "chatkit.client_tool_call";
    }
}