// Code generated by schema2code at 2026-02-23 15:55:50. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// The output of a code interpreter tool call that is a file.

    /// </summary>
    public class CodeInterpreterFileOutput
    {
        [JsonPropertyName("files")]
        public List<FilesItem> Files { get; set; } = default!;
        /// <summary>
        /// The type of the code interpreter file output. Always `files`.

        /// </summary>
        [JsonPropertyName("type")]
        public Type Type { get; set; } = default!;
    }
}