// Code generated by schema2code at 2026-02-23 15:55:52. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// The output of a computer tool call.
    /// </summary>
    public class ComputerCallOutputItemParam
    {
        [JsonPropertyName("acknowledged_safety_checks")]
        public object? AcknowledgedSafetyChecks { get; set; }
        /// <summary>
        /// The ID of the computer tool call that produced the output.
        /// </summary>
        [JsonPropertyName("call_id")]
        public string CallId { get; set; } = default!;
        [JsonPropertyName("id")]
        public object? Id { get; set; }
        [JsonPropertyName("output")]
        public ComputerScreenshotImage Output { get; set; } = default!;
        [JsonPropertyName("status")]
        public object? Status { get; set; }
        /// <summary>
        /// The type of the computer tool call output. Always `computer_call_output`.
        /// </summary>
        [JsonPropertyName("type")]
        public Type Type { get; set; } = "computer_call_output";
    }
}