// Code generated by schema2code at 2026-02-23 15:55:53. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    public class ContainerFileListResource
    {
        /// <summary>
        /// A list of container files.
        /// </summary>
        [JsonPropertyName("data")]
        public List<ContainerFileResource> Data { get; set; } = default!;
        /// <summary>
        /// The ID of the first file in the list.
        /// </summary>
        [JsonPropertyName("first_id")]
        public string FirstId { get; set; } = default!;
        /// <summary>
        /// Whether there are more files available.
        /// </summary>
        [JsonPropertyName("has_more")]
        public bool HasMore { get; set; } = default!;
        /// <summary>
        /// The ID of the last file in the list.
        /// </summary>
        [JsonPropertyName("last_id")]
        public string LastId { get; set; } = default!;
        /// <summary>
        /// The type of object returned, must be 'list'.
        /// </summary>
        [JsonPropertyName("object")]
        public string Object { get; set; } = default!;
    }
}