// Code generated by schema2code at 2026-02-23 15:55:54. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// The conversation that this response belongs to.
    /// </summary>
    public class ConversationParam-2
    {
        /// <summary>
        /// The unique ID of the conversation.
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; } = default!;
    }
}