// Code generated by schema2code at 2026-02-23 15:55:56. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// A CustomDataSourceConfig object that defines the schema for the data source used for the evaluation runs.
This schema is used to define the shape of the data that will be:
- Used to define your testing criteria and
- What data is required when creating a run

    /// </summary>
    public class CreateEvalCustomDataSourceConfig
    {
        /// <summary>
        /// Whether the eval should expect you to populate the sample namespace (ie, by generating responses off of your data source)
        /// </summary>
        [JsonPropertyName("include_sample_schema")]
        public bool? IncludeSampleSchema { get; set; } = false;
        /// <summary>
        /// The json schema for each row in the data source.
        /// </summary>
        [JsonPropertyName("item_schema")]
        public Dictionary<string, object> ItemSchema { get; set; } = default!;
        /// <summary>
        /// The type of data source. Always `custom`.
        /// </summary>
        [JsonPropertyName("type")]
        public Type Type { get; set; } = "custom";
    }
}