// Code generated by schema2code at 2026-02-23 15:56:00. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// Parameters for remixing an existing generated video.
    /// </summary>
    public class CreateVideoRemixBody
    {
        /// <summary>
        /// Updated text prompt that directs the remix generation.
        /// </summary>
        [JsonPropertyName("prompt")]
        public string Prompt { get; set; } = default!;
    }
}