// Code generated by schema2code at 2026-02-23 15:55:57. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// Deprecated in favor of LogsDataSourceConfig.

    /// </summary>
    public class CreateEvalStoredCompletionsDataSourceConfig
    {
        /// <summary>
        /// Metadata filters for the stored completions data source.
        /// </summary>
        [JsonPropertyName("metadata")]
        public Dictionary<string, object>? Metadata { get; set; }
        /// <summary>
        /// The type of data source. Always `stored_completions`.
        /// </summary>
        [JsonPropertyName("type")]
        public Type Type { get; set; } = "stored_completions";
    }
}