// Code generated by schema2code at 2026-02-23 15:55:55. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// Represents a completion response from the API. Note: both the streamed and non-streamed response objects share the same shape (unlike the chat endpoint).

    /// </summary>
    public class CreateCompletionResponse
    {
        /// <summary>
        /// The list of completion choices the model generated for the input prompt.
        /// </summary>
        [JsonPropertyName("choices")]
        public List<ChoicesItem> Choices { get; set; } = default!;
        /// <summary>
        /// The Unix timestamp (in seconds) of when the completion was created.
        /// </summary>
        [JsonPropertyName("created")]
        public long Created { get; set; } = default!;
        /// <summary>
        /// A unique identifier for the completion.
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; } = default!;
        /// <summary>
        /// The model used for completion.
        /// </summary>
        [JsonPropertyName("model")]
        public string Model { get; set; } = default!;
        /// <summary>
        /// The object type, which is always "text_completion"
        /// </summary>
        [JsonPropertyName("object")]
        public Object Object { get; set; } = default!;
        /// <summary>
        /// This fingerprint represents the backend configuration that the model runs with.

Can be used in conjunction with the `seed` request parameter to understand when backend changes have been made that might impact determinism.

        /// </summary>
        [JsonPropertyName("system_fingerprint")]
        public string? SystemFingerprint { get; set; }
        [JsonPropertyName("usage")]
        public CompletionUsage? Usage { get; set; }
    }
}