// Code generated by schema2code at 2026-02-23 15:56:01. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    public class CreateVoiceRequest
    {
        /// <summary>
        /// The sample audio recording file. Maximum size is 10 MiB.

Supported MIME types:
`audio/mpeg`, `audio/wav`, `audio/x-wav`, `audio/ogg`, `audio/aac`, `audio/flac`, `audio/webm`, `audio/mp4`.

        /// </summary>
        [JsonPropertyName("audio_sample")]
        public string AudioSample { get; set; } = default!;
        /// <summary>
        /// The consent recording ID (for example, `cons_1234`).
        /// </summary>
        [JsonPropertyName("consent")]
        public string Consent { get; set; } = default!;
        /// <summary>
        /// The name of the new voice.
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; } = default!;
    }
}