// Code generated by schema2code at 2026-02-23 15:55:57. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    public class CreateFineTuningJobRequest
    {
        /// <summary>
        /// The hyperparameters used for the fine-tuning job.
This value is now deprecated in favor of `method`, and should be passed in under the `method` parameter.

        /// </summary>
        [JsonPropertyName("hyperparameters")]
        public Hyperparameters? Hyperparameters { get; set; }
        /// <summary>
        /// A list of integrations to enable for your fine-tuning job.
        /// </summary>
        [JsonPropertyName("integrations")]
        public List<IntegrationsItem>? Integrations { get; set; }
        [JsonPropertyName("metadata")]
        public Metadata? Metadata { get; set; }
        [JsonPropertyName("method")]
        public FineTuneMethod? Method { get; set; }
        /// <summary>
        /// The name of the model to fine-tune. You can select one of the
[supported models](https://platform.openai.com/docs/guides/fine-tuning#which-models-can-be-fine-tuned).

        /// </summary>
        [JsonPropertyName("model")]
        public object Model { get; set; } = default!;
        /// <summary>
        /// The seed controls the reproducibility of the job. Passing in the same seed and job parameters should produce the same results, but may differ in rare cases.
If a seed is not specified, one will be generated for you.

        /// </summary>
        [JsonPropertyName("seed")]
        [Range(0, double.MaxValue)]
        [Range(double.MinValue, 2147483647)]
        public long? Seed { get; set; }
        /// <summary>
        /// A string of up to 64 characters that will be added to your fine-tuned model name.

For example, a `suffix` of "custom-model-name" would produce a model name like `ft:gpt-4o-mini:openai:custom-model-name:7p4lURel`.

        /// </summary>
        [JsonPropertyName("suffix")]
        public string? Suffix { get; set; }
        /// <summary>
        /// The ID of an uploaded file that contains training data.

See [upload file](https://platform.openai.com/docs/api-reference/files/create) for how to upload a file.

Your dataset must be formatted as a JSONL file. Additionally, you must upload your file with the purpose `fine-tune`.

The contents of the file should differ depending on if the model uses the [chat](https://platform.openai.com/docs/api-reference/fine-tuning/chat-input), [completions](https://platform.openai.com/docs/api-reference/fine-tuning/completions-input) format, or if the fine-tuning method uses the [preference](https://platform.openai.com/docs/api-reference/fine-tuning/preference-input) format.

See the [fine-tuning guide](https://platform.openai.com/docs/guides/model-optimization) for more details.

        /// </summary>
        [JsonPropertyName("training_file")]
        public string TrainingFile { get; set; } = default!;
        /// <summary>
        /// The ID of an uploaded file that contains validation data.

If you provide this file, the data is used to generate validation
metrics periodically during fine-tuning. These metrics can be viewed in
the fine-tuning results file.
The same data should not be present in both train and validation files.

Your dataset must be formatted as a JSONL file. You must upload your file with the purpose `fine-tune`.

See the [fine-tuning guide](https://platform.openai.com/docs/guides/model-optimization) for more details.

        /// </summary>
        [JsonPropertyName("validation_file")]
        public string? ValidationFile { get; set; }
    }
}