// Code generated by schema2code at 2026-02-23 15:55:58. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    public class CreateRunRequest
    {
        /// <summary>
        /// Appends additional instructions at the end of the instructions for the run. This is useful for modifying the behavior on a per-run basis without overriding other instructions.
        /// </summary>
        [JsonPropertyName("additional_instructions")]
        public string? AdditionalInstructions { get; set; }
        /// <summary>
        /// Adds additional messages to the thread before creating the run.
        /// </summary>
        [JsonPropertyName("additional_messages")]
        public List<CreateMessageRequest>? AdditionalMessages { get; set; }
        /// <summary>
        /// The ID of the [assistant](https://platform.openai.com/docs/api-reference/assistants) to use to execute this run.
        /// </summary>
        [JsonPropertyName("assistant_id")]
        public string AssistantId { get; set; } = default!;
        /// <summary>
        /// Overrides the [instructions](https://platform.openai.com/docs/api-reference/assistants/createAssistant) of the assistant. This is useful for modifying the behavior on a per-run basis.
        /// </summary>
        [JsonPropertyName("instructions")]
        public string? Instructions { get; set; }
        /// <summary>
        /// The maximum number of completion tokens that may be used over the course of the run. The run will make a best effort to use only the number of completion tokens specified, across multiple turns of the run. If the run exceeds the number of completion tokens specified, the run will end with status `incomplete`. See `incomplete_details` for more info.

        /// </summary>
        [JsonPropertyName("max_completion_tokens")]
        [Range(256, double.MaxValue)]
        public long? MaxCompletionTokens { get; set; }
        /// <summary>
        /// The maximum number of prompt tokens that may be used over the course of the run. The run will make a best effort to use only the number of prompt tokens specified, across multiple turns of the run. If the run exceeds the number of prompt tokens specified, the run will end with status `incomplete`. See `incomplete_details` for more info.

        /// </summary>
        [JsonPropertyName("max_prompt_tokens")]
        [Range(256, double.MaxValue)]
        public long? MaxPromptTokens { get; set; }
        [JsonPropertyName("metadata")]
        public Metadata? Metadata { get; set; }
        /// <summary>
        /// The ID of the [Model](https://platform.openai.com/docs/api-reference/models) to be used to execute this run. If a value is provided here, it will override the model associated with the assistant. If not, the model associated with the assistant will be used.
        /// </summary>
        [JsonPropertyName("model")]
        public object? Model { get; set; }
        [JsonPropertyName("parallel_tool_calls")]
        public ParallelToolCalls? ParallelToolCalls { get; set; }
        [JsonPropertyName("reasoning_effort")]
        public ReasoningEffort? ReasoningEffort { get; set; }
        [JsonPropertyName("response_format")]
        public AssistantsApiResponseFormatOption? ResponseFormat { get; set; }
        /// <summary>
        /// If `true`, returns a stream of events that happen during the Run as server-sent events, terminating when the Run enters a terminal state with a `data: [DONE]` message.

        /// </summary>
        [JsonPropertyName("stream")]
        public bool? Stream { get; set; }
        /// <summary>
        /// What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.

        /// </summary>
        [JsonPropertyName("temperature")]
        [Range(0, double.MaxValue)]
        [Range(double.MinValue, 2)]
        public double? Temperature { get; set; } = 1;
        [JsonPropertyName("tool_choice")]
        public string? ToolChoice { get; set; }
        /// <summary>
        /// Override the tools the assistant can use for this run. This is useful for modifying the behavior on a per-run basis.
        /// </summary>
        [JsonPropertyName("tools")]
        public List<AssistantTool>? Tools { get; set; }
        /// <summary>
        /// An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered.

We generally recommend altering this or temperature but not both.

        /// </summary>
        [JsonPropertyName("top_p")]
        [Range(0, double.MaxValue)]
        [Range(double.MinValue, 1)]
        public double? TopP { get; set; } = 1;
        [JsonPropertyName("truncation_strategy")]
        public string? TruncationStrategy { get; set; }
    }
}