// Code generated by schema2code at 2026-01-24 15:16:45. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// Source type for retrieved documents
    /// </summary>
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum DocumentSource
    {
        [JsonPropertyName("memory")]
        MEMORY,
        [JsonPropertyName("web_search")]
        WEB_SEARCH,
        [JsonPropertyName("vector_store")]
        VECTOR_STORE,
        [JsonPropertyName("file_upload")]
        FILE_UPLOAD
    }
}