// Code generated by schema2code at 2026-02-23 15:56:04. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// An error that occurred while generating the response.
    /// </summary>
    public class Error-2
    {
        /// <summary>
        /// A machine-readable error code that was returned.
        /// </summary>
        [JsonPropertyName("code")]
        public string Code { get; set; } = default!;
        /// <summary>
        /// A human-readable description of the error that was returned.
        /// </summary>
        [JsonPropertyName("message")]
        public string Message { get; set; } = default!;
    }
}