// Code generated by schema2code at 2026-02-23 15:56:13. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// A message input to the model with a role indicating instruction following
hierarchy. Instructions given with the `developer` or `system` role take
precedence over instructions given with the `user` role. Messages with the
`assistant` role are presumed to have been generated by the model in previous
interactions.

    /// </summary>
    public class EvalItem
    {
        [JsonPropertyName("content")]
        public EvalItemContent Content { get; set; } = default!;
        /// <summary>
        /// The role of the message input. One of `user`, `assistant`, `system`, or
`developer`.

        /// </summary>
        [JsonPropertyName("role")]
        public Role Role { get; set; } = default!;
        /// <summary>
        /// The type of the message input. Always `message`.

        /// </summary>
        [JsonPropertyName("type")]
        public Type? Type { get; set; }
    }
}