// Code generated by schema2code at 2026-02-23 15:56:06. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// A LogsDataSourceConfig which specifies the metadata property of your logs query.
This is usually metadata like `usecase=chatbot` or `prompt-version=v2`, etc.
The schema returned by this data source config is used to defined what variables are available in your evals.
`item` and `sample` are both defined when using this data source config.

    /// </summary>
    public class EvalLogsDataSourceConfig
    {
        [JsonPropertyName("metadata")]
        public Metadata? Metadata { get; set; }
        /// <summary>
        /// The json schema for the run data source items.
Learn how to build JSON schemas [here](https://json-schema.org/).

        /// </summary>
        [JsonPropertyName("schema")]
        public Dictionary<string, object> Schema { get; set; } = default!;
        /// <summary>
        /// The type of data source. Always `logs`.
        /// </summary>
        [JsonPropertyName("type")]
        public Type Type { get; set; } = "logs";
    }
}