// Code generated by schema2code at 2026-02-23 15:56:05. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// A list of inputs, each of which may be either an input text, output text, input
image, or input audio object.

    /// </summary>
    public class EvalItemContentArray
    {
    }
}