// Code generated by schema2code at 2026-02-23 15:56:07. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// The ranking options for the file search. If not specified, the file search tool will use the `auto` ranker and a score_threshold of 0.

See the [file search tool documentation](https://platform.openai.com/docs/assistants/tools/file-search#customizing-file-search-settings) for more information.

    /// </summary>
    public class FileSearchRankingOptions
    {
        [JsonPropertyName("ranker")]
        public FileSearchRanker? Ranker { get; set; }
        /// <summary>
        /// The score threshold for the file search. All values must be a floating point number between 0 and 1.
        /// </summary>
        [JsonPropertyName("score_threshold")]
        [Range(0, double.MaxValue)]
        [Range(double.MinValue, 1)]
        public double ScoreThreshold { get; set; } = default!;
    }
}