// Code generated by schema2code at 2026-02-23 15:56:10. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// The hyperparameters used for the fine-tuning job.
    /// </summary>
    public class FineTuneSupervisedHyperparameters
    {
        /// <summary>
        /// Number of examples in each batch. A larger batch size means that model parameters are updated less frequently, but with lower variance.

        /// </summary>
        [JsonPropertyName("batch_size")]
        public object? BatchSize { get; set; } = "auto";
        /// <summary>
        /// Scaling factor for the learning rate. A smaller learning rate may be useful to avoid overfitting.

        /// </summary>
        [JsonPropertyName("learning_rate_multiplier")]
        public object? LearningRateMultiplier { get; set; }
        /// <summary>
        /// The number of epochs to train the model for. An epoch refers to one full cycle through the training dataset.

        /// </summary>
        [JsonPropertyName("n_epochs")]
        public object? NEpochs { get; set; } = "auto";
    }
}