// Code generated by schema2code at 2026-02-23 15:55:32. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// Schema to trigger Go imports for time, uuid, and url
    /// </summary>
    public class FormatTest
    {
        [JsonPropertyName("timestamp")]
        public DateTime? Timestamp { get; set; }
        [JsonPropertyName("day")]
        public DateOnly? Day { get; set; }
        [JsonPropertyName("duration")]
        public TimeSpan? Duration { get; set; }
        [JsonPropertyName("user_id")]
        public Guid? UserId { get; set; }
        [JsonPropertyName("homepage")]
        public Uri? Homepage { get; set; }
    }
}