// Code generated by schema2code at 2026-02-23 15:56:12. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// The output of a shell tool call that was emitted.
    /// </summary>
    public class FunctionShellCallOutput
    {
        /// <summary>
        /// The unique ID of the shell tool call generated by the model.
        /// </summary>
        [JsonPropertyName("call_id")]
        public string CallId { get; set; } = default!;
        /// <summary>
        /// The identifier of the actor that created the item.
        /// </summary>
        [JsonPropertyName("created_by")]
        public string? CreatedBy { get; set; }
        /// <summary>
        /// The unique ID of the shell call output. Populated when this item is returned via API.
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; } = default!;
        [JsonPropertyName("max_output_length")]
        public object MaxOutputLength { get; set; } = default!;
        /// <summary>
        /// An array of shell call output contents
        /// </summary>
        [JsonPropertyName("output")]
        public List<FunctionShellCallOutputContent> Output { get; set; } = default!;
        /// <summary>
        /// The type of the shell call output. Always `shell_call_output`.
        /// </summary>
        [JsonPropertyName("type")]
        public Type Type { get; set; } = "shell_call_output";
    }
}