// Code generated by schema2code at 2026-02-23 15:56:10. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// The output of a function tool call.
    /// </summary>
    public class FunctionCallOutputItemParam
    {
        /// <summary>
        /// The unique ID of the function tool call generated by the model.
        /// </summary>
        [JsonPropertyName("call_id")]
        public string CallId { get; set; } = default!;
        [JsonPropertyName("id")]
        public object? Id { get; set; }
        /// <summary>
        /// Text, image, or file output of the function tool call.
        /// </summary>
        [JsonPropertyName("output")]
        public object Output { get; set; } = default!;
        [JsonPropertyName("status")]
        public object? Status { get; set; }
        /// <summary>
        /// The type of the function tool call output. Always `function_call_output`.
        /// </summary>
        [JsonPropertyName("type")]
        public Type Type { get; set; } = "function_call_output";
    }
}