// Code generated by schema2code at 2026-02-23 15:56:13. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// A MultiGrader object combines the output of multiple graders to produce a single score.
    /// </summary>
    public class GraderMulti
    {
        /// <summary>
        /// A formula to calculate the output based on grader results.
        /// </summary>
        [JsonPropertyName("calculate_output")]
        public string CalculateOutput { get; set; } = default!;
        [JsonPropertyName("graders")]
        public object Graders { get; set; } = default!;
        /// <summary>
        /// The name of the grader.
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; } = default!;
        /// <summary>
        /// The object type, which is always `multi`.
        /// </summary>
        [JsonPropertyName("type")]
        public Type Type { get; set; } = "multi";
    }
}