// Code generated by schema2code at 2026-02-23 15:56:13. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// A StringCheckGrader object that performs a string comparison between input and reference using a specified operation.

    /// </summary>
    public class GraderStringCheck
    {
        /// <summary>
        /// The input text. This may include template strings.
        /// </summary>
        [JsonPropertyName("input")]
        public string Input { get; set; } = default!;
        /// <summary>
        /// The name of the grader.
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; } = default!;
        /// <summary>
        /// The string check operation to perform. One of `eq`, `ne`, `like`, or `ilike`.
        /// </summary>
        [JsonPropertyName("operation")]
        public Operation Operation { get; set; } = default!;
        /// <summary>
        /// The reference text. This may include template strings.
        /// </summary>
        [JsonPropertyName("reference")]
        public string Reference { get; set; } = default!;
        /// <summary>
        /// The object type, which is always `string_check`.
        /// </summary>
        [JsonPropertyName("type")]
        public Type Type { get; set; } = default!;
    }
}