// Code generated by schema2code at 2025-08-26 22:17:32. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// Response from generating an image
    /// </summary>
    public class ImageGenerateResponse
    {
        /// <summary>
        /// Base64-encoded image
        /// </summary>
        [JsonPropertyName("image")]
        public string Image { get; set; } = default!;
        /// <summary>
        /// URL to download the image
        /// </summary>
        [JsonPropertyName("download")]
        public string Download { get; set; } = default!;
    }
}