// Code generated by schema2code at 2026-02-23 15:56:16. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// A tool that generates images using the GPT image models.

    /// </summary>
    public class ImageGenTool
    {
        /// <summary>
        /// Background type for the generated image. One of `transparent`,
`opaque`, or `auto`. Default: `auto`.

        /// </summary>
        [JsonPropertyName("background")]
        public Background? Background { get; set; } = "auto";
        [JsonPropertyName("input_fidelity")]
        public object? InputFidelity { get; set; }
        /// <summary>
        /// Optional mask for inpainting. Contains `image_url`
(string, optional) and `file_id` (string, optional).

        /// </summary>
        [JsonPropertyName("input_image_mask")]
        public InputImageMask? InputImageMask { get; set; }
        [JsonPropertyName("model")]
        public object? Model { get; set; }
        /// <summary>
        /// Moderation level for the generated image. Default: `auto`.

        /// </summary>
        [JsonPropertyName("moderation")]
        public Moderation? Moderation { get; set; } = "auto";
        /// <summary>
        /// Compression level for the output image. Default: 100.

        /// </summary>
        [JsonPropertyName("output_compression")]
        [Range(0, double.MaxValue)]
        [Range(double.MinValue, 100)]
        public long? OutputCompression { get; set; } = 100;
        /// <summary>
        /// The output format of the generated image. One of `png`, `webp`, or
`jpeg`. Default: `png`.

        /// </summary>
        [JsonPropertyName("output_format")]
        public OutputFormat? OutputFormat { get; set; } = "png";
        /// <summary>
        /// Number of partial images to generate in streaming mode, from 0 (default value) to 3.

        /// </summary>
        [JsonPropertyName("partial_images")]
        [Range(0, double.MaxValue)]
        [Range(double.MinValue, 3)]
        public long? PartialImages { get; set; } = 0;
        /// <summary>
        /// The quality of the generated image. One of `low`, `medium`, `high`,
or `auto`. Default: `auto`.

        /// </summary>
        [JsonPropertyName("quality")]
        public Quality? Quality { get; set; } = "auto";
        /// <summary>
        /// The size of the generated image. One of `1024x1024`, `1024x1536`,
`1536x1024`, or `auto`. Default: `auto`.

        /// </summary>
        [JsonPropertyName("size")]
        public Size? Size { get; set; } = "auto";
        /// <summary>
        /// The type of the image generation tool. Always `image_generation`.

        /// </summary>
        [JsonPropertyName("type")]
        public Type Type { get; set; } = default!;
    }
}