// Code generated by schema2code at 2025-08-26 22:17:35. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// Image generation configuration
    /// </summary>
    public class ImageGenerationConfig
    {
        /// <summary>
        /// Whether image generation is enabled
        /// </summary>
        [JsonPropertyName("enabled")]
        public bool Enabled { get; set; } = default!;
        /// <summary>
        /// Directory for file storage
        /// </summary>
        [JsonPropertyName("storage_directory")]
        public string StorageDirectory { get; set; } = default!;
        /// <summary>
        /// Maximum number of pixels in width or height (whichever is greater) for generated images
        /// </summary>
        [JsonPropertyName("max_image_size")]
        public long MaxImageSize { get; set; } = default!;
        /// <summary>
        /// Retention period for generated images in hours (e.g., 720 for 30 days)
        /// </summary>
        [JsonPropertyName("retention_hours")]
        public long RetentionHours { get; set; } = default!;
        /// <summary>
        /// Whether to enable automatic prompt refinement for image generation. This will take the given prompt and attempt to refine it to improve the quality of the generated image.
        /// </summary>
        [JsonPropertyName("auto_prompt_refinement")]
        public bool AutoPromptRefinement { get; set; } = default!;
        /// <summary>
        /// Width of the generated image
        /// </summary>
        [JsonPropertyName("width")]
        public long Width { get; set; } = default!;
        /// <summary>
        /// Height of the generated image
        /// </summary>
        [JsonPropertyName("height")]
        public long Height { get; set; } = default!;
        /// <summary>
        /// Number of inference steps
        /// </summary>
        [JsonPropertyName("inference_steps")]
        public long InferenceSteps { get; set; } = default!;
        /// <summary>
        /// Guidance scale for image generation
        /// </summary>
        [JsonPropertyName("guidance_scale")]
        public double GuidanceScale { get; set; } = default!;
        /// <summary>
        /// Whether to use low memory mode
        /// </summary>
        [JsonPropertyName("low_memory_mode")]
        public bool LowMemoryMode { get; set; } = default!;
        /// <summary>
        /// Negative prompt for image generation
        /// </summary>
        [JsonPropertyName("negative_prompt")]
        public string NegativePrompt { get; set; } = default!;
    }
}