// Code generated by schema2code at 2026-02-23 15:56:16. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// For the GPT image models only, the token usage information for the image generation.

    /// </summary>
    public class ImagesUsage
    {
        /// <summary>
        /// The number of tokens (images and text) in the input prompt.
        /// </summary>
        [JsonPropertyName("input_tokens")]
        public long InputTokens { get; set; } = default!;
        /// <summary>
        /// The input tokens detailed information for the image generation.
        /// </summary>
        [JsonPropertyName("input_tokens_details")]
        public InputTokensDetails InputTokensDetails { get; set; } = default!;
        /// <summary>
        /// The number of image tokens in the output image.
        /// </summary>
        [JsonPropertyName("output_tokens")]
        public long OutputTokens { get; set; } = default!;
        /// <summary>
        /// The total number of tokens (images and text) used for the image generation.

        /// </summary>
        [JsonPropertyName("total_tokens")]
        public long TotalTokens { get; set; } = default!;
    }
}