// Code generated by schema2code at 2025-08-26 22:17:32. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// Schema for an inference request in the LLM system
    /// </summary>
    public class InferenceQueueMessage
    {
        /// <summary>
        /// Unique identifier for the request and response correlation
        /// </summary>
        [JsonPropertyName("correlation_id")]
        public string CorrelationId { get; set; } = default!;
        /// <summary>
        /// Priority of the request
        /// </summary>
        [JsonPropertyName("priority")]
        public long Priority { get; set; } = default!;
        /// <summary>
        /// Timestamp of the request
        /// </summary>
        [JsonPropertyName("timestamp")]
        public DateTime Timestamp { get; set; } = default!;
        /// <summary>
        /// Payload containing the inference request details
        /// </summary>
        [JsonPropertyName("payload")]
        public object? Payload { get; set; }
        /// <summary>
        /// Type of the request, e.g., "chat", "image_generation", etc.
        /// </summary>
        [JsonPropertyName("task")]
        public Task Task { get; set; } = default!;
        /// <summary>
        /// Required memory in bytes for processing the request
        /// </summary>
        [JsonPropertyName("memory_required")]
        public double MemoryRequired { get; set; } = default!;
        /// <summary>
        /// type of message (e.g. "request", "status", "result")
        /// </summary>
        [JsonPropertyName("type")]
        public string? Type { get; set; }
    }
}