// Code generated by schema2code at 2025-10-27 18:24:28. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// Inference service configuration
    /// </summary>
    public class InferenceService
    {
        /// <summary>
        /// Base URL for the inference service
        /// </summary>
        [JsonPropertyName("base_url")]
        public string BaseUrl { get; set; } = default!;
    }
}