// Code generated by schema2code at 2026-02-23 15:56:19. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// An internal identifier for an item to reference.
    /// </summary>
    public class ItemReferenceParam
    {
        /// <summary>
        /// The ID of the item to reference.
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; } = default!;
        [JsonPropertyName("type")]
        public object? Type { get; set; }
    }
}