// Code generated by schema2code at 2025-08-26 22:17:32. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// Source type for a memory
    /// </summary>
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum MemorySource
    {
        /// <summary>
        /// Memory type for conversation summaries
        /// </summary>
        [JsonPropertyName("summary")]
        SUMMARY,
        /// <summary>
        /// Memory type for conversation messages
        /// </summary>
        [JsonPropertyName("message")]
        MESSAGE
    }
}