// Code generated by schema2code at 2026-02-23 15:56:25. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// A message to or from the model.
    /// </summary>
    public class Message
    {
        /// <summary>
        /// The content of the message
        /// </summary>
        [JsonPropertyName("content")]
        public List<object> Content { get; set; } = default!;
        /// <summary>
        /// The unique ID of the message.
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; } = default!;
        /// <summary>
        /// The role of the message. One of `unknown`, `user`, `assistant`, `system`, `critic`, `discriminator`, `developer`, or `tool`.
        /// </summary>
        [JsonPropertyName("role")]
        public MessageRole Role { get; set; } = default!;
        /// <summary>
        /// The status of item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API.
        /// </summary>
        [JsonPropertyName("status")]
        public MessageStatus Status { get; set; } = default!;
        /// <summary>
        /// The type of the message. Always set to `message`.
        /// </summary>
        [JsonPropertyName("type")]
        public Type Type { get; set; } = "message";
    }
}