// Code generated by schema2code at 2026-02-23 15:56:23. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// The refusal content generated by the assistant.
    /// </summary>
    public class MessageContentRefusalObject
    {
        [JsonPropertyName("refusal")]
        public string Refusal { get; set; } = default!;
        /// <summary>
        /// Always `refusal`.
        /// </summary>
        [JsonPropertyName("type")]
        public Type Type { get; set; } = default!;
    }
}