// Code generated by schema2code at 2025-08-03 11:47:22. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// ModelProfileImageSettings represents the image settings for a model profile
    /// </summary>
    public class ModelProfileImageSettings
    {
        /// <summary>
        /// Height of the image in pixels
        /// </summary>
        [JsonPropertyName("height")]
        public long? Height { get; set; }
        /// <summary>
        /// Width of the image in pixels
        /// </summary>
        [JsonPropertyName("width")]
        public long? Width { get; set; }
        /// <summary>
        /// Number of inference steps
        /// </summary>
        [JsonPropertyName("inference_steps")]
        public long? InferenceSteps { get; set; }
        /// <summary>
        /// Guidance scale for image generation
        /// </summary>
        [JsonPropertyName("guidance_scale")]
        public double? GuidanceScale { get; set; }
        /// <summary>
        /// Whether to use low memory mode
        /// </summary>
        [JsonPropertyName("low_memory_mode")]
        public bool? LowMemoryMode { get; set; }
        /// <summary>
        /// Negative prompt for image generation
        /// </summary>
        [JsonPropertyName("negative_prompt")]
        public string? NegativePrompt { get; set; }
        /// <summary>
        /// Name of the LoRA model to use for image generation
        /// </summary>
        [JsonPropertyName("lora_model")]
        public string? LoraModel { get; set; }
    }
}