// Code generated by schema2code at 2026-02-23 15:56:26. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// A mouse move action.

    /// </summary>
    public class Move
    {
        /// <summary>
        /// Specifies the event type. For a move action, this property is 
always set to `move`.

        /// </summary>
        [JsonPropertyName("type")]
        public Type Type { get; set; } = "move";
        /// <summary>
        /// The x-coordinate to move to.

        /// </summary>
        [JsonPropertyName("x")]
        public long X { get; set; } = default!;
        /// <summary>
        /// The y-coordinate to move to.

        /// </summary>
        [JsonPropertyName("y")]
        public long Y { get; set; } = default!;
    }
}