// Code generated by schema2code at 2026-02-23 15:56:29. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    public class ProjectServiceAccountCreateRequest
    {
        /// <summary>
        /// The name of the service account being created.
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; } = default!;
    }
}