// Code generated by schema2code at 2026-02-23 15:56:42. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// Returned in `server_vad` mode when the server detects the end of speech in 
the audio buffer. The server will also send an `conversation.item.created` 
event with the user message item that is created from the audio buffer.

    /// </summary>
    public class RealtimeServerEventInputAudioBufferSpeechStopped
    {
        /// <summary>
        /// Milliseconds since the session started when speech stopped. This will 
correspond to the end of audio sent to the model, and thus includes the 
`min_silence_duration_ms` configured in the Session.

        /// </summary>
        [JsonPropertyName("audio_end_ms")]
        public long AudioEndMs { get; set; } = default!;
        /// <summary>
        /// The unique ID of the server event.
        /// </summary>
        [JsonPropertyName("event_id")]
        public string EventId { get; set; } = default!;
        /// <summary>
        /// The ID of the user message item that will be created.
        /// </summary>
        [JsonPropertyName("item_id")]
        public string ItemId { get; set; } = default!;
        /// <summary>
        /// The event type, must be `input_audio_buffer.speech_stopped`.
        /// </summary>
        [JsonPropertyName("type")]
        public string Type { get; set; } = default!;
    }
}