// Code generated by schema2code at 2026-02-23 15:56:40. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    public class RealtimeMCPHTTPError
    {
        [JsonPropertyName("code")]
        public long Code { get; set; } = default!;
        [JsonPropertyName("message")]
        public string Message { get; set; } = default!;
        [JsonPropertyName("type")]
        public Type Type { get; set; } = default!;
    }
}