// Code generated by schema2code at 2026-02-23 15:56:41. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// Returned when the text value of an input audio transcription content part is updated with incremental transcription results.

    /// </summary>
    public class RealtimeServerEventConversationItemInputAudioTranscriptionDelta
    {
        /// <summary>
        /// The index of the content part in the item's content array.
        /// </summary>
        [JsonPropertyName("content_index")]
        public long? ContentIndex { get; set; }
        /// <summary>
        /// The text delta.
        /// </summary>
        [JsonPropertyName("delta")]
        public string? Delta { get; set; }
        /// <summary>
        /// The unique ID of the server event.
        /// </summary>
        [JsonPropertyName("event_id")]
        public string EventId { get; set; } = default!;
        /// <summary>
        /// The ID of the item containing the audio that is being transcribed.
        /// </summary>
        [JsonPropertyName("item_id")]
        public string ItemId { get; set; } = default!;
        [JsonPropertyName("logprobs")]
        public object? Logprobs { get; set; }
        /// <summary>
        /// The event type, must be `conversation.item.input_audio_transcription.delta`.
        /// </summary>
        [JsonPropertyName("type")]
        public string Type { get; set; } = default!;
    }
}