// Code generated by schema2code at 2026-02-23 15:56:34. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// Emitted at the beginning of a Response to indicate the updated rate limits. 
When a Response is created some tokens will be "reserved" for the output 
tokens, the rate limits shown here reflect that reservation, which is then 
adjusted accordingly once the Response is completed.

    /// </summary>
    public class RealtimeBetaServerEventRateLimitsUpdated
    {
        /// <summary>
        /// The unique ID of the server event.
        /// </summary>
        [JsonPropertyName("event_id")]
        public string EventId { get; set; } = default!;
        /// <summary>
        /// List of rate limit information.
        /// </summary>
        [JsonPropertyName("rate_limits")]
        public List<RateLimitsItem> RateLimits { get; set; } = default!;
        /// <summary>
        /// The event type, must be `rate_limits.updated`.
        /// </summary>
        [JsonPropertyName("type")]
        public string Type { get; set; } = default!;
    }
}