// Code generated by schema2code at 2026-02-23 15:56:40. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// A Realtime item representing an invocation of a tool on an MCP server.

    /// </summary>
    public class RealtimeMCPToolCall
    {
        [JsonPropertyName("approval_request_id")]
        public object? ApprovalRequestId { get; set; }
        /// <summary>
        /// A JSON string of the arguments passed to the tool.
        /// </summary>
        [JsonPropertyName("arguments")]
        public string Arguments { get; set; } = default!;
        [JsonPropertyName("error")]
        public object? Error { get; set; }
        /// <summary>
        /// The unique ID of the tool call.
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; } = default!;
        /// <summary>
        /// The name of the tool that was run.
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; } = default!;
        [JsonPropertyName("output")]
        public object? Output { get; set; }
        /// <summary>
        /// The label of the MCP server running the tool.
        /// </summary>
        [JsonPropertyName("server_label")]
        public string ServerLabel { get; set; } = default!;
        /// <summary>
        /// The type of the item. Always `mcp_call`.
        /// </summary>
        [JsonPropertyName("type")]
        public Type Type { get; set; } = default!;
    }
}