// Code generated by schema2code at 2026-02-23 15:56:32. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// Create a new Realtime response with these parameters
    /// </summary>
    public class RealtimeBetaResponseCreateParams
    {
        /// <summary>
        /// Controls which conversation the response is added to. Currently supports
`auto` and `none`, with `auto` as the default value. The `auto` value
means that the contents of the response will be added to the default
conversation. Set this to `none` to create an out-of-band response which 
will not add items to default conversation.

        /// </summary>
        [JsonPropertyName("conversation")]
        public object? Conversation { get; set; }
        /// <summary>
        /// Input items to include in the prompt for the model. Using this field
creates a new context for this Response instead of using the default
conversation. An empty array `[]` will clear the context for this Response.
Note that this can include references to items from the default conversation.

        /// </summary>
        [JsonPropertyName("input")]
        public List<RealtimeConversationItem>? Input { get; set; }
        /// <summary>
        /// The default system instructions (i.e. system message) prepended to model 
calls. This field allows the client to guide the model on desired 
responses. The model can be instructed on response content and format, 
(e.g. "be extremely succinct", "act friendly", "here are examples of good 
responses") and on audio behavior (e.g. "talk quickly", "inject emotion 
into your voice", "laugh frequently"). The instructions are not guaranteed 
to be followed by the model, but they provide guidance to the model on the 
desired behavior.

Note that the server sets default instructions which will be used if this 
field is not set and are visible in the `session.created` event at the 
start of the session.

        /// </summary>
        [JsonPropertyName("instructions")]
        public string? Instructions { get; set; }
        /// <summary>
        /// Maximum number of output tokens for a single assistant response,
inclusive of tool calls. Provide an integer between 1 and 4096 to
limit output tokens, or `inf` for the maximum available tokens for a
given model. Defaults to `inf`.

        /// </summary>
        [JsonPropertyName("max_output_tokens")]
        public object? MaxOutputTokens { get; set; }
        [JsonPropertyName("metadata")]
        public Metadata? Metadata { get; set; }
        /// <summary>
        /// The set of modalities the model can respond with. To disable audio,
set this to ["text"].

        /// </summary>
        [JsonPropertyName("modalities")]
        public List<ModalitiesItem>? Modalities { get; set; }
        /// <summary>
        /// The format of output audio. Options are `pcm16`, `g711_ulaw`, or `g711_alaw`.

        /// </summary>
        [JsonPropertyName("output_audio_format")]
        public OutputAudioFormat? OutputAudioFormat { get; set; }
        [JsonPropertyName("prompt")]
        public Prompt? Prompt { get; set; }
        /// <summary>
        /// Sampling temperature for the model, limited to [0.6, 1.2]. Defaults to 0.8.

        /// </summary>
        [JsonPropertyName("temperature")]
        public double? Temperature { get; set; }
        /// <summary>
        /// How the model chooses tools. Provide one of the string modes or force a specific
function/MCP tool.

        /// </summary>
        [JsonPropertyName("tool_choice")]
        public object? ToolChoice { get; set; } = "auto";
        /// <summary>
        /// Tools (functions) available to the model.
        /// </summary>
        [JsonPropertyName("tools")]
        public List<ToolsItem>? Tools { get; set; }
        /// <summary>
        /// The voice the model uses to respond. Supported built-in voices are `alloy`, `ash`, `ballad`, `coral`, `echo`, `sage`, `shimmer`, `verse`, `marin`, and `cedar`. Voice cannot be changed during the session once the model has responded with audio at least once.
        /// </summary>
        [JsonPropertyName("voice")]
        public VoiceIdsShared? Voice { get; set; }
    }
}