// Code generated by schema2code at 2026-02-23 15:56:35. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// Returned when a new Response is created. The first event of response creation,
where the response is in an initial state of `in_progress`.

    /// </summary>
    public class RealtimeBetaServerEventResponseCreated
    {
        /// <summary>
        /// The unique ID of the server event.
        /// </summary>
        [JsonPropertyName("event_id")]
        public string EventId { get; set; } = default!;
        [JsonPropertyName("response")]
        public RealtimeBetaResponse Response { get; set; } = default!;
        /// <summary>
        /// The event type, must be `response.created`.
        /// </summary>
        [JsonPropertyName("type")]
        public string Type { get; set; } = default!;
    }
}