// Code generated by schema2code at 2025-08-03 11:47:22. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// Redis configuration
    /// </summary>
    public class RedisConfig
    {
        /// <summary>
        /// Redis host
        /// </summary>
        [JsonPropertyName("host")]
        public string Host { get; set; } = default!;
        /// <summary>
        /// Redis port
        /// </summary>
        [JsonPropertyName("port")]
        public long Port { get; set; } = default!;
        /// <summary>
        /// Redis password
        /// </summary>
        [JsonPropertyName("password")]
        public string Password { get; set; } = default!;
        /// <summary>
        /// Redis database index
        /// </summary>
        [JsonPropertyName("db")]
        public long Db { get; set; } = default!;
        /// <summary>
        /// Whether Redis is enabled
        /// </summary>
        [JsonPropertyName("enabled")]
        public bool Enabled { get; set; } = default!;
        /// <summary>
        /// Conversation TTL
        /// </summary>
        [JsonPropertyName("conversation_ttl")]
        public long ConversationTtl { get; set; } = default!;
        /// <summary>
        /// Message TTL
        /// </summary>
        [JsonPropertyName("message_ttl")]
        public long MessageTtl { get; set; } = default!;
        /// <summary>
        /// Summary TTL
        /// </summary>
        [JsonPropertyName("summary_ttl")]
        public long SummaryTtl { get; set; } = default!;
        /// <summary>
        /// Connection pool size
        /// </summary>
        [JsonPropertyName("pool_size")]
        public long PoolSize { get; set; } = default!;
        /// <summary>
        /// Minimum idle connections
        /// </summary>
        [JsonPropertyName("min_idle_connections")]
        public long MinIdleConnections { get; set; } = default!;
        /// <summary>
        /// Connection timeout
        /// </summary>
        [JsonPropertyName("connect_timeout")]
        public long ConnectTimeout { get; set; } = default!;
    }
}