// Code generated by schema2code at 2026-02-23 15:56:46. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// Emitted when there is a partial audio response.
    /// </summary>
    public class ResponseAudioDeltaEvent
    {
        /// <summary>
        /// A chunk of Base64 encoded response audio bytes.

        /// </summary>
        [JsonPropertyName("delta")]
        public string Delta { get; set; } = default!;
        /// <summary>
        /// A sequence number for this chunk of the stream response.

        /// </summary>
        [JsonPropertyName("sequence_number")]
        public long SequenceNumber { get; set; } = default!;
        /// <summary>
        /// The type of the event. Always `response.audio.delta`.

        /// </summary>
        [JsonPropertyName("type")]
        public Type Type { get; set; } = default!;
    }
}