// Code generated by schema2code at 2026-02-23 15:56:53. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// Configuration options for a text response from the model. Can be plain
text or structured JSON data. Learn more:
- [Text inputs and outputs](https://platform.openai.com/docs/guides/text)
- [Structured Outputs](https://platform.openai.com/docs/guides/structured-outputs)

    /// </summary>
    public class ResponseTextParam
    {
        [JsonPropertyName("format")]
        public TextResponseFormatConfiguration? Format { get; set; }
        [JsonPropertyName("verbosity")]
        public Verbosity? Verbosity { get; set; }
    }
}