// Code generated by schema2code at 2026-02-23 15:56:51. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    public class ResponseProperties
    {
        [JsonPropertyName("background")]
        public object? Background { get; set; }
        [JsonPropertyName("max_output_tokens")]
        public object? MaxOutputTokens { get; set; }
        [JsonPropertyName("max_tool_calls")]
        public object? MaxToolCalls { get; set; }
        /// <summary>
        /// Model ID used to generate the response, like `gpt-4o` or `o3`. OpenAI
offers a wide range of models with different capabilities, performance
characteristics, and price points. Refer to the [model guide](https://platform.openai.com/docs/models)
to browse and compare available models.

        /// </summary>
        [JsonPropertyName("model")]
        public ModelIdsResponses? Model { get; set; }
        [JsonPropertyName("previous_response_id")]
        public object? PreviousResponseId { get; set; }
        [JsonPropertyName("prompt")]
        public Prompt? Prompt { get; set; }
        [JsonPropertyName("reasoning")]
        public object? Reasoning { get; set; }
        [JsonPropertyName("text")]
        public ResponseTextParam? Text { get; set; }
        [JsonPropertyName("tool_choice")]
        public ToolChoiceParam? ToolChoice { get; set; }
        [JsonPropertyName("tools")]
        public ToolsArray? Tools { get; set; }
        [JsonPropertyName("truncation")]
        public object? Truncation { get; set; }
    }
}