// Code generated by schema2code at 2026-02-23 15:56:48. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// Event indicating that input for a custom tool call is complete.

    /// </summary>
    public class ResponseCustomToolCallInputDoneEvent
    {
        /// <summary>
        /// The complete input data for the custom tool call.
        /// </summary>
        [JsonPropertyName("input")]
        public string Input { get; set; } = default!;
        /// <summary>
        /// Unique identifier for the API item associated with this event.
        /// </summary>
        [JsonPropertyName("item_id")]
        public string ItemId { get; set; } = default!;
        /// <summary>
        /// The index of the output this event applies to.
        /// </summary>
        [JsonPropertyName("output_index")]
        public long OutputIndex { get; set; } = default!;
        /// <summary>
        /// The sequence number of this event.
        /// </summary>
        [JsonPropertyName("sequence_number")]
        public long SequenceNumber { get; set; } = default!;
        /// <summary>
        /// The event type identifier.
        /// </summary>
        [JsonPropertyName("type")]
        public Type Type { get; set; } = default!;
    }
}