// Code generated by schema2code at 2026-02-23 15:56:51. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// Assistant response text accompanied by optional annotations.
    /// </summary>
    public class ResponseOutputText
    {
        /// <summary>
        /// Ordered list of annotations attached to the response text.
        /// </summary>
        [JsonPropertyName("annotations")]
        public List<object> Annotations { get; set; } = default!;
        /// <summary>
        /// Assistant generated text.
        /// </summary>
        [JsonPropertyName("text")]
        public string Text { get; set; } = default!;
        /// <summary>
        /// Type discriminator that is always `output_text`.
        /// </summary>
        [JsonPropertyName("type")]
        public Type Type { get; set; } = "output_text";
    }
}