// Code generated by schema2code at 2026-02-23 15:56:48. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// Emitted when an error occurs.
    /// </summary>
    public class ResponseErrorEvent
    {
        [JsonPropertyName("code")]
        public object Code { get; set; } = default!;
        /// <summary>
        /// The error message.

        /// </summary>
        [JsonPropertyName("message")]
        public string Message { get; set; } = default!;
        [JsonPropertyName("param")]
        public object Param { get; set; } = default!;
        /// <summary>
        /// The sequence number of this event.
        /// </summary>
        [JsonPropertyName("sequence_number")]
        public long SequenceNumber { get; set; } = default!;
        /// <summary>
        /// The type of the event. Always `error`.

        /// </summary>
        [JsonPropertyName("type")]
        public Type Type { get; set; } = default!;
    }
}