// Code generated by schema2code at 2026-02-23 15:56:57. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// Tool call objects
    /// </summary>
    public class RunToolCallObject
    {
        /// <summary>
        /// The function definition.
        /// </summary>
        [JsonPropertyName("function")]
        public Function Function { get; set; } = default!;
        /// <summary>
        /// The ID of the tool call. This ID must be referenced when you submit the tool outputs in using the [Submit tool outputs to run](https://platform.openai.com/docs/api-reference/runs/submitToolOutputs) endpoint.
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; } = default!;
        /// <summary>
        /// The type of tool call the output is required for. For now, this is always `function`.
        /// </summary>
        [JsonPropertyName("type")]
        public Type Type { get; set; } = default!;
    }
}