// Code generated by schema2code at 2025-09-18 14:55:39. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// Schema for synthesizing search topics
    /// </summary>
    public class SearchTopicSynthesis
    {
        /// <summary>
        /// List of URLs used to synthesize topics
        /// </summary>
        [JsonPropertyName("urls")]
        public List<string> Urls { get; set; } = default!;
        /// <summary>
        /// List of topics synthesized from the URLs
        /// </summary>
        [JsonPropertyName("topics")]
        public List<string> Topics { get; set; } = default!;
        /// <summary>
        /// The summary or synthesis of the topics from the content at the provided URLs
        /// </summary>
        [JsonPropertyName("synthesis")]
        public string Synthesis { get; set; } = default!;
        /// <summary>
        /// The timestamp when the synthesis was created
        /// </summary>
        [JsonPropertyName("created_at")]
        public DateTime CreatedAt { get; set; } = default!;
        /// <summary>
        /// The unique identifier for the synthesis
        /// </summary>
        [JsonPropertyName("id")]
        public long? Id { get; set; }
        /// <summary>
        /// The ID of the conversation associated with this synthesis
        /// </summary>
        [JsonPropertyName("conversation_id")]
        public long ConversationId { get; set; } = default!;
    }
}