// Code generated by schema2code at 2025-08-26 22:17:34. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// SocketConnectionType represents the type of connection used in a WebSocket communication
    /// </summary>
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum SocketConnectionType
    {
        [JsonPropertyName("image")]
        IMAGE,
        [JsonPropertyName("chat")]
        CHAT,
        [JsonPropertyName("status")]
        STATUS
    }
}