// Code generated by schema2code at 2025-10-27 18:24:38. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// Schema for tool needs analysis
    /// </summary>
    public class ToolNeeds
    {
        [JsonPropertyName("available_tools")]
        public List<AvailableTool> AvailableTools { get; set; } = default!;
        [JsonPropertyName("needs_dynamic_tool")]
        public bool NeedsDynamicTool { get; set; } = default!;
        [JsonPropertyName("dynamic_tool")]
        public DynamicTool? DynamicTool { get; set; }
    }
}