// Code generated by schema2code at 2026-02-23 15:57:02. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// Controls for how a thread will be truncated prior to the run. Use this to control the initial context window of the run.
    /// </summary>
    public class TruncationObject
    {
        [JsonPropertyName("last_messages")]
        public object? LastMessages { get; set; }
        /// <summary>
        /// The truncation strategy to use for the thread. The default is `auto`. If set to `last_messages`, the thread will be truncated to the n most recent messages in the thread. When set to `auto`, messages in the middle of the thread will be dropped to fit the context length of the model, `max_prompt_tokens`.
        /// </summary>
        [JsonPropertyName("type")]
        public Type Type { get; set; } = default!;
    }
}