// Code generated by schema2code at 2026-02-23 15:57:03. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// A citation for a web resource used to generate a model response.
    /// </summary>
    public class UrlCitationBody
    {
        /// <summary>
        /// The index of the last character of the URL citation in the message.
        /// </summary>
        [JsonPropertyName("end_index")]
        public long EndIndex { get; set; } = default!;
        /// <summary>
        /// The index of the first character of the URL citation in the message.
        /// </summary>
        [JsonPropertyName("start_index")]
        public long StartIndex { get; set; } = default!;
        /// <summary>
        /// The title of the web resource.
        /// </summary>
        [JsonPropertyName("title")]
        public string Title { get; set; } = default!;
        /// <summary>
        /// The type of the URL citation. Always `url_citation`.
        /// </summary>
        [JsonPropertyName("type")]
        public Type Type { get; set; } = "url_citation";
        /// <summary>
        /// The URL of the web resource.
        /// </summary>
        [JsonPropertyName("url")]
        public string Url { get; set; } = default!;
    }
}