// Code generated by schema2code at 2026-02-23 15:57:04. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// Paginated list of user objects returned when inspecting group membership.
    /// </summary>
    public class UserListResource
    {
        /// <summary>
        /// Users in the current page.
        /// </summary>
        [JsonPropertyName("data")]
        public List<User> Data { get; set; } = default!;
        /// <summary>
        /// Whether more users are available when paginating.
        /// </summary>
        [JsonPropertyName("has_more")]
        public bool HasMore { get; set; } = default!;
        /// <summary>
        /// Cursor to fetch the next page of results, or `null` when no further users are available.
        /// </summary>
        [JsonPropertyName("next")]
        public object Next { get; set; } = default!;
        /// <summary>
        /// Always `list`.
        /// </summary>
        [JsonPropertyName("object")]
        public Object Object { get; set; } = default!;
    }
}