// Code generated by schema2code at 2025-08-03 11:47:24. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// WebSocketConnection represents an active WebSocket connection
    /// </summary>
    public class WebSocketConnection
    {
        /// <summary>
        /// Unique identifier for the connection
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; } = default!;
        /// <summary>
        /// Identifier of the user associated with the connection
        /// </summary>
        [JsonPropertyName("user_id")]
        public string UserId { get; set; } = default!;
        /// <summary>
        /// Type of WebSocket connection (e.g., chat, image, status)
        /// </summary>
        [JsonPropertyName("type")]
        public Type Type { get; set; } = default!;
        /// <summary>
        /// The WebSocket connection object (represented as string)
        /// </summary>
        [JsonPropertyName("conn")]
        public object? Conn { get; set; }
        /// <summary>
        /// Timestamp indicating when the connection was established
        /// </summary>
        [JsonPropertyName("created_at")]
        public DateTime CreatedAt { get; set; } = default!;
    }
}