// Code generated by schema2code at 2026-02-23 15:57:14. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// List of web search providers
    /// </summary>
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum WebSearchProviders
    {
        [JsonPropertyName("google")]
        GOOGLE,
        [JsonPropertyName("brave")]
        BRAVE,
        [JsonPropertyName("ddg")]
        DDG,
        [JsonPropertyName("searx")]
        SEARX,
        [JsonPropertyName("serper")]
        SERPER
    }
}