// Code generated by schema2code at 2025-08-26 22:17:35. DO NOT EDIT.

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace SchemaTypes
{
    /// <summary>
    /// Web search settings
    /// </summary>
    public class WebSearchConfig
    {
        /// <summary>
        /// Whether web search is enabled
        /// </summary>
        [JsonPropertyName("enabled")]
        public bool Enabled { get; set; } = default!;
        /// <summary>
        /// Auto-detect web search
        /// </summary>
        [JsonPropertyName("auto_detect")]
        public bool AutoDetect { get; set; } = default!;
        /// <summary>
        /// Maximum number of results
        /// </summary>
        [JsonPropertyName("max_results")]
        public long MaxResults { get; set; } = default!;
        /// <summary>
        /// Include results in response
        /// </summary>
        [JsonPropertyName("include_results")]
        public bool IncludeResults { get; set; } = default!;
    }
}