// Code generated by schema2code at 2026-02-23 16:06:26. DO NOT EDIT.


/**
 * A test schema with an acronym in the title
 */
export interface APIResponse {
  /**
   * HTTP status code
   */
  status_code?: number;
  /**
   * Response body
   */
  body?: string;
}