// Code generated by schema2code at 2025-08-26 22:17:56. DO NOT EDIT.


/**
 * ChatSocketType represents a response sent over WebSocket
 */
export type ChatSocketType = 'send' | 'pause' | 'resume' | 'cancel';

/**
 * Constant values for ChatSocketType
 */
export const ChatSocketTypeValues = {
  /** send */
  SEND: 'send',
  /** pause */
  PAUSE: 'pause',
  /** resume */
  RESUME: 'resume',
  /** cancel */
  CANCEL: 'cancel'
} as const;