// Code generated by schema2code at 2025-08-03 11:47:04. DO NOT EDIT.


import { Message } from './Message';



/**
 * ChatResponse represents a response from the chat API
 */
export interface ChatResponse {
  /**
   * Indicates whether the generation is complete
   */
  done: boolean;
  /**
   * The message content and metadata returned by the model
   */
  message?: Message;
  /**
   * Timestamp when the response was created
   */
  created_at: Date;
  /**
   * The name or identifier of the model used for generation
   */
  model: string;
  /**
   * Array of numbers representing the tokenized context
   */
  context?: number[];
  /**
   * Specific indicator of how or why the generation finished
   */
  finish_reason?: 'stop' | 'length' | 'error' | 'load' | 'unload' | 'timeout' | 'cancel';
  /**
   * Total time taken for the entire generation process in milliseconds
   */
  total_duration?: number;
  /**
   * Time taken to load the model in milliseconds
   */
  load_duration?: number;
  /**
   * Number of tokens in the prompt that were evaluated
   */
  prompt_eval_count?: number;
  /**
   * Time taken to evaluate the prompt tokens in milliseconds
   */
  prompt_eval_duration?: number;
  /**
   * Total number of tokens evaluated
   */
  eval_count?: number;
  /**
   * Time taken for token evaluation in milliseconds
   */
  eval_duration?: number;
}