// Code generated by schema2code at 2026-02-23 16:06:42. DO NOT EDIT.


import { ChatCompletionResponseMessage } from './ChatCompletionResponseMessage';

import { ChatCompletionRequestMessageContentPartText } from './ChatCompletionRequestMessageContentPartText';

import { ChatCompletionRequestMessageContentPartImage } from './ChatCompletionRequestMessageContentPartImage';



/**
 * An object representing a list of chat completion messages.

 */
export interface ChatCompletionMessageList {
  /**
   * An array of chat completion message objects.

   */
  data: (ChatCompletionResponseMessage & DataItemOption1)[];
  /**
   * The identifier of the first chat message in the data array.
   */
  first_id: string;
  /**
   * Indicates whether there are more chat messages available.
   */
  has_more: boolean;
  /**
   * The identifier of the last chat message in the data array.
   */
  last_id: string;
  /**
   * The type of this object. It is always set to "list".

   */
  object: 'list';
}