// Code generated by schema2code at 2026-02-23 16:06:50. DO NOT EDIT.


import { ContainerResource } from './ContainerResource';



export interface ContainerListResource {
  /**
   * A list of containers.
   */
  data: (ContainerResource)[];
  /**
   * The ID of the first container in the list.
   */
  first_id: string;
  /**
   * Whether there are more containers available.
   */
  has_more: boolean;
  /**
   * The ID of the last container in the list.
   */
  last_id: string;
  /**
   * The type of object returned, must be 'list'.
   */
  object: string;
}