// Code generated by schema2code at 2026-02-23 16:06:52. DO NOT EDIT.


import { InputItem } from './InputItem';

import { Metadata } from './Metadata';



export interface CreateConversationBody {
  items?: (InputItem)[] | unknown;
  metadata?: Metadata | unknown;
}