// Code generated by schema2code at 2026-02-23 16:07:01. DO NOT EDIT.


/**
 * Properties of the custom tool.

 */
export interface Customtoolproperties {
  /**
   * Optional description of the custom tool, used to provide more context.

   */
  description?: string;
  /**
   * The input format for the custom tool. Default is unconstrained text.

   */
  format?: FormatOption0 | FormatOption1;
  /**
   * The name of the custom tool, used to identify it in tool calls.
   */
  name: string;
}

/**
 * A custom tool that processes input using a specified format.

 */
export interface CustomToolChatCompletions {
  /**
   * Properties of the custom tool.

   */
  custom: Custom;
  /**
   * The type of the custom tool. Always `custom`.
   */
  type: 'custom';
}