// Code generated by schema2code at 2026-02-23 16:07:01. DO NOT EDIT.


import { CustomTextFormatParam } from './CustomTextFormatParam';

import { CustomGrammarFormatParam } from './CustomGrammarFormatParam';



/**
 * A custom tool that processes input using a specified format. Learn more about   [custom tools](https://platform.openai.com/docs/guides/function-calling#custom-tools)
 */
export interface CustomToolParam {
  /**
   * Optional description of the custom tool, used to provide more context.
   */
  description?: string;
  /**
   * The input format for the custom tool. Default is unconstrained text.
   */
  format?: CustomTextFormatParam | CustomGrammarFormatParam;
  /**
   * The name of the custom tool, used to identify it in tool calls.
   */
  name: string;
  /**
   * The type of the custom tool. Always `custom`.
   */
  type: 'custom';
}