// Code generated by schema2code at 2026-02-23 16:06:31. DO NOT EDIT.


/**
 * Represents the response for an embedding request
 */
export interface EmbeddingResponse {
  model: string;
  embeddings: ((number)[])[];
  total_duration: number;
  load_duration: number;
  prompt_eval_count: number;
}