// Code generated by schema2code at 2026-02-23 16:09:14. DO NOT EDIT.


/**
 * An error that occurred while generating the response.
 */
export interface Error-2 {
  /**
   * A machine-readable error code that was returned.
   */
  code: string;
  /**
   * A human-readable description of the error that was returned.
   */
  message: string;
}