// Code generated by schema2code at 2026-02-23 16:07:18. DO NOT EDIT.


import { FunctionShellCallOutputTimeoutOutcome } from './FunctionShellCallOutputTimeoutOutcome';

import { FunctionShellCallOutputExitOutcome } from './FunctionShellCallOutputExitOutcome';



/**
 * The content of a shell tool call output that was emitted.
 */
export interface FunctionShellCallOutputContent {
  /**
   * The identifier of the actor that created the item.
   */
  created_by?: string;
  /**
   * Represents either an exit outcome (with an exit code) or a timeout outcome for a shell call output chunk.
   */
  outcome: FunctionShellCallOutputTimeoutOutcome | FunctionShellCallOutputExitOutcome;
  /**
   * The standard error output that was captured.
   */
  stderr: string;
  /**
   * The standard output that was captured.
   */
  stdout: string;
}