// Code generated by schema2code at 2026-02-23 16:07:25. DO NOT EDIT.


import { ImageGenUsage } from './ImageGenUsage';

import { Image } from './Image';



/**
 * The response from the image generation endpoint.
 */
export interface ImagesResponse {
  /**
   * The background parameter used for the image generation. Either `transparent` or `opaque`.
   */
  background?: 'transparent' | 'opaque';
  /**
   * The Unix timestamp (in seconds) of when the image was created.
   */
  created: number;
  /**
   * The list of generated images.
   */
  data?: (Image)[];
  /**
   * The output format of the image generation. Either `png`, `webp`, or `jpeg`.
   */
  output_format?: 'png' | 'webp' | 'jpeg';
  /**
   * The quality of the image generated. Either `low`, `medium`, or `high`.
   */
  quality?: 'low' | 'medium' | 'high';
  /**
   * The size of the image generated. Either `1024x1024`, `1024x1536`, or `1536x1024`.
   */
  size?: '1024x1024' | '1024x1536' | '1536x1024';
  usage?: ImageGenUsage;
}