// Code generated by schema2code at 2025-08-26 22:17:57. DO NOT EDIT.


import { InferenceService } from './InferenceService';



/**
 * Inference services configuration
 */
export interface InferenceServiceConfig {
  ollama: InferenceService;
  stable_diffusion: InferenceService;
  /**
   * Host for the inference service
   */
  host: string;
  /**
   * Port for the inference service
   */
  port: number;
}