// Code generated by schema2code at 2026-02-23 16:06:33. DO NOT EDIT.


/**
 * Inference service configuration
 */
export interface InferenceService {
  /**
   * Base URL for the inference service
   */
  base_url: string;
}