// Code generated by schema2code at 2026-01-24 15:18:00. DO NOT EDIT.


/**
 * Inference service configuration
 */
export interface InferenceService {
  /**
   * Base URL for the inference service
   */
  base_url: string;
}