// Code generated by schema2code at 2026-02-23 16:07:41. DO NOT EDIT.


/**
 * A file input to the model.
 */
export interface InputFileContent {
  /**
   * The content of the file to be sent to the model.

   */
  file_data?: string;
  file_id?: string | unknown;
  /**
   * The URL of the file to be sent to the model.
   */
  file_url?: string;
  /**
   * The name of the file to be sent to the model.
   */
  filename?: string;
  /**
   * The type of the input item. Always `input_file`.
   */
  type: 'input_file';
}