// Code generated by schema2code at 2025-09-18 14:56:31. DO NOT EDIT.


import { ComplexityLevel } from './ComplexityLevel';

import { RequiredCapability } from './RequiredCapability';



/**
 * Detailed analysis of user intent for smart tool generation
 */
export interface IntentAnalysis {
  /**
   * Primary intent identified from the user message
   */
  primary_intent: string;
  /**
   * Assessed complexity level of the request
   */
  complexity_level: ComplexityLevel;
  /**
   * Set of capabilities required to fulfill the request
   */
  required_capabilities: RequiredCapability[];
  /**
   * List of computational requirements identified
   */
  computational_requirements: string[];
  /**
   * Domain specificity score (0-1, higher = more domain-specific)
   */
  domain_specificity: number;
  /**
   * Reusability potential score (0-1, higher = more reusable)
   */
  reusability_potential: number;
  /**
   * Confidence in the analysis (0-1)
   */
  confidence: number;
}