// Code generated by schema2code at 2025-09-18 14:56:32. DO NOT EDIT.


/**
 * Configuration for internal services, including API keys and allowed IPs.
 */
export interface InternalConfig {
  /**
   * API key for internal service auth
   */
  APIKey: string;
  /**
   * Comma-separated list of allowed IPs
   */
  AllowedIPs: string;
}