// Code generated by schema2code at 2026-02-23 16:07:45. DO NOT EDIT.


import { TopLogProb } from './TopLogProb';



/**
 * The log probability of a token.
 */
export interface LogProb {
  bytes: (number)[];
  logprob: number;
  token: string;
  top_logprobs: (TopLogProb)[];
}