// Code generated by schema2code at 2025-10-27 18:26:11. DO NOT EDIT.


/**
 * Source type for a memory
 */
export type MemorySource = 'summary' | 'message' | 'search';

/**
 * Constant values for MemorySource
 */
export const MemorySourceValues = {
  /** summary // Memory type for conversation summaries */
  SUMMARY: 'summary',
  /** message // Memory type for conversation messages */
  MESSAGE: 'message',
  /** search // Memory type for search topic syntheses */
  SEARCH: 'search'
} as const;