// Code generated by schema2code at 2025-09-18 14:56:44. DO NOT EDIT.


/**
 * Memory retrieval settings
 */
export interface MemoryConfig {
  /**
   * Whether memory retrieval is enabled
   */
  enabled: boolean;
  /**
   * Retrieval limit
   */
  limit: number;
  /**
   * Enable cross-user retrieval
   */
  enable_cross_user: boolean;
  /**
   * Enable cross-conversation retrieval
   */
  enable_cross_conversation: boolean;
  /**
   * Similarity threshold
   */
  similarity_threshold: number;
  /**
   * Always retrieve
   */
  always_retrieve: boolean;
}