// Code generated by schema2code at 2026-02-23 16:07:39. DO NOT EDIT.


/**
 * The refusal content that is part of a message.
 */
export interface MessageDeltaContentRefusalObject {
  /**
   * The index of the refusal part in the message.
   */
  index: number;
  refusal?: string;
  /**
   * Always `refusal`.
   */
  type: 'refusal';
}