// Code generated by schema2code at 2026-02-23 16:07:40. DO NOT EDIT.


/**
 * The text content that is part of a message.
 */
export interface MessageRequestContentTextObject {
  /**
   * Text content to be sent to the model
   */
  text: string;
  /**
   * Always `text`.
   */
  type: 'text';
}