// Code generated by schema2code at 2026-02-23 16:08:42. DO NOT EDIT.


/**
 * Whether to enable [parallel function calling](https://platform.openai.com/docs/guides/function-calling#configuring-parallel-function-calling) during tool use.
 */
export interface ParallelToolCalls {
}