// Code generated by schema2code at 2026-02-23 16:09:24. DO NOT EDIT.


/**
 * Pipeline priority levels for cache eviction and resource management
 */
export enum PipelinePriority {
  VALUE_1 = 1,
  VALUE_5 = 5,
  VALUE_10 = 10,
  VALUE_20 = 20,
}