// Code generated by schema2code at 2026-01-24 15:18:07. DO NOT EDIT.


/**
 * User preferences
 */
export interface PreferencesConfig {
  /**
   * Default profile ID
   */
  default_profile_id?: string;
  /**
   * Theme
   */
  theme?: string;
  /**
   * Font size
   */
  font_size?: number;
  /**
   * Notifications enabled
   */
  notifications_on?: boolean;
  /**
   * Language
   */
  language?: string;
}