// Code generated by schema2code at 2026-02-23 16:07:52. DO NOT EDIT.


import { HybridSearchOptions } from './HybridSearchOptions';

import { RankerVersionType } from './RankerVersionType';



export interface RankingOptions {
  /**
   * Weights that control how reciprocal rank fusion balances semantic embedding matches versus sparse keyword matches when hybrid search is enabled.
   */
  hybrid_search?: HybridSearchOptions;
  /**
   * The ranker to use for the file search.
   */
  ranker?: RankerVersionType;
  /**
   * The score threshold for the file search, a number between 0 and 1. Numbers closer to 1 will attempt to return only the most relevant results, but may return fewer results.
   */
  score_threshold?: number;
}