// Code generated by schema2code at 2026-02-23 16:07:54. DO NOT EDIT.


/**
 * Send this event to cancel an in-progress response. The server will respond 
with a `response.done` event with a status of `response.status=cancelled`. If 
there is no response to cancel, the server will respond with an error.

 */
export interface RealtimeBetaClientEventResponseCancel {
  /**
   * Optional client-generated ID used to identify this event.
   */
  event_id?: string;
  /**
   * A specific response ID to cancel - if not provided, will cancel an 
in-progress response in the default conversation.

   */
  response_id?: string;
  /**
   * The event type, must be `response.cancel`.
   */
  type: string;
}