// Code generated by schema2code at 2025-09-18 14:56:39. DO NOT EDIT.


/**
 * Sub-question in a research plan
 */
export interface ResearchQuestion {
  /**
   * Unique identifier for the question
   */
  id: number;
  /**
   * The question to investigate
   */
  question: string;
  /**
   * Keywords relevant to the question
   */
  keywords: string[];
}