// Code generated by schema2code at 2026-02-23 16:08:24. DO NOT EDIT.


/**
 * Emitted when there is a partial transcript of audio.
 */
export interface ResponseAudioTranscriptDeltaEvent {
  /**
   * The partial transcript of the audio response.

   */
  delta: string;
  /**
   * The sequence number of this event.
   */
  sequence_number: number;
  /**
   * The type of the event. Always `response.audio.transcript.delta`.

   */
  type: 'response.audio.transcript.delta';
}