// Code generated by schema2code at 2026-02-23 16:08:35. DO NOT EDIT.


import { FileAnnotation } from './FileAnnotation';

import { UrlAnnotation } from './UrlAnnotation';



/**
 * Assistant response text accompanied by optional annotations.
 */
export interface ResponseOutputText {
  /**
   * Ordered list of annotations attached to the response text.
   */
  annotations: (FileAnnotation | UrlAnnotation)[];
  /**
   * Assistant generated text.
   */
  text: string;
  /**
   * Type discriminator that is always `output_text`.
   */
  type: 'output_text';
}