// Code generated by schema2code at 2026-02-23 16:09:09. DO NOT EDIT.


/**
 * Details about a role that can be assigned through the public Roles API.
 */
export interface Role {
  /**
   * Optional description of the role.
   */
  description: string | unknown;
  /**
   * Identifier for the role.
   */
  id: string;
  /**
   * Unique name for the role.
   */
  name: string;
  /**
   * Always `role`.
   */
  object: 'role';
  /**
   * Permissions granted by the role.
   */
  permissions: (string)[];
  /**
   * Whether the role is predefined and managed by OpenAI.
   */
  predefined_role: boolean;
  /**
   * Resource type the role is bound to (for example `api.organization` or `api.project`).
   */
  resource_type: string;
}