// Code generated by schema2code at 2025-08-03 11:47:08. DO NOT EDIT.


/**
 * Content item from a web search result
 */
export interface SearchResultContent {
  /**
   * URL of the content
   */
  url: string;
  /**
   * Title of the content
   */
  title: string;
  /**
   * Snippet or summary of the content
   */
  content: string;
}