// Code generated by schema2code at 2026-01-24 15:18:05. DO NOT EDIT.


/**
 * Server configuration
 */
export interface ServerConfig {
  /**
   * Server host
   */
  host: string;
  /**
   * Server port
   */
  port: number;
  /**
   * Base URL
   */
  base_url: string;
}