// Code generated by schema2code at 2026-01-24 15:18:05. DO NOT EDIT.


/**
 * SocketConnectionType represents the type of connection used in a WebSocket communication
 */
export type SocketConnectionType = 'image' | 'chat' | 'status';

/**
 * Constant values for SocketConnectionType
 */
export const SocketConnectionTypeValues = {
  /** image */
  IMAGE: 'image',
  /** chat */
  CHAT: 'chat',
  /** status */
  STATUS: 'status'
} as const;