// Code generated by schema2code at 2026-02-23 16:08:52. DO NOT EDIT.


import { TaskGroupTask } from './TaskGroupTask';



/**
 * Collection of workflow tasks grouped together in the thread.
 */
export interface TaskGroupItem {
  /**
   * Unix timestamp (in seconds) for when the item was created.
   */
  created_at: number;
  /**
   * Identifier of the thread item.
   */
  id: string;
  /**
   * Type discriminator that is always `chatkit.thread_item`.
   */
  object: 'chatkit.thread_item';
  /**
   * Tasks included in the group.
   */
  tasks: (TaskGroupTask)[];
  /**
   * Identifier of the parent thread.
   */
  thread_id: string;
  /**
   * Type discriminator that is always `chatkit.task_group`.
   */
  type: 'chatkit.task_group';
}