// Code generated by schema2code at 2026-02-23 16:08:53. DO NOT EDIT.


export type TaskType = 'custom' | 'thought';

/**
 * Constant values for TaskType
 */
export const TaskTypeValues = {
  /** custom */
  CUSTOM: 'custom',
  /** thought */
  THOUGHT: 'thought'
} as const;