// Code generated by schema2code at 2025-08-03 11:47:08. DO NOT EDIT.


/**
 * Holds the outcome of token validation
 */
export interface TokenValidationResult {
  /**
   * The user ID extracted from the token
   */
  user_id: string;
  /**
   * JWT claims from the token
   */
  claims: Record<string, unknown>;
  /**
   * Whether the user has admin privileges
   */
  is_admin: boolean;
}