// Code generated by schema2code at 2025-10-27 18:27:00. DO NOT EDIT.


import { DynamicTool } from './DynamicTool';

import { AvailableTool } from './AvailableTool';



/**
 * Schema for tool needs analysis
 */
export interface ToolNeeds {
  available_tools: AvailableTool[];
  needs_dynamic_tool: boolean;
  dynamic_tool?: DynamicTool;
}