// Code generated by schema2code at 2026-02-23 16:08:59. DO NOT EDIT.


/**
 * The top log probability of a token.
 */
export interface TopLogProb {
  bytes: (number)[];
  logprob: number;
  token: string;
}