// Code generated by schema2code at 2026-02-23 16:09:04. DO NOT EDIT.


import { OpenAIFile } from './OpenAiFile';



/**
 * The Upload object can accept byte chunks in the form of Parts.

 */
export interface Upload {
  /**
   * The intended number of bytes to be uploaded.
   */
  bytes: number;
  /**
   * The Unix timestamp (in seconds) for when the Upload was created.
   */
  created_at: number;
  /**
   * The Unix timestamp (in seconds) for when the Upload will expire.
   */
  expires_at: number;
  file?: OpenAIFile & string;
  /**
   * The name of the file to be uploaded.
   */
  filename: string;
  /**
   * The Upload unique identifier, which can be referenced in API endpoints.
   */
  id: string;
  /**
   * The object type, which is always "upload".
   */
  object: 'upload';
  /**
   * The intended purpose of the file. [Please refer here](https://platform.openai.com/docs/api-reference/files/object#files/object-purpose) for acceptable values.
   */
  purpose: string;
  /**
   * The status of the Upload.
   */
  status: 'pending' | 'completed' | 'cancelled' | 'expired';
}