// Code generated by schema2code at 2025-10-27 18:27:07. DO NOT EDIT.


import { WebSearchProviders } from './WebSearchProviders';



/**
 * Web search settings
 */
export interface WebSearchConfig {
  /**
   * Whether web search is enabled
   */
  enabled: boolean;
  /**
   * Auto-detect web search
   */
  auto_detect: boolean;
  /**
   * Maximum number of results
   */
  max_results: number;
  /**
   * Include results in response
   */
  include_results: boolean;
  /**
   * List of search providers to use
   */
  search_providers: WebSearchProviders[];
  /**
   * Maximum number of URLs to deep crawl
   */
  max_urls_deep: number;
}