# Code generated by schema2code at 2025-09-18 14:56:21. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class AvailableTool(BaseModel):
    """A tool made available for use in the system"""
    name: Optional[str] = Field(default=None, description="The name of the tool")
    """The name of the tool"""
    description: Optional[str] = Field(default=None, description="A description of the tool's purpose")
    """A description of the tool's purpose"""
    type: Optional[str] = Field(default=None, description="The type of the tool")
    """The type of the tool"""

    class Config:
        extra = "ignore"