# Code generated by schema2code at 2025-08-03 11:47:10. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from .chat_message_metadata import ChatMessageMetadata
from pydantic import BaseModel, Field, AnyUrl, EmailStr



"""ChatSocketCommand represents a command sent over WebSocket"""
class ChatSocketCommand(BaseModel):
    # Type of command
    type: str = Field(..., description="Type of command")
    # Message content
    message: str = Field(..., description="Message content")
    # Conversation ID
    conversation_id: int = Field(..., description="Conversation ID")
    # Additional metadata
    metadata: Optional[ChatMessageMetadata] = Field(None, description="Additional metadata")

    class Config:
        extra = "ignore"