# Code generated by schema2code at 2025-08-26 22:17:46. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ChatMessageMetadata(BaseModel):
    """Additional metadata for the chat message"""
    generate_image: bool = Field(..., description="Whether the message includes generated images")
    """Whether the message includes generated images"""
    is_continuation: bool = Field(..., description="Whether this message is a continuation of a previous message")
    """Whether this message is a continuation of a previous message"""
    is_cancellation: Optional[bool] = Field(default=None, description="Whether this message is a cancellation of a previous message")
    """Whether this message is a cancellation of a previous message"""
    is_pause: Optional[bool] = Field(default=None, description="Whether this message is a pause in the conversation")
    """Whether this message is a pause in the conversation"""
    type: str = Field(..., description="Type of the message, e.g., 'pause', 'cancel', etc.")
    """Type of the message, e.g., 'pause', 'cancel', etc."""

    class Config:
        extra = "ignore"