# Code generated by schema2code at 2026-02-23 16:05:25. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .conversation_param_2 import ConversationParam2
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



ConversationParam = Union[ConversationParam2]