# Code generated by schema2code at 2026-02-23 16:05:30. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .grammar_syntax1 import GrammarSyntax1
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class CustomGrammarFormatParam(BaseModel):
    """A grammar defined by the user."""
    definition: Annotated[str, Field(..., description="The grammar definition.")]
    """The grammar definition."""
    syntax: Annotated[GrammarSyntax1, Field(..., description="The syntax of the grammar definition. One of `lark` or `regex`.")]
    """The syntax of the grammar definition. One of `lark` or `regex`."""
    type: Annotated[Literal["grammar"], Field(default='grammar', description="Grammar format. Always `grammar`.")]
    """Grammar format. Always `grammar`."""

    class Config:
        extra = "ignore"