# Code generated by schema2code at 2025-10-27 18:25:13. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union, Annotated
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class DatabaseConfig(BaseModel):
    """Database configuration"""
    host: Annotated[str, Field(..., description="Database host")]
    """Database host"""
    port: Annotated[int, Field(..., description="Database port")]
    """Database port"""
    user: Annotated[str, Field(..., description="Database user")]
    """Database user"""
    password: Annotated[str, Field(..., description="Database password")]
    """Database password"""
    dbname: Annotated[str, Field(..., description="Database name")]
    """Database name"""
    sslmode: Annotated[str, Field(..., description="SSL mode")]
    """SSL mode"""
    connection_string: Annotated[str, Field(..., description="Connection string")]
    """Connection string"""

    class Config:
        extra = "ignore"