# Code generated by schema2code at 2026-02-23 16:01:50. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class DeletedVideoResource(BaseModel):
    """Confirmation payload returned after deleting a video."""
    deleted: Annotated[bool, Field(..., description="Indicates that the video resource was deleted.")]
    """Indicates that the video resource was deleted."""
    id: Annotated[str, Field(..., description="Identifier of the deleted video.")]
    """Identifier of the deleted video."""
    object: Annotated[Literal["video.deleted"], Field(default='video.deleted', description="The object type that signals the deletion response.")]
    """The object type that signals the deletion response."""

    class Config:
        extra = "ignore"