# Code generated by schema2code at 2026-01-24 15:17:32. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class DevStats(BaseModel):
    """Schema representing device memory statistics."""
    id: Annotated[str, Field(..., description="Device identifier.")]
    """Device identifier."""
    uuid: Annotated[str, Field(..., description="Universally unique identifier for the device.")]
    """Universally unique identifier for the device."""
    gpu_util: Annotated[float, Field(..., description="GPU utilization percentage.")]
    """GPU utilization percentage."""
    mem_util: Annotated[float, Field(..., description="Memory utilization percentage.")]
    """Memory utilization percentage."""
    mem_total: Annotated[float, Field(..., description="Total memory in megabytes.")]
    """Total memory in megabytes."""
    mem_used: Annotated[float, Field(..., description="Used memory in megabytes.")]
    """Used memory in megabytes."""
    mem_free: Annotated[float, Field(..., description="Free memory in megabytes.")]
    """Free memory in megabytes."""
    driver: Annotated[str, Field(..., description="Driver version.")]
    """Driver version."""
    name: Annotated[str, Field(..., description="Device name.")]
    """Device name."""
    serial: Annotated[str, Field(..., description="Device serial number.")]
    """Device serial number."""
    display_mode: Annotated[str, Field(..., description="Display mode status.")]
    """Display mode status."""
    display_active: Annotated[str, Field(..., description="Display active status.")]
    """Display active status."""
    temperature: Annotated[float, Field(..., description="Device temperature in Celsius.")]
    """Device temperature in Celsius."""

    class Config:
        extra = "ignore"