# Code generated by schema2code at 2025-08-03 11:47:11. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr



"""Represents the response for an embedding request"""
class EmbeddingResponse(BaseModel):
    model: str
    embeddings: List[List[float]]
    total_duration: int
    load_duration: int
    prompt_eval_count: int

    class Config:
        extra = "ignore"