# Code generated by schema2code at 2025-10-27 18:25:15. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union, Annotated
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class EmbeddingResponse(BaseModel):
    """Represents the response for an embedding request"""
    model: Annotated[str, Field(...)]
    embeddings: Annotated[List[List[float]], Field(...)]
    total_duration: Annotated[int, Field(...)]
    load_duration: Annotated[int, Field(...)]
    prompt_eval_count: Annotated[int, Field(...)]

    class Config:
        extra = "ignore"