# Code generated by schema2code at 2026-01-24 15:17:34. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class EnumBundle(BaseModel):
    """Multiple enums to test TypeScript generation and index exports"""
    status: Annotated[Optional[Literal["pending", "running", "done"]], Field(default=None)] = None
    level: Annotated[Optional[Literal["low", "medium", "high"]], Field(default=None)] = None
    flags: Annotated[Optional[List[Literal["alpha", "beta"]]], Field(default=None)] = None

    class Config:
        extra = "ignore"