# Code generated by schema2code at 2026-02-23 16:02:44. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class FineTuningCheckpointPermission(BaseModel):
    """The `checkpoint.permission` object represents a permission for a fine-tuned model checkpoint.
"""
    created_at: Annotated[int, Field(..., description="The Unix timestamp (in seconds) for when the permission was created.")]
    """The Unix timestamp (in seconds) for when the permission was created."""
    id: Annotated[str, Field(..., description="The permission identifier, which can be referenced in the API endpoints.")]
    """The permission identifier, which can be referenced in the API endpoints."""
    object: Annotated[Literal["checkpoint.permission"], Field(..., description="The object type, which is always \"checkpoint.permission\".")]
    """The object type, which is always \"checkpoint.permission\"."""
    project_id: Annotated[str, Field(..., description="The project identifier that the permission is for.")]
    """The project identifier that the permission is for."""

    class Config:
        extra = "ignore"