# Code generated by schema2code at 2026-02-23 16:00:37. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
import uuid
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class FormatTest(BaseModel):
    """Schema to trigger Go imports for time, uuid, and url"""
    timestamp: Annotated[Optional[datetime], Field(default=None)] = None
    day: Annotated[Optional[date], Field(default=None)] = None
    duration: Annotated[Optional[timedelta], Field(default=None)] = None
    user_id: Annotated[Optional[uuid.UUID], Field(default=None)] = None
    homepage: Annotated[Optional[AnyUrl], Field(default=None)] = None

    class Config:
        extra = "ignore"