# Code generated by schema2code at 2026-02-23 16:04:38. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .function_tool_call import FunctionToolCall
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class FunctionToolCallResource(BaseModel):
    arguments: Annotated[str, Field(..., description="A JSON string of the arguments to pass to the function. ")]
    """A JSON string of the arguments to pass to the function. """
    call_id: Annotated[str, Field(..., description="The unique ID of the function tool call generated by the model. ")]
    """The unique ID of the function tool call generated by the model. """
    id: Annotated[str, Field(..., description="The unique ID of the function tool call. ")]
    """The unique ID of the function tool call. """
    name: Annotated[str, Field(..., description="The name of the function to run. ")]
    """The name of the function to run. """
    status: Annotated[Optional[Literal["in_progress", "completed", "incomplete"]], Field(default=None, description="The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API. ")] = None
    """The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API. """
    type: Annotated[Literal["function_call"], Field(..., description="The type of the function tool call. Always `function_call`. ")]
    """The type of the function tool call. Always `function_call`. """

    class Config:
        extra = "ignore"