# Code generated by schema2code at 2026-02-23 16:02:32. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class InputTokensDetails(BaseModel):
    """The input tokens detailed information for the image generation."""
    image_tokens: Annotated[int, Field(..., description="The number of image tokens in the input prompt.")]
    """The number of image tokens in the input prompt."""
    text_tokens: Annotated[int, Field(..., description="The number of text tokens in the input prompt.")]
    """The number of text tokens in the input prompt."""

    class Config:
        extra = "ignore"

class ImagesUsage(BaseModel):
    """For the GPT image models only, the token usage information for the image generation.
"""
    input_tokens: Annotated[int, Field(..., description="The number of tokens (images and text) in the input prompt.")]
    """The number of tokens (images and text) in the input prompt."""
    input_tokens_details: Annotated[InputTokensDetails, Field(..., description="The input tokens detailed information for the image generation.")]
    """The input tokens detailed information for the image generation."""
    output_tokens: Annotated[int, Field(..., description="The number of image tokens in the output image.")]
    """The number of image tokens in the output image."""
    total_tokens: Annotated[int, Field(..., description="The total number of tokens (images and text) used for the image generation. ")]
    """The total number of tokens (images and text) used for the image generation. """

    class Config:
        extra = "ignore"

ImagesUsage.model_rebuild()