# Code generated by schema2code at 2026-01-24 15:17:38. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class InferenceQueueMessage(BaseModel):
    """Schema for an inference request in the LLM system"""
    correlation_id: Annotated[str, Field(..., description="Unique identifier for the request and response correlation")]
    """Unique identifier for the request and response correlation"""
    priority: Annotated[int, Field(..., description="Priority of the request")]
    """Priority of the request"""
    timestamp: Annotated[datetime, Field(..., description="Timestamp of the request")]
    """Timestamp of the request"""
    payload: Annotated[Optional[Any], Field(default=None, description="Payload containing the inference request details")] = None
    """Payload containing the inference request details"""
    task: Annotated[Literal["image_generation", "image_editing", "research"], Field(..., description="Type of the request, e.g., \"chat\", \"image_generation\", etc.")]
    """Type of the request, e.g., \"chat\", \"image_generation\", etc."""
    memory_required: Annotated[float, Field(..., description="Required memory in bytes for processing the request")]
    """Required memory in bytes for processing the request"""
    type: Annotated[Optional[str], Field(default=None, description="type of message (e.g. \"request\", \"status\", \"result\")")] = None
    """type of message (e.g. \"request\", \"status\", \"result\")"""

    class Config:
        extra = "ignore"