# Code generated by schema2code at 2025-10-27 18:25:19. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union, Annotated
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class InferenceService(BaseModel):
    """Inference service configuration"""
    base_url: Annotated[str, Field(..., description="Base URL for the inference service")]
    """Base URL for the inference service"""

    class Config:
        extra = "ignore"