# Code generated by schema2code at 2026-01-24 15:17:41. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class MapExample(BaseModel):
    attributes: Annotated[Optional[Dict[str, str]], Field(default=None)] = None
    counts: Annotated[Optional[Dict[str, int]], Field(default=None)] = None
    generic: Annotated[Optional[Dict[str, Any]], Field(default=None)] = None

    class Config:
        extra = "ignore"