# Code generated by schema2code at 2026-02-23 16:03:00. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ImageFile(BaseModel):
    detail: Annotated[Optional[Literal["auto", "low", "high"]], Field(default='auto', description="Specifies the detail level of the image if specified by the user. `low` uses fewer tokens, you can opt in to high resolution using `high`.")] = 'auto'
    """Specifies the detail level of the image if specified by the user. `low` uses fewer tokens, you can opt in to high resolution using `high`."""
    file_id: Annotated[str, Field(..., description="The [File](https://platform.openai.com/docs/api-reference/files) ID of the image in the message content. Set `purpose=\"vision\"` when uploading the File if you need to later display the file content.")]
    """The [File](https://platform.openai.com/docs/api-reference/files) ID of the image in the message content. Set `purpose=\"vision\"` when uploading the File if you need to later display the file content."""

    class Config:
        extra = "ignore"

class MessageContentImageFileObject(BaseModel):
    """References an image [File](https://platform.openai.com/docs/api-reference/files) in the content of a message."""
    image_file: Annotated[ImageFile, Field(...)]
    type: Annotated[Literal["image_file"], Field(..., description="Always `image_file`.")]
    """Always `image_file`."""

    class Config:
        extra = "ignore"

MessageContentImageFileObject.model_rebuild()