# Code generated by schema2code at 2026-02-23 16:05:19. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class FileCitation(BaseModel):
    file_id: Annotated[str, Field(..., description="The ID of the specific File the citation is from.")]
    """The ID of the specific File the citation is from."""

    class Config:
        extra = "ignore"

class MessageContentTextAnnotationsFileCitationObject(BaseModel):
    """A citation within the message that points to a specific quote from a specific File associated with the assistant or the message. Generated when the assistant uses the "file_search" tool to search files."""
    end_index: Annotated[int, Field(..., ge=0)]
    file_citation: Annotated[FileCitation, Field(...)]
    start_index: Annotated[int, Field(..., ge=0)]
    text: Annotated[str, Field(..., description="The text in the message content that needs to be replaced.")]
    """The text in the message content that needs to be replaced."""
    type: Annotated[Literal["file_citation"], Field(..., description="Always `file_citation`.")]
    """Always `file_citation`."""

    class Config:
        extra = "ignore"

MessageContentTextAnnotationsFileCitationObject.model_rebuild()