# Code generated by schema2code at 2025-08-03 11:47:14. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from .model_task import ModelTask
from .model_details import ModelDetails
from .lora_weight import LoraWeight
from pydantic import BaseModel, Field, AnyUrl, EmailStr



"""Model represents a machine learning model used for generating responses"""
class Model(BaseModel):
    # Unique identifier for the model
    id: Optional[str] = Field(None, description="Unique identifier for the model")
    # Display name of the model
    name: str = Field(..., description="Display name of the model")
    # Identifier used to reference the model
    model: str = Field(..., description="Identifier used to reference the model")
    # Type of task the model is designed for (e.g., "TextToText", "TextToImage")
    task: ModelTask = Field(..., description="Type of task the model is designed for (e.g., \"TextToText\", \"TextToImage\")")
    # Timestamp of when the model was last modified
    modified_at: str = Field(..., description="Timestamp of when the model was last modified")
    # Size of the model in bytes
    size: int = Field(..., description="Size of the model in bytes")
    # Hash digest identifying the model version
    digest: str = Field(..., description="Hash digest identifying the model version")
    # Additional information about the model
    details: ModelDetails = Field(..., description="Additional information about the model")
    # Pipeline type used for the model (e.g., "sd3", "sdxl")
    pipeline: Optional[str] = Field(None, description="Pipeline type used for the model (e.g., \"sd3\", \"sdxl\")")
    # List of LoRA weights associated with the model
    lora_weights: Optional[List[LoraWeight]] = Field(None, description="List of LoRA weights associated with the model")

    class Config:
        extra = "ignore"