# Code generated by schema2code at 2026-02-23 16:05:39. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class OpenAIFile(BaseModel):
    """The `File` object represents a document that has been uploaded to OpenAI."""
    bytes: Annotated[int, Field(..., description="The size of the file, in bytes.")]
    """The size of the file, in bytes."""
    created_at: Annotated[int, Field(..., description="The Unix timestamp (in seconds) for when the file was created.")]
    """The Unix timestamp (in seconds) for when the file was created."""
    expires_at: Annotated[Optional[int], Field(default=None, description="The Unix timestamp (in seconds) for when the file will expire.")] = None
    """The Unix timestamp (in seconds) for when the file will expire."""
    filename: Annotated[str, Field(..., description="The name of the file.")]
    """The name of the file."""
    id: Annotated[str, Field(..., description="The file identifier, which can be referenced in the API endpoints.")]
    """The file identifier, which can be referenced in the API endpoints."""
    object: Annotated[Literal["file"], Field(..., description="The object type, which is always `file`.")]
    """The object type, which is always `file`."""
    purpose: Annotated[Literal["assistants", "assistants_output", "batch", "batch_output", "fine-tune", "fine-tune-results", "vision", "user_data"], Field(..., description="The intended purpose of the file. Supported values are `assistants`, `assistants_output`, `batch`, `batch_output`, `fine-tune`, `fine-tune-results`, `vision`, and `user_data`.")]
    """The intended purpose of the file. Supported values are `assistants`, `assistants_output`, `batch`, `batch_output`, `fine-tune`, `fine-tune-results`, `vision`, and `user_data`."""
    status: Annotated[Literal["uploaded", "processed", "error"], Field(..., description="Deprecated. The current status of the file, which can be either `uploaded`, `processed`, or `error`.")]
    """Deprecated. The current status of the file, which can be either `uploaded`, `processed`, or `error`."""
    status_details: Annotated[Optional[str], Field(default=None, description="Deprecated. For details on why a fine-tuning training file failed validation, see the `error` field on `fine_tuning.job`.")] = None
    """Deprecated. For details on why a fine-tuning training file failed validation, see the `error` field on `fine_tuning.job`."""

    class Config:
        extra = "ignore"