# Code generated by schema2code at 2026-02-23 16:03:13. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ProjectRateLimitUpdateRequest(BaseModel):
    batch_1_day_max_input_tokens: Annotated[Optional[int], Field(default=None, description="The maximum batch input tokens per day. Only relevant for certain models.")] = None
    """The maximum batch input tokens per day. Only relevant for certain models."""
    max_audio_megabytes_per_1_minute: Annotated[Optional[int], Field(default=None, description="The maximum audio megabytes per minute. Only relevant for certain models.")] = None
    """The maximum audio megabytes per minute. Only relevant for certain models."""
    max_images_per_1_minute: Annotated[Optional[int], Field(default=None, description="The maximum images per minute. Only relevant for certain models.")] = None
    """The maximum images per minute. Only relevant for certain models."""
    max_requests_per_1_day: Annotated[Optional[int], Field(default=None, description="The maximum requests per day. Only relevant for certain models.")] = None
    """The maximum requests per day. Only relevant for certain models."""
    max_requests_per_1_minute: Annotated[Optional[int], Field(default=None, description="The maximum requests per minute.")] = None
    """The maximum requests per minute."""
    max_tokens_per_1_minute: Annotated[Optional[int], Field(default=None, description="The maximum tokens per minute.")] = None
    """The maximum tokens per minute."""

    class Config:
        extra = "ignore"