# Code generated by schema2code at 2026-02-23 16:04:16. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class RealtimeFunctionTool(BaseModel):
    description: Annotated[Optional[str], Field(default=None, description="The description of the function, including guidance on when and how to call it, and guidance about what to tell the user when calling (if anything). ")] = None
    """The description of the function, including guidance on when and how to call it, and guidance about what to tell the user when calling (if anything). """
    name: Annotated[Optional[str], Field(default=None, description="The name of the function.")] = None
    """The name of the function."""
    parameters: Annotated[Optional[Dict[str, Any]], Field(default=None, description="Parameters of the function in JSON Schema.")] = None
    """Parameters of the function in JSON Schema."""
    type: Annotated[Optional[Literal["function"]], Field(default=None, description="The type of the tool, i.e. `function`.")] = None
    """The type of the tool, i.e. `function`."""

    class Config:
        extra = "ignore"