# Code generated by schema2code at 2026-02-23 16:04:14. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .mcp_list_tools_tool import MCPListToolsTool
from .realtime_conversation_item import RealtimeConversationItem
from .realtime_conversation_item_function_call import RealtimeConversationItemFunctionCall
from .realtime_conversation_item_function_call_output import RealtimeConversationItemFunctionCallOutput
from .realtime_conversation_item_message_assistant import RealtimeConversationItemMessageAssistant
from .realtime_conversation_item_message_system import RealtimeConversationItemMessageSystem
from .realtime_conversation_item_message_user import RealtimeConversationItemMessageUser
from .realtime_mcp_approval_request import RealtimeMCPApprovalRequest
from .realtime_mcp_approval_response import RealtimeMCPApprovalResponse
from .realtime_mcp_list_tools import RealtimeMCPListTools
from .realtime_mcp_protocol_error import RealtimeMCPProtocolError
from .realtime_mcp_tool_call import RealtimeMCPToolCall
from .realtime_mcp_tool_execution_error import RealtimeMCPToolExecutionError
from .realtime_mcphttp_error import RealtimeMCPHTTPError
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class RealtimeServerEventConversationItemAdded(BaseModel):
    """Sent by the server when an Item is added to the default Conversation. This can happen in several cases:
- When the client sends a `conversation.item.create` event.
- When the input audio buffer is committed. In this case the item will be a user message containing the audio from the buffer.
- When the model is generating a Response. In this case the `conversation.item.added` event will be sent when the model starts generating a specific Item, and thus it will not yet have any content (and `status` will be `in_progress`).

The event will include the full content of the Item (except when model is generating a Response) except for audio data, which can be retrieved separately with a `conversation.item.retrieve` event if necessary.
"""
    event_id: Annotated[str, Field(..., description="The unique ID of the server event.")]
    """The unique ID of the server event."""
    item: Annotated[RealtimeConversationItem, Field(...)]
    previous_item_id: Annotated[Optional[Union[str, Any]], Field(default=None)] = None
    type: Annotated[str, Field(..., description="The event type, must be `conversation.item.added`.")]
    """The event type, must be `conversation.item.added`."""

    class Config:
        extra = "ignore"