# Code generated by schema2code at 2026-02-23 16:05:25. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ResponseFormatJsonObject(BaseModel):
    """JSON object response format. An older method of generating JSON responses.
Using `json_schema` is recommended for models that support it. Note that the
model will not generate JSON without a system or user message instructing it
to do so.
"""
    type: Annotated[Literal["json_object"], Field(..., description="The type of response format being defined. Always `json_object`.")]
    """The type of response format being defined. Always `json_object`."""

    class Config:
        extra = "ignore"