# Code generated by schema2code at 2026-02-23 16:04:52. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ResponseMCPCallCompletedEvent(BaseModel):
    """Emitted when an MCP  tool call has completed successfully.
"""
    item_id: Annotated[str, Field(..., description="The ID of the MCP tool call item that completed.")]
    """The ID of the MCP tool call item that completed."""
    output_index: Annotated[int, Field(..., description="The index of the output item that completed.")]
    """The index of the output item that completed."""
    sequence_number: Annotated[int, Field(..., description="The sequence number of this event.")]
    """The sequence number of this event."""
    type: Annotated[Literal["response.mcp_call.completed"], Field(..., description="The type of the event. Always 'response.mcp_call.completed'.")]
    """The type of the event. Always 'response.mcp_call.completed'."""

    class Config:
        extra = "ignore"