# Code generated by schema2code at 2026-02-23 16:04:52. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ResponseMCPCallArgumentsDoneEvent(BaseModel):
    """Emitted when the arguments for an MCP tool call are finalized.
"""
    arguments: Annotated[str, Field(..., description="A JSON string containing the finalized arguments for the MCP tool call. ")]
    """A JSON string containing the finalized arguments for the MCP tool call. """
    item_id: Annotated[str, Field(..., description="The unique identifier of the MCP tool call item being processed.")]
    """The unique identifier of the MCP tool call item being processed."""
    output_index: Annotated[int, Field(..., description="The index of the output item in the response's output array.")]
    """The index of the output item in the response's output array."""
    sequence_number: Annotated[int, Field(..., description="The sequence number of this event.")]
    """The sequence number of this event."""
    type: Annotated[Literal["response.mcp_call_arguments.done"], Field(..., description="The type of the event. Always 'response.mcp_call_arguments.done'.")]
    """The type of the event. Always 'response.mcp_call_arguments.done'."""

    class Config:
        extra = "ignore"