# Code generated by schema2code at 2026-02-23 16:04:32. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ResponseFormatTextGrammar(BaseModel):
    """A custom grammar for the model to follow when generating text.
Learn more in the [custom grammars guide](https://platform.openai.com/docs/guides/custom-grammars).
"""
    grammar: Annotated[str, Field(..., description="The custom grammar for the model to follow.")]
    """The custom grammar for the model to follow."""
    type: Annotated[Literal["grammar"], Field(..., description="The type of response format being defined. Always `grammar`.")]
    """The type of response format being defined. Always `grammar`."""

    class Config:
        extra = "ignore"