# Code generated by schema2code at 2025-09-18 14:56:16. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from .document_source import DocumentSource
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class Metadata(BaseModel):
    """Document metadata"""
    title: Optional[str] = Field(default=None, description="Document title")
    """Document title"""
    url: Optional[AnyUrl] = Field(default=None, description="Source URL if applicable")
    """Source URL if applicable"""
    created_at: Optional[datetime] = Field(default=None, description="When document was created")
    """When document was created"""
    tags: Optional[List[str]] = Field(default=None, description="Document tags")
    """Document tags"""

    class Config:
        extra = "ignore"

class ChunkInfo(BaseModel):
    """Information about document chunking"""
    chunk_id: Optional[str] = Field(default=None)
    total_chunks: Optional[int] = Field(default=None, ge=1)
    chunk_index: Optional[int] = Field(default=None, ge=0)

    class Config:
        extra = "ignore"

class RetrievedDocument(BaseModel):
    """Document retrieved from RAG system"""
    document_id: str = Field(..., description="Unique identifier for the document")
    """Unique identifier for the document"""
    source: DocumentSource = Field(..., description="Source of the document")
    """Source of the document"""
    content: str = Field(..., description="The document content")
    """The document content"""
    relevance_score: float = Field(..., description="Relevance score for the query", ge=0, le=1)
    """Relevance score for the query"""
    metadata: Optional[Metadata] = Field(default=None, description="Document metadata")
    """Document metadata"""
    chunk_info: Optional[ChunkInfo] = Field(default=None, description="Information about document chunking")
    """Information about document chunking"""

    class Config:
        extra = "ignore"