# Code generated by schema2code at 2026-02-23 16:05:47. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class Role(BaseModel):
    """Details about a role that can be assigned through the public Roles API."""
    description: Annotated[Union[str, Any], Field(..., description="Optional description of the role.")]
    """Optional description of the role."""
    id: Annotated[str, Field(..., description="Identifier for the role.")]
    """Identifier for the role."""
    name: Annotated[str, Field(..., description="Unique name for the role.")]
    """Unique name for the role."""
    object: Annotated[Literal["role"], Field(..., description="Always `role`.")]
    """Always `role`."""
    permissions: Annotated[List[str], Field(..., description="Permissions granted by the role.")]
    """Permissions granted by the role."""
    predefined_role: Annotated[bool, Field(..., description="Whether the role is predefined and managed by OpenAI.")]
    """Whether the role is predefined and managed by OpenAI."""
    resource_type: Annotated[str, Field(..., description="Resource type the role is bound to (for example `api.organization` or `api.project`).")]
    """Resource type the role is bound to (for example `api.organization` or `api.project`)."""

    class Config:
        extra = "ignore"