# Code generated by schema2code at 2026-02-23 16:05:09. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .file_search_ranker import FileSearchRanker
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class RunStepDetailsToolCallsFileSearchRankingOptionsObject(BaseModel):
    """The ranking options for the file search."""
    ranker: Annotated[FileSearchRanker, Field(...)]
    score_threshold: Annotated[float, Field(..., description="The score threshold for the file search. All values must be a floating point number between 0 and 1.", ge=0, le=1)]
    """The score threshold for the file search. All values must be a floating point number between 0 and 1."""

    class Config:
        extra = "ignore"