# Code generated by schema2code at 2026-02-23 16:05:51. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .static_chunking_strategy import StaticChunkingStrategy
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class StaticChunkingStrategyResponseParam(BaseModel):
    static: Annotated[StaticChunkingStrategy, Field(...)]
    type: Annotated[Literal["static"], Field(..., description="Always `static`.")]
    """Always `static`."""

    class Config:
        extra = "ignore"