# Code generated by schema2code at 2026-02-23 16:05:22. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .task_type import TaskType
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class TaskItem(BaseModel):
    """Task emitted by the workflow to show progress and status updates."""
    created_at: Annotated[int, Field(..., description="Unix timestamp (in seconds) for when the item was created.")]
    """Unix timestamp (in seconds) for when the item was created."""
    heading: Annotated[Union[str, Any], Field(...)]
    id: Annotated[str, Field(..., description="Identifier of the thread item.")]
    """Identifier of the thread item."""
    object: Annotated[Literal["chatkit.thread_item"], Field(default='chatkit.thread_item', description="Type discriminator that is always `chatkit.thread_item`.")]
    """Type discriminator that is always `chatkit.thread_item`."""
    summary: Annotated[Union[str, Any], Field(...)]
    task_type: Annotated[TaskType, Field(..., description="Subtype for the task.")]
    """Subtype for the task."""
    thread_id: Annotated[str, Field(..., description="Identifier of the parent thread.")]
    """Identifier of the parent thread."""
    type: Annotated[Literal["chatkit.task"], Field(default='chatkit.task', description="Type discriminator that is always `chatkit.task`.")]
    """Type discriminator that is always `chatkit.task`."""

    class Config:
        extra = "ignore"