# Code generated by schema2code at 2026-02-23 16:05:19. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .message_delta_content_text_annotations_file_citation_object import MessageDeltaContentTextAnnotationsFileCitationObject
from .message_delta_content_text_annotations_file_citation_object import FileCitation
from .message_delta_content_text_annotations_file_path_object import MessageDeltaContentTextAnnotationsFilePathObject
from .message_delta_content_text_annotations_file_path_object import FilePath
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



TextAnnotationDelta = Union[MessageDeltaContentTextAnnotationsFileCitationObject, MessageDeltaContentTextAnnotationsFilePathObject]