# Code generated by schema2code at 2026-01-24 15:17:54. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .available_tool import AvailableTool
from .dynamic_tool import DynamicTool
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ToolNeeds(BaseModel):
    """Schema for tool needs analysis"""
    available_tools: Annotated[List[AvailableTool], Field(...)]
    needs_dynamic_tool: Annotated[bool, Field(...)]
    dynamic_tool: Annotated[Optional[DynamicTool], Field(default=None)] = None

    class Config:
        extra = "ignore"