# Code generated by schema2code at 2026-02-23 16:05:37. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .vector_store_file_attributes import VectorStoreFileAttributes
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class UpdateVectorStoreFileAttributesRequest(BaseModel):
    attributes: Annotated[VectorStoreFileAttributes, Field(...)]

    class Config:
        extra = "ignore"