# Code generated by schema2code at 2025-10-27 18:25:38. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union, Annotated
from datetime import datetime, date, time, timedelta
from .web_search_providers import WebSearchProviders
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class WebSearchConfig(BaseModel):
    """Web search settings"""
    enabled: Annotated[bool, Field(..., description="Whether web search is enabled")]
    """Whether web search is enabled"""
    auto_detect: Annotated[bool, Field(..., description="Auto-detect web search")]
    """Auto-detect web search"""
    max_results: Annotated[int, Field(..., description="Maximum number of results")]
    """Maximum number of results"""
    include_results: Annotated[bool, Field(..., description="Include results in response")]
    """Include results in response"""
    search_providers: Annotated[List[WebSearchProviders], Field(..., description="List of search providers to use")]
    """List of search providers to use"""
    max_urls_deep: Annotated[int, Field(..., description="Maximum number of URLs to deep crawl")]
    """Maximum number of URLs to deep crawl"""

    class Config:
        extra = "ignore"