# Code generated by schema2code at 2026-02-23 16:06:25. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class WebSearchConfig(BaseModel):
    """Comprehensive web search settings for SearxNG integration"""
    enabled: Annotated[bool, Field(default=True, description="Whether web search is enabled")]
    """Whether web search is enabled"""
    auto_detect: Annotated[bool, Field(default=True, description="Auto-detect web search needs from user queries")]
    """Auto-detect web search needs from user queries"""
    max_results: Annotated[int, Field(default=5, description="Maximum number of search results to return", ge=1, le=20)]
    """Maximum number of search results to return"""
    include_results: Annotated[bool, Field(default=True, description="Include full search results in response")]
    """Include full search results in response"""
    max_urls_deep: Annotated[int, Field(default=3, description="Maximum number of URLs to deep crawl for content extraction", ge=0, le=10)]
    """Maximum number of URLs to deep crawl for content extraction"""
    engines: Annotated[List[str], Field(default_factory=lambda: ['google', 'bing', 'duckduckgo', 'startpage', 'github', 'arxiv', 'wikipedia'], description="List of SearxNG search engines to use")]
    """List of SearxNG search engines to use"""
    categories: Annotated[List[Literal["general", "news", "science", "it", "shopping", "images", "videos", "music", "files", "social"]], Field(default_factory=lambda: ['general', 'news', 'science', 'it'], description="SearxNG search categories to include")]
    """SearxNG search categories to include"""
    language: Annotated[Literal["en", "es", "fr", "de", "it", "pt", "zh", "ja", "ko", "ru", "ar"], Field(default='en', description="Language for search results")]
    """Language for search results"""
    safesearch: Annotated[int, Field(default=0, description="Safe search level (0=off, 1=moderate, 2=strict)", ge=0, le=2)]
    """Safe search level (0=off, 1=moderate, 2=strict)"""
    time_range: Annotated[Optional[Literal["", "day", "week", "month", "year"]], Field(default='', description="Time range filter for results")] = ''
    """Time range filter for results"""
    searx_host: Annotated[Optional[str], Field(default='', description="SearxNG host URL (defaults to SEARX_HOST environment variable)")] = ''
    """SearxNG host URL (defaults to SEARX_HOST environment variable)"""
    timeout: Annotated[Optional[float], Field(default=30.0, description="Search timeout in seconds", ge=5.0, le=120.0)] = 30.0
    """Search timeout in seconds"""
    user_agent: Annotated[Optional[str], Field(default='LLMMLLab-WebSearch/1.0', description="Custom User-Agent string for requests")] = 'LLMMLLab-WebSearch/1.0'
    """Custom User-Agent string for requests"""
    enable_caching: Annotated[Optional[bool], Field(default=True, description="Enable result caching for performance")] = True
    """Enable result caching for performance"""
    cache_ttl: Annotated[Optional[int], Field(default=300, description="Cache time-to-live in seconds", ge=60, le=3600)] = 300
    """Cache time-to-live in seconds"""
    max_content_length: Annotated[Optional[int], Field(default=5000, description="Maximum content length to fetch from URLs (in characters)", ge=1000, le=100000)] = 5000
    """Maximum content length to fetch from URLs (in characters)"""

    class Config:
        extra = "ignore"