# Code generated by schema2code at 2026-02-23 16:06:02. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class Data(BaseModel):
    """Event data payload.
"""
    id: Annotated[str, Field(..., description="The unique ID of the batch API request. ")]
    """The unique ID of the batch API request. """

    class Config:
        extra = "ignore"

class WebhookBatchCancelled(BaseModel):
    """Sent when a batch API request has been cancelled.
"""
    created_at: Annotated[int, Field(..., description="The Unix timestamp (in seconds) of when the batch API request was cancelled. ")]
    """The Unix timestamp (in seconds) of when the batch API request was cancelled. """
    data: Annotated[Data, Field(..., description="Event data payload. ")]
    """Event data payload. """
    id: Annotated[str, Field(..., description="The unique ID of the event. ")]
    """The unique ID of the event. """
    object: Annotated[Optional[Literal["event"]], Field(default=None, description="The object of the event. Always `event`. ")] = None
    """The object of the event. Always `event`. """
    type: Annotated[Literal["batch.cancelled"], Field(..., description="The type of the event. Always `batch.cancelled`. ")]
    """The type of the event. Always `batch.cancelled`. """

    class Config:
        extra = "ignore"

WebhookBatchCancelled.model_rebuild()