$schema: http://json-schema.org/draft-07/schema#
title: InferenceServiceConfig
description: Inference services configuration
type: object
properties:
  ollama:
    $ref: inference_service.yaml
  stable_diffusion:
    $ref: inference_service.yaml
  host:
    type: string
    description: Host for the inference service
  port:
    type: integer
    description: Port for the inference service
required:
  - ollama
  - stable_diffusion
  - host
  - port
