$schema: http://json-schema.org/draft-07/schema#
title: PreferencesConfig
description: User preferences
type: object
properties:
  default_profile_id:
    type: string
    description: Default profile ID
  theme:
    type: string
    description: Theme
  font_size:
    type: integer
    description: Font size
  notifications_on:
    type: boolean
    description: Notifications enabled
  language:
    type: string
    description: Language
