$schema: http://json-schema.org/draft-07/schema#
title: ServerConfig
description: Server configuration
type: object
properties:
  host:
    type: string
    description: Server host
  port:
    type: integer
    description: Server port
  base_url:
    type: string
    description: Base URL
required:
  - host
  - port
  - base_url
